<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tcl="http://emcs.dgtaxud.ec/v10/tcl" targetNamespace="http://emcs.dgtaxud.ec/v10/tcl" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.00">
	<!--=========================================-->
	<!--===== Technical Message Version =====-->
	<!--=========================================-->
	<xs:simpleType name="TechnicalMessageVersion">
		<xs:annotation>
			<xs:documentation>Technical Message Version</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:enumeration value="1.0">
				<xs:annotation>
					<xs:documentation>XML version</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Common Request Type =====-->
	<!--=========================================-->
	<xs:simpleType name="CommonRequestType">
		<xs:annotation>
			<xs:documentation>Common Request Type</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>(reserved)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>Request for reference data</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="3">
				<xs:annotation>
					<xs:documentation>Request for EOL</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="4">
				<xs:annotation>
					<xs:documentation>(reserved)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="5">
				<xs:annotation>
					<xs:documentation>Request for re-synchronisation of the register of economic operators</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="6">
				<xs:annotation>
					<xs:documentation>Request for retrieval of a list of e-AADs</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Request Message Name =====-->
	<!--=========================================-->
	<xs:simpleType name="RequestMessageName">
		<xs:annotation>
			<xs:documentation>Request Message Name</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:enumeration value="C_COD_DAT">
				<xs:annotation>
					<xs:documentation>Common list of codes</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="C_PAR_DAT">
				<xs:annotation>
					<xs:documentation>Common system parameters</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="ALL">
				<xs:annotation>
					<xs:documentation>For complete structure</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Primary Criterion Type Code =====-->
	<!--=========================================-->
	<xs:simpleType name="PrimaryCriterionTypeCode">
		<xs:annotation>
			<xs:documentation>Primary Criterion Type Code</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>ARC</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>Brand name of product</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="3">
				<xs:annotation>
					<xs:documentation>Categories of goods of the movement</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="4">
				<xs:annotation>
					<xs:documentation>Change of consignee</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="5">
				<xs:annotation>
					<xs:documentation>(reserved)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="6">
				<xs:annotation>
					<xs:documentation>(reserved)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="7">
				<xs:annotation>
					<xs:documentation>Change of transporter</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="8">
				<xs:annotation>
					<xs:documentation>City of consignee</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="9">
				<xs:annotation>
					<xs:documentation>City of consignor</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="10">
				<xs:annotation>
					<xs:documentation>City of guarantor</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="11">
				<xs:annotation>
					<xs:documentation>(reserved)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="12">
				<xs:annotation>
					<xs:documentation>City of place of delivery</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="13">
				<xs:annotation>
					<xs:documentation>City of tax warehouse of dispatch</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="14">
				<xs:annotation>
					<xs:documentation>City of transporter</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="15">
				<xs:annotation>
					<xs:documentation>CN code of product</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="16">
				<xs:annotation>
					<xs:documentation>Date of invoice</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="17">
				<xs:annotation>
					<xs:documentation>Excise number of consignee</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="18">
				<xs:annotation>
					<xs:documentation>Excise number of consignor</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="19">
				<xs:annotation>
					<xs:documentation>Excise number of guarantor</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="20">
				<xs:annotation>
					<xs:documentation>(reserved)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="21">
				<xs:annotation>
					<xs:documentation>(reserved)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="22">
				<xs:annotation>
					<xs:documentation>Excise number of the tax warehouse of destination</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="23">
				<xs:annotation>
					<xs:documentation>Excise number of the tax warehouse of dispatch</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="24">
				<xs:annotation>
					<xs:documentation>(reserved)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="25">
				<xs:annotation>
					<xs:documentation>Excise product code</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="26">
				<xs:annotation>
					<xs:documentation>Journey time</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="27">
				<xs:annotation>
					<xs:documentation>Member State of destination</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="28">
				<xs:annotation>
					<xs:documentation>Member State of dispatch</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="29">
				<xs:annotation>
					<xs:documentation>Name of consignee</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="30">
				<xs:annotation>
					<xs:documentation>Name of consignor</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="31">
				<xs:annotation>
					<xs:documentation>Name of guarantor</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="32">
				<xs:annotation>
					<xs:documentation>(reserved)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="33">
				<xs:annotation>
					<xs:documentation>Name of place of delivery</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="34">
				<xs:annotation>
					<xs:documentation>Name of tax warehouse of dispatch</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="35">
				<xs:annotation>
					<xs:documentation>Name of transporter</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="36">
				<xs:annotation>
					<xs:documentation>Number of invoice</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="37">
				<xs:annotation>
					<xs:documentation>Postal code of consignee</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="38">
				<xs:annotation>
					<xs:documentation>Postal code of consignor</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="39">
				<xs:annotation>
					<xs:documentation>Postal code of guarantor</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="40">
				<xs:annotation>
					<xs:documentation>(reserved)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="41">
				<xs:annotation>
					<xs:documentation>Postal code of place of delivery</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="42">
				<xs:annotation>
					<xs:documentation>Postal code of tax warehouse of dispatch</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="43">
				<xs:annotation>
					<xs:documentation>Postal code of transporter</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="44">
				<xs:annotation>
					<xs:documentation>Quantity of goods (sum of quantities for a group)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="45">
				<xs:annotation>
					<xs:documentation>Local Reference Number, being a serial number, assigned by the consignor</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="46">
				<xs:annotation>
					<xs:documentation>Type of transport</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="47">
				<xs:annotation>
					<xs:documentation>(reserved)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="48">
				<xs:annotation>
					<xs:documentation>(reserved)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="49">
				<xs:annotation>
					<xs:documentation>VAT number of the consignee</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="50">
				<xs:annotation>
					<xs:documentation>(reserved)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="51">
				<xs:annotation>
					<xs:documentation>VAT number of transport</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Common Request Rejection Reason =====-->
	<!--=========================================-->
	<xs:simpleType name="CommonRequestRejectionReason">
		<xs:annotation>
			<xs:documentation>Common Request Rejection Reason</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="0">
				<xs:annotation>
					<xs:documentation>Other</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>No e-AAD(s) retrieved matching selection criteria</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="3">
				<xs:annotation>
					<xs:documentation>Reference data not available</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="4">
				<xs:annotation>
					<xs:documentation>Excise Office List not available</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="5">
				<xs:annotation>
					<xs:documentation>SEED data not available</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="7">
				<xs:annotation>
					<xs:documentation>Unknown requested data</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="8">
				<xs:annotation>
					<xs:documentation>Increment number out of range</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="26">
				<xs:annotation>
					<xs:documentation>Duplicate detected</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="112">
				<xs:annotation>
					<xs:documentation>Incorrect (code) value</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="115">
				<xs:annotation>
					<xs:documentation>Not supported in this position</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Type of Recall =====-->
	<!--=========================================-->
	<xs:simpleType name="TypeOfRecall">
		<xs:annotation>
			<xs:documentation>Type of Recall</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>STA_PERIOD</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>STA_OPERATION</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="3">
				<xs:annotation>
					<xs:documentation>STA_APPLICATION</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="4">
				<xs:annotation>
					<xs:documentation>STA_BUSINESS</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="5">
				<xs:annotation>
					<xs:documentation>STA_EWSE</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="6">
				<xs:annotation>
					<xs:documentation>STA_MVS</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="7">
				<xs:annotation>
					<xs:documentation>STA_MA</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="8">
				<xs:annotation>
					<xs:documentation>STA_AD-HOC QUERY</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Requested List of Codes (external) =====-->
	<!--=========================================-->
	<xs:simpleType name="RequestedListOfCodesExternal">
		<xs:annotation>
			<xs:documentation>Requested List of Codes (external)</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>Units of measure</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="3">
				<xs:annotation>
					<xs:documentation>Evidence types</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="4">
				<xs:annotation>
					<xs:documentation>(reserved)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="5">
				<xs:annotation>
					<xs:documentation>(reserved)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="6">
				<xs:annotation>
					<xs:documentation>Language codes</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="7">
				<xs:annotation>
					<xs:documentation>Member states</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="8">
				<xs:annotation>
					<xs:documentation>Country codes</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="9">
				<xs:annotation>
					<xs:documentation>Packaging codes</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="10">
				<xs:annotation>
					<xs:documentation>Reasons for unsatisfactory receipt or control report</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="11">
				<xs:annotation>
					<xs:documentation>Reasons for interruption</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="12">
				<xs:annotation>
					<xs:documentation>(reserved)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="13">
				<xs:annotation>
					<xs:documentation>Transport modes</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="14">
				<xs:annotation>
					<xs:documentation>Transport units</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="15">
				<xs:annotation>
					<xs:documentation>Wine-growing zones</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="16">
				<xs:annotation>
					<xs:documentation>Wine manipulation codes</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="17">
				<xs:annotation>
					<xs:documentation>Excise product categories</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="18">
				<xs:annotation>
					<xs:documentation>Excise products</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="19">
				<xs:annotation>
					<xs:documentation>CN codes</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="20">
				<xs:annotation>
					<xs:documentation>Correspondences CN code - Excise product</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="21">
				<xs:annotation>
					<xs:documentation>Cancellation reasons</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="22">
				<xs:annotation>
					<xs:documentation>Alert or rejection of e-AAD reasons</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="23">
				<xs:annotation>
					<xs:documentation>Delay explanations</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="24">
				<xs:annotation>
					<xs:documentation>(reserved)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="25">
				<xs:annotation>
					<xs:documentation>Event declaring person capacities</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>Event types</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Action Code =====-->
	<!--=========================================-->
	<xs:simpleType name="ActionCode">
		<xs:annotation>
			<xs:documentation>Action Code</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>Flag alert</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Global Conclusion Of Receipt =====-->
	<!--=========================================-->
	<xs:simpleType name="GlobalConclusionOfReceipt">
		<xs:annotation>
			<xs:documentation>Global Conclusion Of Receipt</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>Receipt accepted and satisfactory</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>Receipt accepted although unsatisfactory</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="3">
				<xs:annotation>
					<xs:documentation>Receipt refused</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="4">
				<xs:annotation>
					<xs:documentation>Receipt partially refused</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="11">
				<xs:annotation>
					<xs:documentation>Export Refused</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="21">
				<xs:annotation>
					<xs:documentation>Exit accepted and satisfactory</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="22">
				<xs:annotation>
					<xs:documentation>Exit accepted although unsatisfactory</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="23">
				<xs:annotation>
					<xs:documentation>Exit refused</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== History Message Type =====-->
	<!--=========================================-->
	<xs:simpleType name="HistoryMessageType">
		<xs:annotation>
			<xs:documentation>History Message Type</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>Message sent in response to a request for download</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>Message sent in the course of business (change of destination)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== SEED Message Type =====-->
	<!--=========================================-->
	<xs:simpleType name="SeedMessageType">
		<xs:annotation>
			<xs:documentation>SEED Message Type</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>Update of economic operators (Notification of changes to CD/RD)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>Dissemination of updates of economic operators</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="3">
				<xs:annotation>
					<xs:documentation>Retrieval of economic operators</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="4">
				<xs:annotation>
					<xs:documentation>Extraction of economic operators</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Subject Code =====-->
	<!--=========================================-->
	<xs:simpleType name="SubjectCode">
		<xs:annotation>
			<xs:documentation>Subject Code</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>e-AAD</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>(reserved)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="3">
				<xs:annotation>
					<xs:documentation>e-AADs linked by splitting</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="4">
				<xs:annotation>
					<xs:documentation>(reserved)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="5">
				<xs:annotation>
					<xs:documentation>(reserved)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="6">
				<xs:annotation>
					<xs:documentation>e-AADs submitted by the same consignor</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="7">
				<xs:annotation>
					<xs:documentation>e-AADs intended for the same consignee</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Modification Type =====-->
	<!--=========================================-->
	<xs:simpleType name="ModificationType">
		<xs:annotation>
			<xs:documentation>Modification Type</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:enumeration value="C">
				<xs:annotation>
					<xs:documentation>Create</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="U">
				<xs:annotation>
					<xs:documentation>Update</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="I">
				<xs:annotation>
					<xs:documentation>Invalidate</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Requested List of Codes (full) =====-->
	<!--=========================================-->
	<xs:simpleType name="RequestedListOfCodesFull">
		<xs:annotation>
			<xs:documentation>Requested List of Codes (full)</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>Units of measure</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>Events types</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="3">
				<xs:annotation>
					<xs:documentation>Evidence types</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="4">
				<xs:annotation>
					<xs:documentation>(reserved)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="5">
				<xs:annotation>
					<xs:documentation>(reserved)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="6">
				<xs:annotation>
					<xs:documentation>Language codes</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="7">
				<xs:annotation>
					<xs:documentation>Member states</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="8">
				<xs:annotation>
					<xs:documentation>Country codes</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="9">
				<xs:annotation>
					<xs:documentation>Packaging codes</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="10">
				<xs:annotation>
					<xs:documentation>Reasons for unsatisfactory receipt or control report</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="11">
				<xs:annotation>
					<xs:documentation>Reasons for interruption</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="12">
				<xs:annotation>
					<xs:documentation>(reserved)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="13">
				<xs:annotation>
					<xs:documentation>Transport modes</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="14">
				<xs:annotation>
					<xs:documentation>Transport units</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="15">
				<xs:annotation>
					<xs:documentation>Wine-growing zones</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="16">
				<xs:annotation>
					<xs:documentation>Wine operations codes</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="17">
				<xs:annotation>
					<xs:documentation>Excise product categories</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="18">
				<xs:annotation>
					<xs:documentation>Excise products</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="19">
				<xs:annotation>
					<xs:documentation>CN codes</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="20">
				<xs:annotation>
					<xs:documentation>Correspondences CN code - Excise product</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="21">
				<xs:annotation>
					<xs:documentation>Cancellation reasons</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="22">
				<xs:annotation>
					<xs:documentation>Alert or rejection of e-AAD reasons</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="23">
				<xs:annotation>
					<xs:documentation>Delay explanations</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="24">
				<xs:annotation>
					<xs:documentation>(reserved)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="25">
				<xs:annotation>
					<xs:documentation>Event submitting person capacities</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="26">
				<xs:annotation>
					<xs:documentation>History refusal reasons</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="27">
				<xs:annotation>
					<xs:documentation>Reasons for delayed feedback</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="28">
				<xs:annotation>
					<xs:documentation>Movement verification actions</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="29">
				<xs:annotation>
					<xs:documentation>Reasons for request movement verification</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="30">
				<xs:annotation>
					<xs:documentation>Application statistics action types</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="31">
				<xs:annotation>
					<xs:documentation>Business statistics action types</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="32">
				<xs:annotation>
					<xs:documentation>Operation statistics action types</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="33">
				<xs:annotation>
					<xs:documentation>Statistics application exception types</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="34">
				<xs:annotation>
					<xs:documentation>Reasons for checks not possible in EWSE</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="35">
				<xs:annotation>
					<xs:documentation>Common request rejection reasons</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="36">
				<xs:annotation>
					<xs:documentation>Update of economic operator rejection reason</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Flag =====-->
	<!--=========================================-->
	<xs:simpleType name="Flag">
		<xs:annotation>
			<xs:documentation>Flag</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="1"/>
			<xs:pattern value="[.0-1]{0,1}"/>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Guarantor Type Code =====-->
	<!--=========================================-->
	<xs:simpleType name="GuarantorTypeCode">
		<xs:annotation>
			<xs:documentation>Guarantor Type Code</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>Consignor</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>Transporter</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="3">
				<xs:annotation>
					<xs:documentation>Owner of the Excise products</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="4">
				<xs:annotation>
					<xs:documentation>Consignee</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="12">
				<xs:annotation>
					<xs:documentation>Joint guarantee of the consignor and of the transporter</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="13">
				<xs:annotation>
					<xs:documentation>Joint guarantee of the consignor and of the owner of the Excise products</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="14">
				<xs:annotation>
					<xs:documentation>Joint guarantee of the consignor and of the consignee</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="23">
				<xs:annotation>
					<xs:documentation>Joint guarantee of the transporter and of the owner of the Excise products</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="24">
				<xs:annotation>
					<xs:documentation>Joint guarantee of the transporter and of the consignee</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="34">
				<xs:annotation>
					<xs:documentation>Joint guarantee of the owner of the Excise products and of the consignee</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="123">
				<xs:annotation>
					<xs:documentation>Joint guarantee of the consignor, of the transporter and of the owner of the Excise products</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="124">
				<xs:annotation>
					<xs:documentation>Joint guarantee of the consignor, of the transporter and of the consignee</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="134">
				<xs:annotation>
					<xs:documentation>Joint guarantee of the consignor, of the owner of the Excise products and of the consignee</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="234">
				<xs:annotation>
					<xs:documentation>Joint guarantee of the transporter, of the owner of the Excise products and of the consignee</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="1234">
				<xs:annotation>
					<xs:documentation>Joint guarantee of the consignor, of the transporter, of the owner of the Excise products and of the consignee</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="5">
				<xs:annotation>
					<xs:documentation>No guarantee is provided according to Article 18.4(b) of 2008/118/EC</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Origin Type Code =====-->
	<!--=========================================-->
	<xs:simpleType name="OriginTypeCode">
		<xs:annotation>
			<xs:documentation>Origin Type Code</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>Origin - Tax warehouse</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>Origin - Import</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Destination Type Code =====-->
	<!--=========================================-->
	<xs:simpleType name="DestinationTypeCode">
		<xs:annotation>
			<xs:documentation>Destination Type Code</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>Destination - Tax warehouse</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>Destination - Registered consignee</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="3">
				<xs:annotation>
					<xs:documentation>Destination - Temporary registered consignee</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="4">
				<xs:annotation>
					<xs:documentation>Destination - Direct delivery</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="5">
				<xs:annotation>
					<xs:documentation>Destination - Exempted organisation</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="6">
				<xs:annotation>
					<xs:documentation>Destination - Export</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="8">
				<xs:annotation>
					<xs:documentation>Unknown destination (consignee unknown)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Category of Wine Product =====-->
	<!--=========================================-->
	<xs:simpleType name="CategoryOfWineProduct">
		<xs:annotation>
			<xs:documentation>Category of Wine Product</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="1"/>
			<xs:pattern value="[.1-5]{0,1}"/>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Notification Type =====-->
	<!--=========================================-->
	<xs:simpleType name="NotificationType">
		<xs:annotation>
			<xs:documentation>Notification Type</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>Change of destination</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Indicator of Shortage or Excess =====-->
	<!--=========================================-->
	<xs:simpleType name="IndicatorOfShortageOrExcess">
		<xs:annotation>
			<xs:documentation>Indicator of Shortage or Excess</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:enumeration value="E">
				<xs:annotation>
					<xs:documentation>Excess</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="S">
				<xs:annotation>
					<xs:documentation>Shortage</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Reminder Message Type =====-->
	<!--=========================================-->
	<xs:simpleType name="ReminderMessageType">
		<xs:annotation>
			<xs:documentation>Reminder Message Type</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>Reminder message at expiry of time to change destination</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>Reminder message at expiry of time to send the report of receipt</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Functional Error Codes =====-->
	<!--=========================================-->
	<xs:simpleType name="FunctionalErrorCodes">
		<xs:annotation>
			<xs:documentation>Functional Error Codes</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="0">
				<xs:annotation>
					<xs:documentation>Other</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="12">
				<xs:annotation>
					<xs:documentation>Incorrect (code) value</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="15">
				<xs:annotation>
					<xs:documentation>Not supported in this position</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="26">
				<xs:annotation>
					<xs:documentation>Duplicate detected</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="90">
				<xs:annotation>
					<xs:documentation>Unknown ARC</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="93">
				<xs:annotation>
					<xs:documentation>Invalid ARC</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="91">
				<xs:annotation>
					<xs:documentation>Duplicate LRN</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="92">
				<xs:annotation>
					<xs:documentation>Message out of sequence</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Technical Message Type =====-->
	<!--=========================================-->
	<xs:simpleType name="TechnicalMessageType">
		<xs:annotation>
			<xs:documentation>Technical Message Type</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:enumeration value="CD801">
				<xs:annotation>
					<xs:documentation>E-AAD</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="CD802">
				<xs:annotation>
					<xs:documentation>REMINDER MESSAGE FOR EXCISE MOVEMENT</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="CD810">
				<xs:annotation>
					<xs:documentation>CANCELLATION OF EAAD</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="CD813">
				<xs:annotation>
					<xs:documentation>CHANGE OF DESTINATION</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="CD818">
				<xs:annotation>
					<xs:documentation>ACCEPTED OR (PARTIALLY) REFUSED REPORT OF RECEIPT</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="CD829">
				<xs:annotation>
					<xs:documentation>NOTIFICATION OF ACCEPTED EXPORT</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="CD837">
				<xs:annotation>
					<xs:documentation>EXPLANATION ON DELAY FOR DELIVERY</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="CD839">
				<xs:annotation>
					<xs:documentation>REJECTION OF E-AAD FOR EXPORT</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="CD905">
				<xs:annotation>
					<xs:documentation>STATUS RESPONSE</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Submitter Type =====-->
	<!--=========================================-->
	<xs:simpleType name="SubmitterType">
		<xs:annotation>
			<xs:documentation>Submitter Type</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>Consignor</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>Consignee</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Reason to refuse update of economic operators =====-->
	<!--=========================================-->
	<xs:simpleType name="ReasonToRefuseUpdateOfEconomicOperators">
		<xs:annotation>
			<xs:documentation>Reason to refuse update of economic operators</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="0">
				<xs:annotation>
					<xs:documentation>Other</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="8">
				<xs:annotation>
					<xs:documentation>Trader Authorisation already exists (creation)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="9">
				<xs:annotation>
					<xs:documentation>Tax warehouse already exists (creation)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="10">
				<xs:annotation>
					<xs:documentation>Temporary authorisation already exists (creation)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="11">
				<xs:annotation>
					<xs:documentation>Trader Authorisation not found (Update / Deletion)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="12">
				<xs:annotation>
					<xs:documentation>Tax warehouse not found (Update / Deletion)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="13">
				<xs:annotation>
					<xs:documentation>Temporary authorisation not found (Update / Deletion)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="26">
				<xs:annotation>
					<xs:documentation>Duplicate detected</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="27">
				<xs:annotation>
					<xs:documentation>Inconsistency between Excise number and Excise office</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="41">
				<xs:annotation>
					<xs:documentation>Only a warehouse keeper may be allowed to use a tax warehouse</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="112">
				<xs:annotation>
					<xs:documentation>Incorrect (code) value</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="115">
				<xs:annotation>
					<xs:documentation>Not supported in this position</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Requested Message Type =====-->
	<!--=========================================-->
	<xs:simpleType name="RequestedMessageType">
		<xs:annotation>
			<xs:documentation>Requested Message Type</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:enumeration value="CD801">
				<xs:annotation>
					<xs:documentation>E-AAD</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="CD810">
				<xs:annotation>
					<xs:documentation>CANCELLATION OF EAAD</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="CD813">
				<xs:annotation>
					<xs:documentation>CHANGE OF DESTINATION</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="CD818">
				<xs:annotation>
					<xs:documentation>ACCEPTED OR (PARTIALLY) REFUSED REPORT OF RECEIPT</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="CD829">
				<xs:annotation>
					<xs:documentation>NOTIFICATION OF ACCEPTED EXPORT</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="CD839">
				<xs:annotation>
					<xs:documentation>REJECTION OF E-AAD FOR EXPORT</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="None">
				<xs:annotation>
					<xs:documentation>NONE</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Operator Type Code =====-->
	<!--=========================================-->
	<xs:simpleType name="OperatorTypeCode">
		<xs:annotation>
			<xs:documentation>Operator Type Code</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>Authorised warehouse keeper</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>Registered consignee</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="3">
				<xs:annotation>
					<xs:documentation>Registered consignor</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="4">
				<xs:annotation>
					<xs:documentation>Other registered operator (possible guarantor, e.g. transporter)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Operator Role Code =====-->
	<!--=========================================-->
	<xs:simpleType name="OperatorRoleCode">
		<xs:annotation>
			<xs:documentation>Operator Role Code</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>Allowed to practice direct delivery</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>Allowed to leave empty the destination fields according to Article 15(6) of the Directive</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Transport Arrangement =====-->
	<!--=========================================-->
	<xs:simpleType name="TransportArrangement">
		<xs:annotation>
			<xs:documentation>Transport Arrangement</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>Consignor</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>Consignee</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="3">
				<xs:annotation>
					<xs:documentation>Owner of goods</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="4">
				<xs:annotation>
					<xs:documentation>Other</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Diagnosis Code =====-->
	<!--=========================================-->
	<xs:simpleType name="DiagnosisCode">
		<xs:annotation>
			<xs:documentation>Diagnosis Code</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>Unknown ARC</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>Body Record Unique Reference does not exist in the e-AAD</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="3">
				<xs:annotation>
					<xs:documentation>No corresponding GOODS ITEM in the export declaration</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="4">
				<xs:annotation>
					<xs:documentation>Weight/mass do not match</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="5">
				<xs:annotation>
					<xs:documentation>The destination type code of the e-AAD is not export</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Message Role Code =====-->
	<!--=========================================-->
	<xs:simpleType name="MessageRoleCode">
		<xs:annotation>
			<xs:documentation>Message Role Code</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>Explanation on delay for sending the report of receipt</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Status Request Message Type =====-->
	<!--=========================================-->
	<xs:simpleType name="StatusRequestMessageType">
		<xs:annotation>
			<xs:documentation>Status Request Message Type</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>Status Synchronisation Request</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>Movement History Request</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Change of Destination Type Code =====-->
	<!--=========================================-->
	<xs:simpleType name="ChangeOfDestinationTypeCode">
		<xs:annotation>
			<xs:documentation>Change of Destination Type Code</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>Destination - Tax warehouse</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>Destination - Registered consignee</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="3">
				<xs:annotation>
					<xs:documentation>Destination - Temporary registered consignee</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="4">
				<xs:annotation>
					<xs:documentation>Destination - Direct delivery</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="6">
				<xs:annotation>
					<xs:documentation>Destination - Export</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Excise Operate State Types =====-->
	<!--=========================================-->
	<xs:simpleType name="StatusType">
		<xs:annotation>
			<xs:documentation>Change of Destination Type Code</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:enumeration value="X01">
				<xs:annotation>
					<xs:documentation>Accepted</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="X02">
				<xs:annotation>
					<xs:documentation>Cancelled</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="X03">
				<xs:annotation>
					<xs:documentation>Delivered</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="X04">
				<xs:annotation>
					<xs:documentation>Diverted</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="X05">
				<xs:annotation>
					<xs:documentation>(reserved)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="X06">
				<xs:annotation>
					<xs:documentation>(reserved)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="X07">
				<xs:annotation>
					<xs:documentation>e-AAD Manually Closed</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="X08">
				<xs:annotation>
					<xs:documentation>Refused</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="X09">
				<xs:annotation>
					<xs:documentation>None</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="X10">
				<xs:annotation>
					<xs:documentation>Partially Refused</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="X11">
				<xs:annotation>
					<xs:documentation>Exporting</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="X12">
				<xs:annotation>
					<xs:documentation>Accepted for Export</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="IterationTotalType">
		<xs:annotation>
			<xs:documentation>Iteration Total</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="2"/>
			<xs:pattern value="[0-9]{3}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="IterationTotal99Type">
		<xs:annotation>
			<xs:documentation>Iteration Total</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="99"/>
			<xs:pattern value="[0-9]{3}"/>
		</xs:restriction>
	</xs:simpleType>	
		<xs:simpleType name="IterationTotal9Type">
		<xs:annotation>
			<xs:documentation>Iteration Total</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="9"/>			
			<xs:pattern value="[0-9]{3}"/>
		</xs:restriction>
	</xs:simpleType>	
	<xs:simpleType name="IterationCodeType">
		<xs:annotation>
			<xs:documentation>Iteration Code</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:enumeration value="G">
				<xs:annotation>
					<xs:documentation>Import DAU</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="H">
				<xs:annotation>
					<xs:documentation>Guarantee</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="I">
				<xs:annotation>
					<xs:documentation>Transport Details</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="L">
				<xs:annotation>
					<xs:documentation>Certificate</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="M">
				<xs:annotation>
					<xs:documentation>Imballaggi</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="O">
				<xs:annotation>
					<xs:documentation>Wine Tratements</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="P">
				<xs:annotation>
					<xs:documentation>Transport Details</xs:documentation>
				</xs:annotation>
			</xs:enumeration>			
			<xs:enumeration value="Q">
				<xs:annotation>
					<xs:documentation>Unsatisfactory Reason</xs:documentation>
				</xs:annotation>
			</xs:enumeration>	
			<xs:enumeration  value="S">
				<xs:annotation>
					<xs:documentation>Alert Or Rejection Reason</xs:documentation>
				</xs:annotation>
			</xs:enumeration>											
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="IterationNumber99Type">
		<xs:annotation>
			<xs:documentation>IterationNumber</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="99"/>
			<xs:pattern value="[0-9]{3}"/>
		</xs:restriction>
	</xs:simpleType>
		<xs:simpleType name="IterationNumber9Type">
		<xs:annotation>
			<xs:documentation>IterationNumber</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="9"/>		
			<xs:pattern value="[0-9]{3}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="IterationNumberType">
		<xs:annotation>
			<xs:documentation>IterationNumber</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="3"/>
			<xs:pattern value="[0-9]{1,3}"/>
		</xs:restriction>
	</xs:simpleType>	
</xs:schema>
