<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:doc="http://emcs.dgtaxud.ec/v10/doc" xmlns:emcs="http://emcs.dgtaxud.ec/v10/types_2" xmlns:ns1="http://emcs.dgtaxud.ec/v10/types" xmlns:ns2="urn:publicid:-:EC:DGTAXUD:EMCS:PHASE3:DOC:V1.71" targetNamespace="http://emcs.dgtaxud.ec/v10/types" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.00">
	<!--xs:import namespace="http://emcs.dgtaxud.ec/v10/doc" schemaLocation="doc.xsd"/-->
	<xs:import namespace="urn:publicid:-:EC:DGTAXUD:EMCS:PHASE3:DOC:V1.76" schemaLocation="doc.xsd"/>
	<xs:simpleType name="AadReferenceCodeType">
		<xs:restriction base="xs:token">
			<xs:length value="21"/>
			<xs:pattern value="[0-9]{2}[A-Z]{2}[a-zA-Z0-9]{16}[0-9]"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ExciseNumberType">
		<xs:restriction base="xs:token">
			<xs:length value="13"/>
			<xs:pattern value="[a-zA-Z0-9]{13}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ExciseOfficeCodeType">
		<xs:restriction base="xs:token">
			<xs:length value="8"/>
			<xs:pattern value="[a-zA-Z0-9]{8}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="VatNumberType">
		<xs:restriction base="xs:token">
			<xs:maxLength value="35"/>
			<xs:pattern value=".{0,35}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ExciseProductsCategoryCodeType">
		<xs:restriction base="xs:token">
			<xs:length value="1"/>
			<xs:pattern value="[A-Z]"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ExciseProductCodeType">
		<xs:restriction base="xs:token">
			<xs:length value="4"/>
			<xs:pattern value="[A-Z][0-9]{3}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ProductQuantityType">
		<xs:restriction base="xs:decimal">
			<xs:totalDigits value="15"/>
			<xs:fractionDigits value="3"/>
			<xs:minInclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="WeightType">
		<xs:restriction base="xs:decimal">
			<xs:totalDigits value="15"/>
			<xs:fractionDigits value="2"/>
			<xs:minInclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="PhoneNumberType">
		<xs:restriction base="xs:token">
			<xs:maxLength value="18"/>
			<xs:pattern value=".{1,18}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="EmailAddressType">
		<xs:restriction base="xs:token">
			<xs:maxLength value="70"/>
			<xs:pattern value=".{1,70}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="EoriNumberType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="EORI Number"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="17"/>
			<xs:pattern value=".{1,17}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="LanguageCodeType">
		<xs:restriction base="xs:token">
			<xs:length value="2"/>
			<xs:pattern value="([a-zA-Z]){2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CountryCodeType">
		<xs:restriction base="xs:token">
			<xs:maxLength value="2"/>
			<xs:pattern value="([a-zA-Z]){0,2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CodeListItemType">
		<xs:restriction base="xs:token"/>
	</xs:simpleType>
	<xs:simpleType name="TechnicalCodeListItemType">
		<xs:restriction base="xs:token"/>
	</xs:simpleType>
	<xs:simpleType name="CnCodeType">
		<xs:restriction base="xs:token">
			<xs:length value="8"/>
			<xs:pattern value="[0-9]{8}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="JourneyDurationType">
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:pattern value="[0-9]{2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="JourneyTimeType">
		<xs:annotation>
			<xs:documentation>
        The format of Journey Time or of Maximum Journey Time is expressed in hours or in days, 
        with the format Pdd, where:
        - "P" is a letter in ("H" = Hours or "D" = Day)
        - "dd" is a two digits number
        If P is "H" then the number is less or equal to 24
        If P is "D" then the number is less or equal to 92        
      </xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:length value="3"/>
			<xs:pattern value="(D|H)[0-9]{2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TimerDurationType">
		<xs:annotation>
			<xs:documentation>
        The format of Time To ... or Maximum Duration of ... is expressed in days, 
        months or years, with the format P999, where:
        - "P" is a letter in ("D" = Day, "M" = Month or "Y" = Year) 
        - "999" is a three digits number        
      </xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:length value="4"/>
			<xs:pattern value="(Y|M|D)[0-9]{3}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="PostCodeType">
		<xs:restriction base="xs:token">
			<xs:maxLength value="10"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ExtractionType">
		<xs:annotation>
			<xs:documentation>Extraction Flag</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="0">
				<xs:annotation>
					<xs:documentation>for retrieval (or missing in order to enable backward compatibility)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>for extraction</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="2">
				<xs:annotation>
					<xs:documentation>for non-invalidated records</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DateTimeType">
		<xs:annotation>
			<xs:documentation>The date is in the Common Era (minus sign in years is not permitted) and time zone although not included UTC is implied. The format must be yyyymmdd</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:dateTime">
			<xs:pattern value="\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DateType">
		<xs:annotation>
			<xs:documentation>The date is in the Common Era (minus sign in years is not permitted)</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:date">
			<xs:pattern value="\d{4}-\d{2}-\d{2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DateFlatType">
		<xs:annotation>
			<xs:documentation>The date is in the Common Era (minus sign in years is not permitted)</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="(19|20)(([0-9]){2})(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TimeType">
		<xs:annotation>
			<xs:documentation>The time zone although not included UTC is implied</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:time">
			<xs:pattern value="\d{2}:\d{2}:\d{2}(\.\d+)?"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TimeFlatType">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="000000"/>
			<xs:maxInclusive value="235959"/>
			<xs:pattern value="[0-9]{0,2}[0-9]{2,4}[0-9]{4,6}"/>
		</xs:restriction>
	</xs:simpleType>
	<!--==========================================================-->
	<!--===                  Sequence Number                   ===-->
	<!--==========================================================-->
	<xs:simpleType name="SequenceNumberType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Sequence Number"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="99"/>
			<xs:pattern value="[0-9]{2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SequenceNumber818Type">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Sequence Number"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:pattern value="[0-9]{1,2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AlcoholicStrengthType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Alcoholic strength"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="6"/>
			<xs:pattern value="[.0-9]{0,6}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="BodyRecordUniqueReferenceType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Body Record Unique Reference"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:length value="3"/>
			<xs:pattern value="[0-9]{3}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="BrandNameOfProductsType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Brand Name of Products"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="350"/>
			<xs:pattern value=".{0,350}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CityType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="City"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="50"/>
			<xs:pattern value=".{0,50}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CommercialDescriptionType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Commercial description"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="350"/>
			<xs:pattern value=".{0,350}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CommercialSealIdentificationType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Commercial Seal Identification"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="35"/>
			<xs:pattern value=".{0,35}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ComplementaryInformationType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Complementary Information"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="350"/>
			<xs:pattern value=".{0,350}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DegreePlatoType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Degree Plato"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="6"/>
			<xs:pattern value="[.0-9]{0,6}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DensityType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Density"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="6"/>
			<xs:pattern value="[.0-9]{0,6}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DesignationOfOriginType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Designation of Origin"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="350"/>
			<xs:pattern value=".{0,350}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DocumentDescriptionType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Document Description"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="350"/>
			<xs:pattern value=".{1,350}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="FiscalMarkType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Fiscal Mark"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="350"/>
			<xs:pattern value=".{0,350}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="IdentityOfTransportUnitsType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Identity of Transport Units"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="35"/>
			<xs:pattern value=".{0,35}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ImportSadNumberType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Import SAD Number"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="21"/>
			<xs:pattern value=".{1,21}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="InvoiceNumberType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Invoice Number"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="35"/>
			<xs:pattern value=".{1,35}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TARICCodeType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="TARIC Code"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="2"/>
			<xs:pattern value="[0-9]{0,2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AAMSCodeType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="AAMS Code"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="4"/>
			<xs:pattern value="[A-Z0-9]{0,4}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CADDCodeType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="CADDCode"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="4"/>
			<xs:pattern value="[A-Z0-9]{0,4}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CPAProductCategoryType">
		<xs:annotation>
			<xs:documentation>CPA Product Category</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:enumeration value="T">
				<xs:annotation>
					<xs:documentation>Tobacco</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="B">
				<xs:annotation>
					<xs:documentation>Beer</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="W">
				<xs:annotation>
					<xs:documentation>Wine</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="I">
				<xs:annotation>
					<xs:documentation>Intermediate alcholic product</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="S">
				<xs:annotation>
					<xs:documentation>Ethilic alcholic</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="E">
				<xs:annotation>
					<xs:documentation>Energy products</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Mesurement Journey Type=====-->
	<!--=========================================-->
	<xs:simpleType name="MesurementJourneyType">
		<xs:annotation>
			<xs:documentation>Mesurements journey type</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:enumeration value="D">
				<xs:annotation>
					<xs:documentation>Day</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="H">
				<xs:annotation>
					<xs:documentation>Hour</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="KindOfPackagesType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Kind of packages"/>
				<doc:codeList name="KindOfPackages"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:length value="2"/>
			<xs:pattern value=".{2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="LocalReferenceNumberType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Local Reference Number"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="22"/>
			<xs:pattern value="[0-9]{1,22}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="NumberOfPackagesType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Number of packages"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="15"/>
			<xs:pattern value="[0-9]{0,15}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="OtherInformationType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Other Information"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="350"/>
			<xs:pattern value=".{0,350}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ReferenceOfDocumentType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Reference of Document"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="350"/>
			<xs:pattern value=".{1,350}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SealInformationType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Seal Information"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="350"/>
			<xs:pattern value=".{0,350}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SerialNumberOfCertificateOfExemptionType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Serial Number of Certificate of Exemption"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="255"/>
			<xs:pattern value=".{0,255}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SizeOfProducerType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Size of Producer"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="15"/>
			<xs:pattern value="[0-9]{0,15}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="StreetNameType">
		<xs:restriction base="xs:token">
			<xs:maxLength value="65"/>
			<xs:pattern value=".{0,65}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="StreetNumberType">
		<xs:restriction base="xs:token">
			<xs:maxLength value="11"/>
			<xs:pattern value=".{0,11}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TraderNameType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Trader Name"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="182"/>
			<xs:pattern value=".{0,182}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TraderidType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="TraderID"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="18"/>
			<xs:pattern value=".{0,18}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TransportModeCodeType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Transport Mode Code"/>
				<doc:codeList name="TransportMode"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="2"/>
			<xs:pattern value="[0-9]{1,2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TransportUnitCodeType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Transport Unit Code"/>
				<doc:codeList name="TransportUnits"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:length value="2"/>
			<xs:pattern value="[0-9]{1,2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TransportUnitCode02Type">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Transport Unit Code"/>
				<doc:codeList name="TransportUnits"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="2"/>
			<xs:pattern value="[0-9]{0,2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="WineGrowingZoneCodeType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Wine-Growing Zone Code"/>
				<doc:codeList name="WineGrowingZoneCode"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="2"/>
			<xs:pattern value="[0-9]{0,2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="WineOperationCodeType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Wine Operation Code"/>
				<doc:codeList name="WineOperationCode"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="2"/>
			<xs:pattern value="[0-9]{1,2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="GuaranteeAccountCodeType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Guarantee Account Code"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="17"/>
			<xs:pattern value="[A-Za-n0-9]{0,17}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TypeGuaranteeType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Type Guarantee Type"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="1"/>
			<xs:pattern value="[EC]{0,1}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ImportGuaranteeType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Import Guarantee Type"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="15"/>
			<xs:pattern value="[.0-9]{0,15}"/>
		</xs:restriction>
	</xs:simpleType>
	<!--=========================================-->
	<!--===== Differite Flag Type =====-->
	<!--=========================================-->
	<xs:simpleType name="DifferiteFlagType">
		<xs:annotation>
			<xs:documentation>Differite Flag Type</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:enumeration value="0">
				<xs:annotation>
					<xs:documentation>True (Differite)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="1">
				<xs:annotation>
					<xs:documentation>False (No Differite)</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<!--==========================================================-->
	<!--===       Alert or Rejection of E-AD Reason Code       ===-->
	<!--==========================================================-->
	<xs:simpleType name="AlertOrRejectionOfEadReasonCodeType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Alert or Rejection of E-AD Reason Code"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="2"/>
			<xs:pattern value="[0-9]{1,2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ObservedShortageOrExcessType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Observed Shortage or Excess"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:decimal">
			<xs:totalDigits value="15"/>
			<xs:fractionDigits value="3"/>
			<xs:minInclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="UnsatisfactoryReasonCodeType">
		<xs:annotation>
			<xs:documentation>
				<doc:description value="Unsatisfactory Reason Code"/>
				<doc:codeList name="UnsatisfactoryReasonCode"/>
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:length value="1"/>
			<xs:pattern value="[0-9]"/>
		</xs:restriction>
	</xs:simpleType>
	<!--==========================================================-->
	<!--===              Cancellation Reason Code              ===-->
	<!--==========================================================-->
	<xs:simpleType name="CancellationReasonCodeType">
		<xs:restriction base="xs:token">
			<xs:length value="1"/>
			<xs:pattern value="[0-9]{1}"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>
