<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\AgronicaCoreStd\AgronicaCoreDTOStd\AgronicaCoreDTOStd.csproj" />
      <ProjectReference Include="..\AgronicaNetCore.Base\AgronicaNetCore.Base.csproj" />
      <ProjectReference Include="..\AgronicaNetCore.MetaSchema.DAL\AgronicaNetCore.MetaSchema.DAL.csproj" />
      <ProjectReference Include="..\AgronicaNetCore.ProfilazioneImprese.DAL\AgronicaNetCore.ProfilazioneImprese.DAL.csproj" />
      <ProjectReference Include="..\AgronicaNetCore.ProfilazioneMacchine.DAL\AgronicaNetCore.ProfilazioneMacchine.DAL.csproj" />
      <ProjectReference Include="..\AgronicaNetCore.Utenti.DAL\AgronicaNetCore.Utenti.DAL.csproj" />
      <ProjectReference Include="..\AgronicaNetCore.UtilityDB.DAL\AgronicaNetCore.UtilityDB.DAL.csproj" />
    </ItemGroup>

</Project>
