'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2470
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class DS_ProdottiFitosanitariMagazzino
    Inherits DataSet
    
    Private tableDS_ProdottiFitosanitariMagazzino As DS_ProdottiFitosanitariMagazzinoDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("DS_ProdottiFitosanitariMagazzino")) Is Nothing) Then
                Me.Tables.Add(New DS_ProdottiFitosanitariMagazzinoDataTable(ds.Tables("DS_ProdottiFitosanitariMagazzino")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property DS_ProdottiFitosanitariMagazzino As DS_ProdottiFitosanitariMagazzinoDataTable
        Get
            Return Me.tableDS_ProdottiFitosanitariMagazzino
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As DS_ProdottiFitosanitariMagazzino = CType(MyBase.Clone,DS_ProdottiFitosanitariMagazzino)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("DS_ProdottiFitosanitariMagazzino")) Is Nothing) Then
            Me.Tables.Add(New DS_ProdottiFitosanitariMagazzinoDataTable(ds.Tables("DS_ProdottiFitosanitariMagazzino")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableDS_ProdottiFitosanitariMagazzino = CType(Me.Tables("DS_ProdottiFitosanitariMagazzino"),DS_ProdottiFitosanitariMagazzinoDataTable)
        If (Not (Me.tableDS_ProdottiFitosanitariMagazzino) Is Nothing) Then
            Me.tableDS_ProdottiFitosanitariMagazzino.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "DS_ProdottiFitosanitariMagazzino"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/DS_ProdottiFitosanitariMagazzino.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableDS_ProdottiFitosanitariMagazzino = New DS_ProdottiFitosanitariMagazzinoDataTable
        Me.Tables.Add(Me.tableDS_ProdottiFitosanitariMagazzino)
    End Sub
    
    Private Function ShouldSerializeDS_ProdottiFitosanitariMagazzino() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub DS_ProdottiFitosanitariMagazzinoRowChangeEventHandler(ByVal sender As Object, ByVal e As DS_ProdottiFitosanitariMagazzinoRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class DS_ProdottiFitosanitariMagazzinoDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnData_Movimento As DataColumn
        
        Private columnCat_Cod As DataColumn
        
        Private columnCat_Des As DataColumn
        
        Private columnPro_Cod As DataColumn
        
        Private columnMat_Cod As DataColumn
        
        Private columnPro_Des As DataColumn
        
        Private columnCau_Mov As DataColumn
        
        Private columnUdm_Cod As DataColumn
        
        Private columnUdm_Sim As DataColumn
        
        Private columnQta As DataColumn
        
        Private columnGiacenza_Finale As DataColumn
        
        Private columnGiacenza_Iniziale As DataColumn
        
        Private columnPiva As DataColumn
        
        Private columnRag_Soc As DataColumn
        
        Private columnSa_Cod As DataColumn
        
        Private columnSa_Nome As DataColumn
        
        Private columnFabbicato_Cod As DataColumn
        
        Private columnFabbricato_Des As DataColumn
        
        Private columnAnnata As DataColumn
        
        Private columnElem_Cod As DataColumn
        
        Private columnCLTOSS_COD As DataColumn
        
        Private columnProvincia As DataColumn
        
        Private columnFr_Des As DataColumn
        
        Private columnMat_Des As DataColumn
        
        Private columnStr_Qta As DataColumn
        
        Friend Sub New()
            MyBase.New("DS_ProdottiFitosanitariMagazzino")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property Data_MovimentoColumn As DataColumn
            Get
                Return Me.columnData_Movimento
            End Get
        End Property
        
        Friend ReadOnly Property Cat_CodColumn As DataColumn
            Get
                Return Me.columnCat_Cod
            End Get
        End Property
        
        Friend ReadOnly Property Cat_DesColumn As DataColumn
            Get
                Return Me.columnCat_Des
            End Get
        End Property
        
        Friend ReadOnly Property Pro_CodColumn As DataColumn
            Get
                Return Me.columnPro_Cod
            End Get
        End Property
        
        Friend ReadOnly Property Mat_CodColumn As DataColumn
            Get
                Return Me.columnMat_Cod
            End Get
        End Property
        
        Friend ReadOnly Property Pro_DesColumn As DataColumn
            Get
                Return Me.columnPro_Des
            End Get
        End Property
        
        Friend ReadOnly Property Cau_MovColumn As DataColumn
            Get
                Return Me.columnCau_Mov
            End Get
        End Property
        
        Friend ReadOnly Property Udm_CodColumn As DataColumn
            Get
                Return Me.columnUdm_Cod
            End Get
        End Property
        
        Friend ReadOnly Property Udm_SimColumn As DataColumn
            Get
                Return Me.columnUdm_Sim
            End Get
        End Property
        
        Friend ReadOnly Property QtaColumn As DataColumn
            Get
                Return Me.columnQta
            End Get
        End Property
        
        Friend ReadOnly Property Giacenza_FinaleColumn As DataColumn
            Get
                Return Me.columnGiacenza_Finale
            End Get
        End Property
        
        Friend ReadOnly Property Giacenza_InizialeColumn As DataColumn
            Get
                Return Me.columnGiacenza_Iniziale
            End Get
        End Property
        
        Friend ReadOnly Property PivaColumn As DataColumn
            Get
                Return Me.columnPiva
            End Get
        End Property
        
        Friend ReadOnly Property Rag_SocColumn As DataColumn
            Get
                Return Me.columnRag_Soc
            End Get
        End Property
        
        Friend ReadOnly Property Sa_CodColumn As DataColumn
            Get
                Return Me.columnSa_Cod
            End Get
        End Property
        
        Friend ReadOnly Property Sa_NomeColumn As DataColumn
            Get
                Return Me.columnSa_Nome
            End Get
        End Property
        
        Friend ReadOnly Property Fabbicato_CodColumn As DataColumn
            Get
                Return Me.columnFabbicato_Cod
            End Get
        End Property
        
        Friend ReadOnly Property Fabbricato_DesColumn As DataColumn
            Get
                Return Me.columnFabbricato_Des
            End Get
        End Property
        
        Friend ReadOnly Property AnnataColumn As DataColumn
            Get
                Return Me.columnAnnata
            End Get
        End Property
        
        Friend ReadOnly Property Elem_CodColumn As DataColumn
            Get
                Return Me.columnElem_Cod
            End Get
        End Property
        
        Friend ReadOnly Property CLTOSS_CODColumn As DataColumn
            Get
                Return Me.columnCLTOSS_COD
            End Get
        End Property
        
        Friend ReadOnly Property ProvinciaColumn As DataColumn
            Get
                Return Me.columnProvincia
            End Get
        End Property
        
        Friend ReadOnly Property Fr_DesColumn As DataColumn
            Get
                Return Me.columnFr_Des
            End Get
        End Property
        
        Friend ReadOnly Property Mat_DesColumn As DataColumn
            Get
                Return Me.columnMat_Des
            End Get
        End Property
        
        Friend ReadOnly Property Str_QtaColumn As DataColumn
            Get
                Return Me.columnStr_Qta
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As DS_ProdottiFitosanitariMagazzinoRow
            Get
                Return CType(Me.Rows(index),DS_ProdottiFitosanitariMagazzinoRow)
            End Get
        End Property
        
        Public Event DS_ProdottiFitosanitariMagazzinoRowChanged As DS_ProdottiFitosanitariMagazzinoRowChangeEventHandler
        
        Public Event DS_ProdottiFitosanitariMagazzinoRowChanging As DS_ProdottiFitosanitariMagazzinoRowChangeEventHandler
        
        Public Event DS_ProdottiFitosanitariMagazzinoRowDeleted As DS_ProdottiFitosanitariMagazzinoRowChangeEventHandler
        
        Public Event DS_ProdottiFitosanitariMagazzinoRowDeleting As DS_ProdottiFitosanitariMagazzinoRowChangeEventHandler
        
        Public Overloads Sub AddDS_ProdottiFitosanitariMagazzinoRow(ByVal row As DS_ProdottiFitosanitariMagazzinoRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddDS_ProdottiFitosanitariMagazzinoRow( _
                    ByVal Data_Movimento As String,  _
                    ByVal Cat_Cod As Integer,  _
                    ByVal Cat_Des As String,  _
                    ByVal Pro_Cod As Integer,  _
                    ByVal Mat_Cod As Integer,  _
                    ByVal Pro_Des As String,  _
                    ByVal Cau_Mov As String,  _
                    ByVal Udm_Cod As Integer,  _
                    ByVal Udm_Sim As String,  _
                    ByVal Qta As String,  _
                    ByVal Giacenza_Finale As String,  _
                    ByVal Giacenza_Iniziale As String,  _
                    ByVal Piva As String,  _
                    ByVal Rag_Soc As String,  _
                    ByVal Sa_Cod As Integer,  _
                    ByVal Sa_Nome As String,  _
                    ByVal Fabbicato_Cod As Integer,  _
                    ByVal Fabbricato_Des As String,  _
                    ByVal Annata As String,  _
                    ByVal Elem_Cod As Integer,  _
                    ByVal CLTOSS_COD As String,  _
                    ByVal Provincia As String,  _
                    ByVal Fr_Des As String,  _
                    ByVal Mat_Des As String,  _
                    ByVal Str_Qta As String) As DS_ProdottiFitosanitariMagazzinoRow
            Dim rowDS_ProdottiFitosanitariMagazzinoRow As DS_ProdottiFitosanitariMagazzinoRow = CType(Me.NewRow,DS_ProdottiFitosanitariMagazzinoRow)
            rowDS_ProdottiFitosanitariMagazzinoRow.ItemArray = New Object() {Data_Movimento, Cat_Cod, Cat_Des, Pro_Cod, Mat_Cod, Pro_Des, Cau_Mov, Udm_Cod, Udm_Sim, Qta, Giacenza_Finale, Giacenza_Iniziale, Piva, Rag_Soc, Sa_Cod, Sa_Nome, Fabbicato_Cod, Fabbricato_Des, Annata, Elem_Cod, CLTOSS_COD, Provincia, Fr_Des, Mat_Des, Str_Qta}
            Me.Rows.Add(rowDS_ProdottiFitosanitariMagazzinoRow)
            Return rowDS_ProdottiFitosanitariMagazzinoRow
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As DS_ProdottiFitosanitariMagazzinoDataTable = CType(MyBase.Clone,DS_ProdottiFitosanitariMagazzinoDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New DS_ProdottiFitosanitariMagazzinoDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnData_Movimento = Me.Columns("Data_Movimento")
            Me.columnCat_Cod = Me.Columns("Cat_Cod")
            Me.columnCat_Des = Me.Columns("Cat_Des")
            Me.columnPro_Cod = Me.Columns("Pro_Cod")
            Me.columnMat_Cod = Me.Columns("Mat_Cod")
            Me.columnPro_Des = Me.Columns("Pro_Des")
            Me.columnCau_Mov = Me.Columns("Cau_Mov")
            Me.columnUdm_Cod = Me.Columns("Udm_Cod")
            Me.columnUdm_Sim = Me.Columns("Udm_Sim")
            Me.columnQta = Me.Columns("Qta")
            Me.columnGiacenza_Finale = Me.Columns("Giacenza_Finale")
            Me.columnGiacenza_Iniziale = Me.Columns("Giacenza_Iniziale")
            Me.columnPiva = Me.Columns("Piva")
            Me.columnRag_Soc = Me.Columns("Rag_Soc")
            Me.columnSa_Cod = Me.Columns("Sa_Cod")
            Me.columnSa_Nome = Me.Columns("Sa_Nome")
            Me.columnFabbicato_Cod = Me.Columns("Fabbicato_Cod")
            Me.columnFabbricato_Des = Me.Columns("Fabbricato_Des")
            Me.columnAnnata = Me.Columns("Annata")
            Me.columnElem_Cod = Me.Columns("Elem_Cod")
            Me.columnCLTOSS_COD = Me.Columns("CLTOSS_COD")
            Me.columnProvincia = Me.Columns("Provincia")
            Me.columnFr_Des = Me.Columns("Fr_Des")
            Me.columnMat_Des = Me.Columns("Mat_Des")
            Me.columnStr_Qta = Me.Columns("Str_Qta")
        End Sub
        
        Private Sub InitClass()
            Me.columnData_Movimento = New DataColumn("Data_Movimento", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnData_Movimento)
            Me.columnCat_Cod = New DataColumn("Cat_Cod", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCat_Cod)
            Me.columnCat_Des = New DataColumn("Cat_Des", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCat_Des)
            Me.columnPro_Cod = New DataColumn("Pro_Cod", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnPro_Cod)
            Me.columnMat_Cod = New DataColumn("Mat_Cod", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnMat_Cod)
            Me.columnPro_Des = New DataColumn("Pro_Des", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnPro_Des)
            Me.columnCau_Mov = New DataColumn("Cau_Mov", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCau_Mov)
            Me.columnUdm_Cod = New DataColumn("Udm_Cod", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnUdm_Cod)
            Me.columnUdm_Sim = New DataColumn("Udm_Sim", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnUdm_Sim)
            Me.columnQta = New DataColumn("Qta", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnQta)
            Me.columnGiacenza_Finale = New DataColumn("Giacenza_Finale", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnGiacenza_Finale)
            Me.columnGiacenza_Iniziale = New DataColumn("Giacenza_Iniziale", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnGiacenza_Iniziale)
            Me.columnPiva = New DataColumn("Piva", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnPiva)
            Me.columnRag_Soc = New DataColumn("Rag_Soc", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnRag_Soc)
            Me.columnSa_Cod = New DataColumn("Sa_Cod", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnSa_Cod)
            Me.columnSa_Nome = New DataColumn("Sa_Nome", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnSa_Nome)
            Me.columnFabbicato_Cod = New DataColumn("Fabbicato_Cod", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnFabbicato_Cod)
            Me.columnFabbricato_Des = New DataColumn("Fabbricato_Des", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnFabbricato_Des)
            Me.columnAnnata = New DataColumn("Annata", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnAnnata)
            Me.columnElem_Cod = New DataColumn("Elem_Cod", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnElem_Cod)
            Me.columnCLTOSS_COD = New DataColumn("CLTOSS_COD", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCLTOSS_COD)
            Me.columnProvincia = New DataColumn("Provincia", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnProvincia)
            Me.columnFr_Des = New DataColumn("Fr_Des", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnFr_Des)
            Me.columnMat_Des = New DataColumn("Mat_Des", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnMat_Des)
            Me.columnStr_Qta = New DataColumn("Str_Qta", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnStr_Qta)
        End Sub
        
        Public Function NewDS_ProdottiFitosanitariMagazzinoRow() As DS_ProdottiFitosanitariMagazzinoRow
            Return CType(Me.NewRow,DS_ProdottiFitosanitariMagazzinoRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New DS_ProdottiFitosanitariMagazzinoRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(DS_ProdottiFitosanitariMagazzinoRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.DS_ProdottiFitosanitariMagazzinoRowChangedEvent) Is Nothing) Then
                RaiseEvent DS_ProdottiFitosanitariMagazzinoRowChanged(Me, New DS_ProdottiFitosanitariMagazzinoRowChangeEvent(CType(e.Row,DS_ProdottiFitosanitariMagazzinoRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.DS_ProdottiFitosanitariMagazzinoRowChangingEvent) Is Nothing) Then
                RaiseEvent DS_ProdottiFitosanitariMagazzinoRowChanging(Me, New DS_ProdottiFitosanitariMagazzinoRowChangeEvent(CType(e.Row,DS_ProdottiFitosanitariMagazzinoRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.DS_ProdottiFitosanitariMagazzinoRowDeletedEvent) Is Nothing) Then
                RaiseEvent DS_ProdottiFitosanitariMagazzinoRowDeleted(Me, New DS_ProdottiFitosanitariMagazzinoRowChangeEvent(CType(e.Row,DS_ProdottiFitosanitariMagazzinoRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.DS_ProdottiFitosanitariMagazzinoRowDeletingEvent) Is Nothing) Then
                RaiseEvent DS_ProdottiFitosanitariMagazzinoRowDeleting(Me, New DS_ProdottiFitosanitariMagazzinoRowChangeEvent(CType(e.Row,DS_ProdottiFitosanitariMagazzinoRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveDS_ProdottiFitosanitariMagazzinoRow(ByVal row As DS_ProdottiFitosanitariMagazzinoRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class DS_ProdottiFitosanitariMagazzinoRow
        Inherits DataRow
        
        Private tableDS_ProdottiFitosanitariMagazzino As DS_ProdottiFitosanitariMagazzinoDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableDS_ProdottiFitosanitariMagazzino = CType(Me.Table,DS_ProdottiFitosanitariMagazzinoDataTable)
        End Sub
        
        Public Property Data_Movimento As String
            Get
                Try 
                    Return CType(Me(Me.tableDS_ProdottiFitosanitariMagazzino.Data_MovimentoColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDS_ProdottiFitosanitariMagazzino.Data_MovimentoColumn) = value
            End Set
        End Property
        
        Public Property Cat_Cod As Integer
            Get
                Try 
                    Return CType(Me(Me.tableDS_ProdottiFitosanitariMagazzino.Cat_CodColumn),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDS_ProdottiFitosanitariMagazzino.Cat_CodColumn) = value
            End Set
        End Property
        
        Public Property Cat_Des As String
            Get
                Try 
                    Return CType(Me(Me.tableDS_ProdottiFitosanitariMagazzino.Cat_DesColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDS_ProdottiFitosanitariMagazzino.Cat_DesColumn) = value
            End Set
        End Property
        
        Public Property Pro_Cod As Integer
            Get
                Try 
                    Return CType(Me(Me.tableDS_ProdottiFitosanitariMagazzino.Pro_CodColumn),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDS_ProdottiFitosanitariMagazzino.Pro_CodColumn) = value
            End Set
        End Property
        
        Public Property Mat_Cod As Integer
            Get
                Try 
                    Return CType(Me(Me.tableDS_ProdottiFitosanitariMagazzino.Mat_CodColumn),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDS_ProdottiFitosanitariMagazzino.Mat_CodColumn) = value
            End Set
        End Property
        
        Public Property Pro_Des As String
            Get
                Try 
                    Return CType(Me(Me.tableDS_ProdottiFitosanitariMagazzino.Pro_DesColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDS_ProdottiFitosanitariMagazzino.Pro_DesColumn) = value
            End Set
        End Property
        
        Public Property Cau_Mov As String
            Get
                Try 
                    Return CType(Me(Me.tableDS_ProdottiFitosanitariMagazzino.Cau_MovColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDS_ProdottiFitosanitariMagazzino.Cau_MovColumn) = value
            End Set
        End Property
        
        Public Property Udm_Cod As Integer
            Get
                Try 
                    Return CType(Me(Me.tableDS_ProdottiFitosanitariMagazzino.Udm_CodColumn),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDS_ProdottiFitosanitariMagazzino.Udm_CodColumn) = value
            End Set
        End Property
        
        Public Property Udm_Sim As String
            Get
                Try 
                    Return CType(Me(Me.tableDS_ProdottiFitosanitariMagazzino.Udm_SimColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDS_ProdottiFitosanitariMagazzino.Udm_SimColumn) = value
            End Set
        End Property
        
        Public Property Qta As String
            Get
                Try 
                    Return CType(Me(Me.tableDS_ProdottiFitosanitariMagazzino.QtaColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDS_ProdottiFitosanitariMagazzino.QtaColumn) = value
            End Set
        End Property
        
        Public Property Giacenza_Finale As String
            Get
                Try 
                    Return CType(Me(Me.tableDS_ProdottiFitosanitariMagazzino.Giacenza_FinaleColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDS_ProdottiFitosanitariMagazzino.Giacenza_FinaleColumn) = value
            End Set
        End Property
        
        Public Property Giacenza_Iniziale As String
            Get
                Try 
                    Return CType(Me(Me.tableDS_ProdottiFitosanitariMagazzino.Giacenza_InizialeColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDS_ProdottiFitosanitariMagazzino.Giacenza_InizialeColumn) = value
            End Set
        End Property
        
        Public Property Piva As String
            Get
                Try 
                    Return CType(Me(Me.tableDS_ProdottiFitosanitariMagazzino.PivaColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDS_ProdottiFitosanitariMagazzino.PivaColumn) = value
            End Set
        End Property
        
        Public Property Rag_Soc As String
            Get
                Try 
                    Return CType(Me(Me.tableDS_ProdottiFitosanitariMagazzino.Rag_SocColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDS_ProdottiFitosanitariMagazzino.Rag_SocColumn) = value
            End Set
        End Property
        
        Public Property Sa_Cod As Integer
            Get
                Try 
                    Return CType(Me(Me.tableDS_ProdottiFitosanitariMagazzino.Sa_CodColumn),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDS_ProdottiFitosanitariMagazzino.Sa_CodColumn) = value
            End Set
        End Property
        
        Public Property Sa_Nome As String
            Get
                Try 
                    Return CType(Me(Me.tableDS_ProdottiFitosanitariMagazzino.Sa_NomeColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDS_ProdottiFitosanitariMagazzino.Sa_NomeColumn) = value
            End Set
        End Property
        
        Public Property Fabbicato_Cod As Integer
            Get
                Try 
                    Return CType(Me(Me.tableDS_ProdottiFitosanitariMagazzino.Fabbicato_CodColumn),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDS_ProdottiFitosanitariMagazzino.Fabbicato_CodColumn) = value
            End Set
        End Property
        
        Public Property Fabbricato_Des As String
            Get
                Try 
                    Return CType(Me(Me.tableDS_ProdottiFitosanitariMagazzino.Fabbricato_DesColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDS_ProdottiFitosanitariMagazzino.Fabbricato_DesColumn) = value
            End Set
        End Property
        
        Public Property Annata As String
            Get
                Try 
                    Return CType(Me(Me.tableDS_ProdottiFitosanitariMagazzino.AnnataColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDS_ProdottiFitosanitariMagazzino.AnnataColumn) = value
            End Set
        End Property
        
        Public Property Elem_Cod As Integer
            Get
                Try 
                    Return CType(Me(Me.tableDS_ProdottiFitosanitariMagazzino.Elem_CodColumn),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDS_ProdottiFitosanitariMagazzino.Elem_CodColumn) = value
            End Set
        End Property
        
        Public Property CLTOSS_COD As String
            Get
                Try 
                    Return CType(Me(Me.tableDS_ProdottiFitosanitariMagazzino.CLTOSS_CODColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDS_ProdottiFitosanitariMagazzino.CLTOSS_CODColumn) = value
            End Set
        End Property
        
        Public Property Provincia As String
            Get
                Try 
                    Return CType(Me(Me.tableDS_ProdottiFitosanitariMagazzino.ProvinciaColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDS_ProdottiFitosanitariMagazzino.ProvinciaColumn) = value
            End Set
        End Property
        
        Public Property Fr_Des As String
            Get
                Try 
                    Return CType(Me(Me.tableDS_ProdottiFitosanitariMagazzino.Fr_DesColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDS_ProdottiFitosanitariMagazzino.Fr_DesColumn) = value
            End Set
        End Property
        
        Public Property Mat_Des As String
            Get
                Try 
                    Return CType(Me(Me.tableDS_ProdottiFitosanitariMagazzino.Mat_DesColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDS_ProdottiFitosanitariMagazzino.Mat_DesColumn) = value
            End Set
        End Property
        
        Public Property Str_Qta As String
            Get
                Try 
                    Return CType(Me(Me.tableDS_ProdottiFitosanitariMagazzino.Str_QtaColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDS_ProdottiFitosanitariMagazzino.Str_QtaColumn) = value
            End Set
        End Property
        
        Public Function IsData_MovimentoNull() As Boolean
            Return Me.IsNull(Me.tableDS_ProdottiFitosanitariMagazzino.Data_MovimentoColumn)
        End Function
        
        Public Sub SetData_MovimentoNull()
            Me(Me.tableDS_ProdottiFitosanitariMagazzino.Data_MovimentoColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCat_CodNull() As Boolean
            Return Me.IsNull(Me.tableDS_ProdottiFitosanitariMagazzino.Cat_CodColumn)
        End Function
        
        Public Sub SetCat_CodNull()
            Me(Me.tableDS_ProdottiFitosanitariMagazzino.Cat_CodColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCat_DesNull() As Boolean
            Return Me.IsNull(Me.tableDS_ProdottiFitosanitariMagazzino.Cat_DesColumn)
        End Function
        
        Public Sub SetCat_DesNull()
            Me(Me.tableDS_ProdottiFitosanitariMagazzino.Cat_DesColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsPro_CodNull() As Boolean
            Return Me.IsNull(Me.tableDS_ProdottiFitosanitariMagazzino.Pro_CodColumn)
        End Function
        
        Public Sub SetPro_CodNull()
            Me(Me.tableDS_ProdottiFitosanitariMagazzino.Pro_CodColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsMat_CodNull() As Boolean
            Return Me.IsNull(Me.tableDS_ProdottiFitosanitariMagazzino.Mat_CodColumn)
        End Function
        
        Public Sub SetMat_CodNull()
            Me(Me.tableDS_ProdottiFitosanitariMagazzino.Mat_CodColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsPro_DesNull() As Boolean
            Return Me.IsNull(Me.tableDS_ProdottiFitosanitariMagazzino.Pro_DesColumn)
        End Function
        
        Public Sub SetPro_DesNull()
            Me(Me.tableDS_ProdottiFitosanitariMagazzino.Pro_DesColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCau_MovNull() As Boolean
            Return Me.IsNull(Me.tableDS_ProdottiFitosanitariMagazzino.Cau_MovColumn)
        End Function
        
        Public Sub SetCau_MovNull()
            Me(Me.tableDS_ProdottiFitosanitariMagazzino.Cau_MovColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsUdm_CodNull() As Boolean
            Return Me.IsNull(Me.tableDS_ProdottiFitosanitariMagazzino.Udm_CodColumn)
        End Function
        
        Public Sub SetUdm_CodNull()
            Me(Me.tableDS_ProdottiFitosanitariMagazzino.Udm_CodColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsUdm_SimNull() As Boolean
            Return Me.IsNull(Me.tableDS_ProdottiFitosanitariMagazzino.Udm_SimColumn)
        End Function
        
        Public Sub SetUdm_SimNull()
            Me(Me.tableDS_ProdottiFitosanitariMagazzino.Udm_SimColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsQtaNull() As Boolean
            Return Me.IsNull(Me.tableDS_ProdottiFitosanitariMagazzino.QtaColumn)
        End Function
        
        Public Sub SetQtaNull()
            Me(Me.tableDS_ProdottiFitosanitariMagazzino.QtaColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsGiacenza_FinaleNull() As Boolean
            Return Me.IsNull(Me.tableDS_ProdottiFitosanitariMagazzino.Giacenza_FinaleColumn)
        End Function
        
        Public Sub SetGiacenza_FinaleNull()
            Me(Me.tableDS_ProdottiFitosanitariMagazzino.Giacenza_FinaleColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsGiacenza_InizialeNull() As Boolean
            Return Me.IsNull(Me.tableDS_ProdottiFitosanitariMagazzino.Giacenza_InizialeColumn)
        End Function
        
        Public Sub SetGiacenza_InizialeNull()
            Me(Me.tableDS_ProdottiFitosanitariMagazzino.Giacenza_InizialeColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsPivaNull() As Boolean
            Return Me.IsNull(Me.tableDS_ProdottiFitosanitariMagazzino.PivaColumn)
        End Function
        
        Public Sub SetPivaNull()
            Me(Me.tableDS_ProdottiFitosanitariMagazzino.PivaColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsRag_SocNull() As Boolean
            Return Me.IsNull(Me.tableDS_ProdottiFitosanitariMagazzino.Rag_SocColumn)
        End Function
        
        Public Sub SetRag_SocNull()
            Me(Me.tableDS_ProdottiFitosanitariMagazzino.Rag_SocColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsSa_CodNull() As Boolean
            Return Me.IsNull(Me.tableDS_ProdottiFitosanitariMagazzino.Sa_CodColumn)
        End Function
        
        Public Sub SetSa_CodNull()
            Me(Me.tableDS_ProdottiFitosanitariMagazzino.Sa_CodColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsSa_NomeNull() As Boolean
            Return Me.IsNull(Me.tableDS_ProdottiFitosanitariMagazzino.Sa_NomeColumn)
        End Function
        
        Public Sub SetSa_NomeNull()
            Me(Me.tableDS_ProdottiFitosanitariMagazzino.Sa_NomeColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsFabbicato_CodNull() As Boolean
            Return Me.IsNull(Me.tableDS_ProdottiFitosanitariMagazzino.Fabbicato_CodColumn)
        End Function
        
        Public Sub SetFabbicato_CodNull()
            Me(Me.tableDS_ProdottiFitosanitariMagazzino.Fabbicato_CodColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsFabbricato_DesNull() As Boolean
            Return Me.IsNull(Me.tableDS_ProdottiFitosanitariMagazzino.Fabbricato_DesColumn)
        End Function
        
        Public Sub SetFabbricato_DesNull()
            Me(Me.tableDS_ProdottiFitosanitariMagazzino.Fabbricato_DesColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsAnnataNull() As Boolean
            Return Me.IsNull(Me.tableDS_ProdottiFitosanitariMagazzino.AnnataColumn)
        End Function
        
        Public Sub SetAnnataNull()
            Me(Me.tableDS_ProdottiFitosanitariMagazzino.AnnataColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsElem_CodNull() As Boolean
            Return Me.IsNull(Me.tableDS_ProdottiFitosanitariMagazzino.Elem_CodColumn)
        End Function
        
        Public Sub SetElem_CodNull()
            Me(Me.tableDS_ProdottiFitosanitariMagazzino.Elem_CodColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCLTOSS_CODNull() As Boolean
            Return Me.IsNull(Me.tableDS_ProdottiFitosanitariMagazzino.CLTOSS_CODColumn)
        End Function
        
        Public Sub SetCLTOSS_CODNull()
            Me(Me.tableDS_ProdottiFitosanitariMagazzino.CLTOSS_CODColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsProvinciaNull() As Boolean
            Return Me.IsNull(Me.tableDS_ProdottiFitosanitariMagazzino.ProvinciaColumn)
        End Function
        
        Public Sub SetProvinciaNull()
            Me(Me.tableDS_ProdottiFitosanitariMagazzino.ProvinciaColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsFr_DesNull() As Boolean
            Return Me.IsNull(Me.tableDS_ProdottiFitosanitariMagazzino.Fr_DesColumn)
        End Function
        
        Public Sub SetFr_DesNull()
            Me(Me.tableDS_ProdottiFitosanitariMagazzino.Fr_DesColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsMat_DesNull() As Boolean
            Return Me.IsNull(Me.tableDS_ProdottiFitosanitariMagazzino.Mat_DesColumn)
        End Function
        
        Public Sub SetMat_DesNull()
            Me(Me.tableDS_ProdottiFitosanitariMagazzino.Mat_DesColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsStr_QtaNull() As Boolean
            Return Me.IsNull(Me.tableDS_ProdottiFitosanitariMagazzino.Str_QtaColumn)
        End Function
        
        Public Sub SetStr_QtaNull()
            Me(Me.tableDS_ProdottiFitosanitariMagazzino.Str_QtaColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class DS_ProdottiFitosanitariMagazzinoRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As DS_ProdottiFitosanitariMagazzinoRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As DS_ProdottiFitosanitariMagazzinoRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As DS_ProdottiFitosanitariMagazzinoRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
