<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://ws_CapitolatoCliente_ElencoTabellaRMA">
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="tabella_rma">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="tabellaRma_cod" type="xs:unsignedByte" />
              <xs:element name="tabellaRma_Des" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>