'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class ACC_Configurazione

    'Simple Properties
    <DataMember()>
    Public Property Piva_SuperUser As String
    <DataMember()>
    Public Property Piva As String
    <DataMember()>
    Public Property Id_Conf As Integer
    <DataMember()>
    Public Property Sa_Cod As Nullable(Of Integer)
    <DataMember()>
    Public Property Cod_Indirizzo As Nullable(Of Integer)
    <DataMember()>
    Public Property RepositoryAllegati As String
    <DataMember()>
    Public Property BackGroundIntestazione As String
    <DataMember()>
    Public Property BackColorIntestazione As String
    <DataMember()>
    Public Property Logo As String
    <DataMember()>
    Public Property FontColorTitolo As String
    <DataMember()>
    Public Property BorderColorIntestazione As String
    <DataMember()>
    Public Property BackGroundHome As String
    <DataMember()>
    Public Property BackColorHome As String
    <DataMember()>
    Public Property BorderColorHome As String
    <DataMember()>
    Public Property FontPagina As String
    <DataMember()>
    Public Property FontColorPagina As String
    <DataMember()>
    Public Property ImmagineHome As String
    <DataMember()>
    Public Property TestoPresentazione As String
    <DataMember()>
    Public Property Flag_Pagina_Azienda As Nullable(Of Short)
    <DataMember()>
    Public Property ImmagineAzienda As String
    <DataMember()>
    Public Property TestoAzienda As String
    <DataMember()>
    Public Property Flag_Pagina_Contatti As Nullable(Of Short)
    <DataMember()>
    Public Property Flag_Piva As Nullable(Of Short)
    <DataMember()>
    Public Property Flag_CodFiscale As Nullable(Of Short)
    <DataMember()>
    Public Property Flag_Indirizzo As Nullable(Of Short)
    <DataMember()>
    Public Property Flag_Localita As Nullable(Of Short)
    <DataMember()>
    Public Property Flag_Tel As Nullable(Of Short)
    <DataMember()>
    Public Property Flag_Fax As Nullable(Of Short)
    <DataMember()>
    Public Property Flag_EMail As Nullable(Of Short)
    <DataMember()>
    Public Property Flag_Responsabile As Nullable(Of Short)
    <DataMember()>
    Public Property Flag_Cell As Nullable(Of Short)
    <DataMember()>
    Public Property Telefono As String
    <DataMember()>
    Public Property Fax As String
    <DataMember()>
    Public Property Email As String
    <DataMember()>
    Public Property Responsabile As String
    <DataMember()>
    Public Property Cellulare As String
    <DataMember()>
    Public Property Flag_Pagina_Prodotti As Nullable(Of Short)
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property datainvio As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Validita_Fine As Nullable(Of Date)
    <DataMember()>
    Public Property Validazione As Nullable(Of Short)
    <DataMember()>
    Public Property Data_Validazione As Nullable(Of Date)
    <DataMember()>
    Public Property UserName_Validazione As String

End Class
