'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class ACCDAA_ANAG_TabellaErrori

    'Simple Properties
    <DataMember()>
    Public Property TipoErrore As String
    <DataMember()>
    Public Property Numero As String
    <DataMember()>
    Public Property Descrizione As String

End Class
