'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class ACCDAA_DAA_Testata

    'Simple Properties
    <DataMember()>
    Public Property DAA_id As Integer
    <DataMember()>
    Public Property Descrizione As String
    <DataMember()>
    Public Property ARC As String
    <DataMember()>
    Public Property ARC_Progressivo As Nullable(Of Integer)
    <DataMember()>
    Public Property Stato_Manager As Nullable(Of Integer)
    <DataMember()>
    Public Property Invio_Differito As Nullable(Of Boolean)
    <DataMember()>
    Public Property Data_creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property Data_riferimento As Nullable(Of Date)
    <DataMember()>
    Public Property Tipo_Messaggio As Nullable(Of Integer)

End Class
