'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class APP_Documenti

    'Simple Properties
    <DataMember()>
    Public Property ID As String
    <DataMember()>
    Public Property Piva_Superuser As String
    <DataMember()>
    Public Property Piva As String
    <DataMember()>
    Public Property Documento_Cod As Integer
    <DataMember()>
    Public Property ID_Tipologia As Integer
    <DataMember()>
    Public Property Descrizione As String
    <DataMember()>
    Public Property Data_Scadenza As Nullable(Of Date)
    <DataMember()>
    Public Property NomeFile As String
    <DataMember()>
    Public Property FileAllegato As Byte()
    <DataMember()>
    Public Property Note As String
    <DataMember()>
    Public Property Visita_Cod As Nullable(Of Integer)
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property datainvio As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Validita_Fine As Nullable(Of Date)
    <DataMember()>
    Public Property Importato_Data As Nullable(Of Date)
    <DataMember()>
    Public Property Importato_Errore As String
    <DataMember()>
    Public Property APP_Ricette_Destinazioni_ID As String
    <DataMember()>
    Public Property APP_Ricette_Operazioni_ID As String
    <DataMember()>
    Public Property Numero_Documento As String
    <DataMember()>
    Public Property Data_Documento As Nullable(Of Date)

End Class
