'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class BIO_Notifica_Frontespizio

    'Simple Properties
    <DataMember()>
    Public Property Notifica_SuperUser As String
    <DataMember()>
    Public Property Notifica_ID As Integer
    <DataMember()>
    Public Property Notifica_Piva As String
    <DataMember()>
    Public Property Notifica_SaCod As Nullable(Of Integer)
    <DataMember()>
    Public Property Notifica_Ricevimento_Protocollo As String
    <DataMember()>
    Public Property Notifica_Ricevimento_Data As Nullable(Of Date)
    <DataMember()>
    Public Property Notifica_Fotografia_Data As Nullable(Of Date)
    <DataMember()>
    Public Property Cod_Istat_Regione As String
    <DataMember()>
    Public Property Flag_Regione As Nullable(Of Short)
    <DataMember()>
    Public Property Flag_Ministero_MiPAF As Nullable(Of Short)
    <DataMember()>
    Public Property Flag_Categoria_Produttore As Short
    <DataMember()>
    Public Property Flag_Categoria_Preparatore As Nullable(Of Short)
    <DataMember()>
    Public Property Flag_Categoria_Importatore As Nullable(Of Short)
    <DataMember()>
    Public Property Flag_PrimaNotifica1_Variazione2 As Nullable(Of Short)
    <DataMember()>
    Public Property Flag_Cause_ModificaDichiarante As Nullable(Of Short)
    <DataMember()>
    Public Property Flag_Cause_ModificaUnitaProduttive As Nullable(Of Short)
    <DataMember()>
    Public Property Flag_Cause_ModificaCategorie As Nullable(Of Short)
    <DataMember()>
    Public Property Flag_Cause_CambioOrganismo As Nullable(Of Short)
    <DataMember()>
    Public Property Flag_Cause_CambioOrganismo_Des As String
    <DataMember()>
    Public Property Flag_Cause_Altro As Nullable(Of Short)
    <DataMember()>
    Public Property Flag_Cause_Altro_Des As String
    <DataMember()>
    Public Property Dichiarante_CodiceFiscale As String
    <DataMember()>
    Public Property Dichiarante_Piva As String
    <DataMember()>
    Public Property Dichiarante_Flag_AziendaIndividuale As Nullable(Of Short)
    <DataMember()>
    Public Property Dichiarante_Flag_Societa As Nullable(Of Short)
    <DataMember()>
    Public Property Dichiarante_Flag_Cooperativa As Nullable(Of Short)
    <DataMember()>
    Public Property Dichiarante_Cognome_RagSoc As String
    <DataMember()>
    Public Property Dichiarante_Nome As String
    <DataMember()>
    Public Property Dichiarante_Nascita_Provincia_Sigla As String
    <DataMember()>
    Public Property Dichiarante_Nascita_Provincia_ISTAT As String
    <DataMember()>
    Public Property Dichiarante_Nascita_Comune As String
    <DataMember()>
    Public Property Dichiarante_Nascita_Comune_ISTAT As String
    <DataMember()>
    Public Property Dichiarante_Nascita_Data As Nullable(Of Date)
    <DataMember()>
    Public Property Dichiarante_Flag_Maschio1_Femmina2_Giuridica3 As Nullable(Of Short)
    <DataMember()>
    Public Property Dichiarante_Domicilio_Provincia_Sigla As String
    <DataMember()>
    Public Property Dichiarante_Domicilio_Provincia_ISTAT As String
    <DataMember()>
    Public Property Dichiarante_Domicilio_Comune As String
    <DataMember()>
    Public Property Dichiarante_Domicilio_Comune_ISTAT As String
    <DataMember()>
    Public Property Dichiarante_Domicilio_Via As String
    <DataMember()>
    Public Property Dichiarante_Domicilio_Numero As String
    <DataMember()>
    Public Property Dichiarante_Domicilio_CAP As String
    <DataMember()>
    Public Property Dichiarante_Domicilio_Telefono As String
    <DataMember()>
    Public Property Dichiarante_Domicilio_Fax As String
    <DataMember()>
    Public Property Dichiarante_Domicilio_Email As String
    <DataMember()>
    Public Property RappLegale_Cognome As String
    <DataMember()>
    Public Property RappLegale_Nome As String
    <DataMember()>
    Public Property RappLegale_CodiceFiscale As String
    <DataMember()>
    Public Property RappLegale_Nascita_Provincia_Sigla As String
    <DataMember()>
    Public Property RappLegale_Nascita_Provincia_ISTAT As String
    <DataMember()>
    Public Property RappLegale_Nascita_Comune As String
    <DataMember()>
    Public Property RappLegale_Nascita_Comune_ISTAT As String
    <DataMember()>
    Public Property RappLegale_Nascita_Data As Nullable(Of Date)
    <DataMember()>
    Public Property RappLegale_Flag_Maschio1_Femmina2 As Nullable(Of Short)
    <DataMember()>
    Public Property RappLegale_Domicilio_Provincia_Sigla As String
    <DataMember()>
    Public Property RappLegale_Domicilio_Provincia_ISTAT As String
    <DataMember()>
    Public Property RappLegale_Domicilio_Comune As String
    <DataMember()>
    Public Property RappLegale_Domicilio_Comune_ISTAT As String
    <DataMember()>
    Public Property RappLegale_Domicilio_Via As String
    <DataMember()>
    Public Property RappLegale_Domicilio_Numero As String
    <DataMember()>
    Public Property RappLegale_Domicilio_CAP As String
    <DataMember()>
    Public Property OrganismoControllo_1_Codice As String
    <DataMember()>
    Public Property OrganismoControllo_1_CodiceOperatore As String
    <DataMember()>
    Public Property Organismo1_Flag_Produttore As Nullable(Of Short)
    <DataMember()>
    Public Property Organismo1_Flag_Preparatore As Nullable(Of Short)
    <DataMember()>
    Public Property Organismo1_Flag_Importatore As Nullable(Of Short)
    <DataMember()>
    Public Property OrganismoControllo_2_Codice As String
    <DataMember()>
    Public Property OrganismoControllo_2_CodiceOperatore As String
    <DataMember()>
    Public Property Organismo2_Flag_Produttore As Nullable(Of Short)
    <DataMember()>
    Public Property Organismo2_Flag_Preparatore As Nullable(Of Short)
    <DataMember()>
    Public Property Organismo2_Flag_Importatore As Nullable(Of Short)
    <DataMember()>
    Public Property Flag_Notifica_Bloccata As Nullable(Of Short)
    <DataMember()>
    Public Property Inviato As Nullable(Of Short)
    <DataMember()>
    Public Property DataInvio As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Validita_Fine As Nullable(Of Date)
    <DataMember()>
    Public Property DataLock As Nullable(Of Integer)
    <DataMember()>
    Public Property Programmazione_Cod As Nullable(Of Integer)

End Class
