'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class CAC_Codifica_Audit_Domande_Interviste

    'Simple Properties
    <DataMember()>
    Public Property Codice_Cliente As String
    <DataMember()>
    Public Property Raccoglitore_Cod As Integer
    <DataMember()>
    Public Property Audit_Tipo As Integer
    <DataMember()>
    Public Property Domanda_Cod As Integer
    <DataMember()>
    Public Property Descrizione As String
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property datainvio As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Validita_Fine As Nullable(Of Date)

End Class
