'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class CAC_Codifica_Zone

    'Simple Properties
    <DataMember()>
    Public Property Piva_SuperUser As String
    <DataMember()>
    Public Property Zona_Cod_Cliente As String
    <DataMember()>
    Public Property Zona_Cod_Gias As Integer
    <DataMember()>
    Public Property Descrizione As String
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)

End Class
