'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
<KnownType(GetType(CampionamentoConferito_TestataGriglia_Calibri))>
<KnownType(GetType(CampionamentoConferito_TestataGriglia_Prodotti))>
<KnownType(GetType(Listini_CampionamentoConferito_X_Testata_Griglia))>
Partial Public Class CampionamentoConferito_TestataGriglia

    'Simple Properties
    <DataMember()>
    Public Property Piva_SuperUser As String
    <DataMember()>
    Public Property PIVA As String
    <DataMember()>
    Public Property Id_TestataGriglia As Integer
    <DataMember()>
    Public Property des_TestataGriglia As String
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property datainvio As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Validita_Fine As Nullable(Of Date)

    'Navigation Properties
    <DataMember()>
    Public Overridable Property CampionamentoConferito_TestataGriglia_Calibri As ICollection(Of CampionamentoConferito_TestataGriglia_Calibri) = New HashSet(Of CampionamentoConferito_TestataGriglia_Calibri)
    <DataMember()>
    Public Overridable Property CampionamentoConferito_TestataGriglia_Prodotti As ICollection(Of CampionamentoConferito_TestataGriglia_Prodotti) = New HashSet(Of CampionamentoConferito_TestataGriglia_Prodotti)
    <DataMember()>
    Public Overridable Property Listini_CampionamentoConferito_X_Testata_Griglia As ICollection(Of Listini_CampionamentoConferito_X_Testata_Griglia) = New HashSet(Of Listini_CampionamentoConferito_X_Testata_Griglia)

End Class
