'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
<KnownType(GetType(Cespiti))>
Partial Public Class Cespiti_Movimenti

    'Simple Properties
    <DataMember()>
    Public Property id_cod_cespite As Integer
    <DataMember()>
    Public Property dat_mov As Date
    <DataMember()>
    Public Property cau_mov As Integer
    <DataMember()>
    Public Property esercizio As Integer
    <DataMember()>
    Public Property qta_N_mov As Integer
    <DataMember()>
    Public Property val_qtaN_costo_acq As Decimal
    <DataMember()>
    Public Property val_qta1_costo_acq As Decimal
    <DataMember()>
    Public Property val_qta1_mov As Decimal
    <DataMember()>
    Public Property val_qtaN_mov As Decimal
    <DataMember()>
    Public Property val_qta1_amm As Decimal
    <DataMember()>
    Public Property val_qtaN_amm As Decimal
    <DataMember()>
    Public Property prc_amm As Decimal
    <DataMember()>
    Public Property val_qta1_fondo_amm As Decimal
    <DataMember()>
    Public Property val_qtaN_fondo_amm As Decimal
    <DataMember()>
    Public Property val_qta1_residuo_amm As Decimal
    <DataMember()>
    Public Property val_qtaN_residuo_amm As Decimal
    <DataMember()>
    Public Property val_qta1_minus As Decimal
    <DataMember()>
    Public Property val_qtaN_minus As Decimal
    <DataMember()>
    Public Property val_qta1_plus As Decimal
    <DataMember()>
    Public Property val_qtaN_plus As Decimal
    <DataMember()>
    Public Property fis_val_qta1_ammortizzabile As Decimal
    <DataMember()>
    Public Property fis_val_qtaN_ammortizzabile As Decimal
    <DataMember()>
    Public Property fis_val_qta1_mov As Decimal
    <DataMember()>
    Public Property fis_val_qtaN_mov As Decimal
    <DataMember()>
    Public Property fis_val_qta1_amm As Decimal
    <DataMember()>
    Public Property fis_val_qtaN_amm As Decimal
    <DataMember()>
    Public Property fis_prc_amm As Decimal
    <DataMember()>
    Public Property fis_val_qta1_fondo_amm As Decimal
    <DataMember()>
    Public Property fis_val_qtaN_fondo_amm As Decimal
    <DataMember()>
    Public Property fis_val_qta1_residuo_amm As Decimal
    <DataMember()>
    Public Property fis_val_qtaN_residuo_amm As Decimal
    <DataMember()>
    Public Property fis_val_qta1_minus As Decimal
    <DataMember()>
    Public Property fis_val_qtaN_minus As Decimal
    <DataMember()>
    Public Property fis_val_qta1_plus As Decimal
    <DataMember()>
    Public Property fis_val_qtaN_plus As Decimal
    <DataMember()>
    Public Property Inviato As Nullable(Of Short)
    <DataMember()>
    Public Property DataInvio As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property UserName_Creazione As String
    <DataMember()>
    Public Property UserName_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Date
    <DataMember()>
    Public Property Validita_Fine As Date

    'Navigation Properties
    <DataMember()>
    Public Overridable Property Cespiti As Cespiti
    <DataMember()>
    Public Overridable Property Cespiti1 As Cespiti
    <DataMember()>
    Public Overridable Property Cespiti2 As Cespiti
    <DataMember()>
    Public Overridable Property Cespiti3 As Cespiti
    <DataMember()>
    Public Overridable Property Cespiti4 As Cespiti
    <DataMember()>
    Public Overridable Property Cespiti5 As Cespiti

End Class
