'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class Configurazione_Imballaggi

    'Simple Properties
    <DataMember()>
    Public Property Piva_SuperUser As String
    <DataMember()>
    Public Property Piva As String
    <DataMember()>
    Public Property Id_Config As Integer
    <DataMember()>
    Public Property Tabella_Cod As Short
    <DataMember()>
    Public Property Tipo_Config As Short
    <DataMember()>
    Public Property Mat_Cod As Integer
    <DataMember()>
    Public Property Modulo_Generazione As Short
    <DataMember()>
    Public Property Tabella_Par_Cod As Integer
    <DataMember()>
    Public Property Veg_Cod As Integer
    <DataMember()>
    Public Property Cul_Cod As Integer
    <DataMember()>
    Public Property Valore As String
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property datainvio As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Validita_Fine As Nullable(Of Date)

End Class
