'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class DW_CDG_Costi_Ricavi

    'Simple Properties
    <DataMember()>
    Public Property Id_DW As Integer
    <DataMember()>
    Public Property Piva_Superuser As String
    <DataMember()>
    Public Property Piva As String
    <DataMember()>
    Public Property Id_CDG As Integer
    <DataMember()>
    Public Property Id_CDG_Dettagli As Integer
    <DataMember()>
    Public Property Criterio_Analisi As Integer
    <DataMember()>
    Public Property Data_Inserimento As Nullable(Of Date)
    <DataMember()>
    Public Property Descr_Modalita_Imputazione As String
    <DataMember()>
    Public Property Id_Agenda As Integer
    <DataMember()>
    Public Property Id_Mov As Integer
    <DataMember()>
    Public Property Id_Mov_Det As Integer
    <DataMember()>
    Public Property Mac_Cod As Integer
    <DataMember()>
    Public Property Cod_RisUm As Integer
    <DataMember()>
    Public Property Elem_Cod As Integer
    <DataMember()>
    Public Property Pro_Cod As Integer
    <DataMember()>
    Public Property Mat_Cod As Integer
    <DataMember()>
    Public Property Id_Attivita As Integer
    <DataMember()>
    Public Property Qualifica_Cod As Integer
    <DataMember()>
    Public Property Tariffa_Cod As Integer
    <DataMember()>
    Public Property Turno_Cod As Integer
    <DataMember()>
    Public Property Conto_Cod As Integer
    <DataMember()>
    Public Property Lotto As String
    <DataMember()>
    Public Property Mezzo As Integer
    <DataMember()>
    Public Property Mezzo_Des As String
    <DataMember()>
    Public Property Prezzo_Unitario As Decimal
    <DataMember()>
    Public Property Qta As Decimal
    <DataMember()>
    Public Property Valore As Decimal
    <DataMember()>
    Public Property Descrizione As String
    <DataMember()>
    Public Property Budget_Cons As Short
    <DataMember()>
    Public Property Budget_Cons_Des As String
    <DataMember()>
    Public Property Costi_Ricavi As Short
    <DataMember()>
    Public Property Costi_Ricavi_Des As String
    <DataMember()>
    Public Property Sa_Cod As Integer
    <DataMember()>
    Public Property Appezza As Integer
    <DataMember()>
    Public Property Id_Reg As Integer
    <DataMember()>
    Public Property Id_Cod_reg_impianti_codici As Integer
    <DataMember()>
    Public Property Id_Imputazione As Integer
    <DataMember()>
    Public Property Macchine_Cod As Integer
    <DataMember()>
    Public Property Linea_Cod As Integer
    <DataMember()>
    Public Property Veg_Cod As Integer
    <DataMember()>
    Public Property Cul_Cod As Integer
    <DataMember()>
    Public Property Descrizione_Operazione As String
    <DataMember()>
    Public Property Descrizione_Macchina As String
    <DataMember()>
    Public Property Nome_Cognome As String
    <DataMember()>
    Public Property Categoria As String
    <DataMember()>
    Public Property Descrizione_Prodotto As String
    <DataMember()>
    Public Property Attivita As String
    <DataMember()>
    Public Property Qualifica As String
    <DataMember()>
    Public Property Tariffa As String
    <DataMember()>
    Public Property Turno As String
    <DataMember()>
    Public Property Conto As String
    <DataMember()>
    Public Property Ragione_Sociale_Azienda As String
    <DataMember()>
    Public Property Indirizzo_Azienda As String
    <DataMember()>
    Public Property Cap_Azienda As String
    <DataMember()>
    Public Property Localita_Azienda As String
    <DataMember()>
    Public Property Prov_Azienda As String
    <DataMember()>
    Public Property Descrizione_Centro As String
    <DataMember()>
    Public Property Indirizzo_Centro As String
    <DataMember()>
    Public Property Cap_Centro As String
    <DataMember()>
    Public Property Localita_Centro As String
    <DataMember()>
    Public Property Prov_Centro As String
    <DataMember()>
    Public Property Descrizione_Campo As String
    <DataMember()>
    Public Property Nome_Appezzamento As String
    <DataMember()>
    Public Property Inizio_Appezzamento As Nullable(Of Date)
    <DataMember()>
    Public Property Fine_Appezzamento As Nullable(Of Date)
    <DataMember()>
    Public Property Descrizione_Gruppo_Vegetale As String
    <DataMember()>
    Public Property Specie_impianto As String
    <DataMember()>
    Public Property Varieta_impianto As String
    <DataMember()>
    Public Property Descrizione_Finalita As String
    <DataMember()>
    Public Property Destinazione_Uso As String
    <DataMember()>
    Public Property Inizio_Impianto As Nullable(Of Date)
    <DataMember()>
    Public Property Fine_Impianto As Nullable(Of Date)
    <DataMember()>
    Public Property Regolamento As String
    <DataMember()>
    Public Property Disciplinare As String
    <DataMember()>
    Public Property Esposizione_Appezzamento As String
    <DataMember()>
    Public Property Ubicazione_Appezzamento As String
    <DataMember()>
    Public Property Descrizione_Portinnesti As String
    <DataMember()>
    Public Property Descrizione_Irrigazioni As String
    <DataMember()>
    Public Property Regione_Impianto As String
    <DataMember()>
    Public Property Prov_Impianto As String
    <DataMember()>
    Public Property Comune_Impianto As String
    <DataMember()>
    Public Property Sezione As String
    <DataMember()>
    Public Property Foglio As Integer
    <DataMember()>
    Public Property Numero As Integer
    <DataMember()>
    Public Property Subalterno As String
    <DataMember()>
    Public Property Descrizione_Macchina_Input_Costi As String
    <DataMember()>
    Public Property Progetto As String
    <DataMember()>
    Public Property Classe_Progetto As String
    <DataMember()>
    Public Property Tipo_Progetto As String
    <DataMember()>
    Public Property Linea_Produzione As String
    <DataMember()>
    Public Property Campo_Cod As Integer
    <DataMember()>
    Public Property Lotto_Input_Costi As String
    <DataMember()>
    Public Property Progetto_Cod As Integer
    <DataMember()>
    Public Property Progetto_Nome As String
    <DataMember()>
    Public Property Progetto_Validita_Inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Progetto_Validita_Fine As Nullable(Of Date)
    <DataMember()>
    Public Property Note As String
    <DataMember()>
    Public Property Vecchio_Tipo_Inser_Dati As Short
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property datainvio As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Validita_Fine As Nullable(Of Date)
    <DataMember()>
    Public Property Tipo_Imputazione As Short
    <DataMember()>
    Public Property Id_Cfg_DW As Integer
    <DataMember()>
    Public Property Udm_Cod As Integer
    <DataMember()>
    Public Property Percentuale_Ripart As Decimal
    <DataMember()>
    Public Property Codice_Impianto As String
    <DataMember()>
    Public Property Cod_Animale As Integer
    <DataMember()>
    Public Property Animale_Progetto As String
    <DataMember()>
    Public Property Cod_Animale_Distinta As Integer
    <DataMember()>
    Public Property Animale_Distinta As String
    <DataMember()>
    Public Property Sta_Num As Integer
    <DataMember()>
    Public Property Stalla_Des As String
    <DataMember()>
    Public Property Raggruppamento_Cod As Integer
    <DataMember()>
    Public Property Raggruppamento_Des As String
    <DataMember()>
    Public Property Specie_Animale_Cod As Integer
    <DataMember()>
    Public Property Specie_Animale_Des As String
    <DataMember()>
    Public Property Razza_Animale_Cod As Integer
    <DataMember()>
    Public Property Razza_Animale_Des As String
    <DataMember()>
    Public Property Tipo_Animale_Cod As Integer
    <DataMember()>
    Public Property Tipo_Animale_Des As String
    <DataMember()>
    Public Property Modalita_Imputazione As Short
    <DataMember()>
    Public Property Cod_Articolo As String
    <DataMember()>
    Public Property MetodoProduzioneAppezzamento As String
    <DataMember()>
    Public Property Sup_app As Double
    <DataMember()>
    Public Property Sup_imp As Double
    <DataMember()>
    Public Property Sup_Prog As Double
    <DataMember()>
    Public Property Data_Chiusura_Esercizio As String
    <DataMember()>
    Public Property Progetto_Des As String
    <DataMember()>
    Public Property Codice_Appezzamento As String
    <DataMember()>
    Public Property App_BIO As String
    <DataMember()>
    Public Property NrBadge As String
    <DataMember()>
    Public Property Data_Split As Nullable(Of Date)
    <DataMember()>
    Public Property ID_Attivita_Gruppo1 As Nullable(Of Integer)
    <DataMember()>
    Public Property Des_Attivita_Gruppo1 As String
    <DataMember()>
    Public Property ID_Attivita_Gruppo2 As Nullable(Of Integer)
    <DataMember()>
    Public Property Des_Attivita_Gruppo2 As String
    <DataMember()>
    Public Property ID_Attivita_Gruppo3 As Nullable(Of Integer)
    <DataMember()>
    Public Property Des_Attivita_Gruppo3 As String
    <DataMember()>
    Public Property Ordine_Attivita As Nullable(Of Integer)
    <DataMember()>
    Public Property Piva_Padre As String
    <DataMember()>
    Public Property Azienda_Padre As String
    <DataMember()>
    Public Property Id_Agenda_Qdc As Integer
    <DataMember()>
    Public Property Fabbricato_Des As String
    <DataMember()>
    Public Property Proprietario_Macchina As String
    <DataMember()>
    Public Property PesoPagato As Nullable(Of Double)
    <DataMember()>
    Public Property PesoArrivo As Nullable(Of Double)
    <DataMember()>
    Public Property PesoUscito As Nullable(Of Double)

End Class
