'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
<KnownType(GetType(FF_ConfigurazioniDiStampa_Dettagli))>
<KnownType(GetType(FF_TipologiaEtichette))>
Partial Public Class FF_LayoutEtichette

    'Simple Properties
    <DataMember()>
    Public Property FF_LayoutEtichette_cod As Integer
    <DataMember()>
    Public Property FF_LayoutEtichette_des As String
    <DataMember()>
    Public Property FileRpt As String
    <DataMember()>
    Public Property Larghezza_etichetta As Nullable(Of Integer)
    <DataMember()>
    Public Property Altezza_etichetta As Nullable(Of Integer)
    <DataMember()>
    Public Property Tipo_etichetta As String
    <DataMember()>
    Public Property [Default] As Nullable(Of Integer)
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property datainvio As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Validita_Fine As Nullable(Of Date)
    <DataMember()>
    Public Property FF_TipologiaEtichette_Cod As Nullable(Of Integer)
    <DataMember()>
    Public Property StartCodeChar As String
    <DataMember()>
    Public Property EndCodeChar As String
    <DataMember()>
    Public Property StartAiChar As String
    <DataMember()>
    Public Property CodeSet128 As String
    <DataMember()>
    Public Property BarcodeFont As String
    <DataMember()>
    Public Property BarcodeType As String
    <DataMember()>
    Public Property piva_SuperUser As String

    'Navigation Properties
    <DataMember()>
    Public Overridable Property FF_ConfigurazioniDiStampa_Dettagli As ICollection(Of FF_ConfigurazioniDiStampa_Dettagli) = New HashSet(Of FF_ConfigurazioniDiStampa_Dettagli)
    <DataMember()>
    Public Overridable Property FF_TipologiaEtichette As FF_TipologiaEtichette

End Class
