'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
<KnownType(GetType(GIS_LayerElementiGrafici_Anagrafica_DataStruct))>
Partial Public Class GIS_LayerElementiGrafici_Anagrafica

    'Simple Properties
    <DataMember()>
    Public Property PivaSuperUser As String
    <DataMember()>
    Public Property LayerElementiGrafici_Cod As Integer
    <DataMember()>
    Public Property TipologiaLayer_cod As Integer
    <DataMember()>
    Public Property LayerElementiGrafici_Des As String
    <DataMember()>
    Public Property Flag_Inserimento As Nullable(Of Integer)
    <DataMember()>
    Public Property Flag_Modifica As Nullable(Of Integer)
    <DataMember()>
    Public Property Flag_Cancellazione As Nullable(Of Integer)
    <DataMember()>
    Public Property Flag_Informazioni As Nullable(Of Integer)
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property datainvio As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Validita_Fine As Nullable(Of Date)
    <DataMember()>
    Public Property Flag_SingolaDataSignificativa As Nullable(Of Integer)
    <DataMember()>
    Public Property LayerElementiGrafici_GUID As String
    <DataMember()>
    Public Property PaletteVisualizzazione As String

    'Navigation Properties
    <DataMember()>
    Public Overridable Property GIS_LayerElementiGrafici_Anagrafica_DataStruct As ICollection(Of GIS_LayerElementiGrafici_Anagrafica_DataStruct) = New HashSet(Of GIS_LayerElementiGrafici_Anagrafica_DataStruct)

End Class
