'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class Imputazioni_Fasi

    'Simple Properties
    <DataMember()>
    Public Property Piva_SuperUser As String
    <DataMember()>
    Public Property Piva As String
    <DataMember()>
    Public Property Imputazione_Cod As Integer
    <DataMember()>
    Public Property Imputazione_Fase_Cod As Integer
    <DataMember()>
    Public Property Imputazione_Fase_Nome As String
    <DataMember()>
    Public Property Imputazione_Fase_Cod_Des As String
    <DataMember()>
    Public Property Imputazione_Fase_Des As String
    <DataMember()>
    Public Property Ordine As Short
    <DataMember()>
    Public Property Tipo_Fase As Short
    <DataMember()>
    Public Property Filtro_Operazioni As String
    <DataMember()>
    Public Property Fase_Budget As Double
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property datainvio As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Validita_Fine As Nullable(Of Date)
    <DataMember()>
    Public Property Filtro_Operazioni_Dettagli As String
    <DataMember()>
    Public Property Filtro_Preparazioni As String
    <DataMember()>
    Public Property Filtro_Preparazioni_Dettagli As String
    <DataMember()>
    Public Property ChkRicette As Short

End Class
