'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class Imputazioni_Fasi_Dettagli

    'Simple Properties
    <DataMember()>
    Public Property Piva_SuperUser As String
    <DataMember()>
    Public Property Piva As String
    <DataMember()>
    Public Property Imputazione_Cod As Integer
    <DataMember()>
    Public Property Imputazione_Fase_Cod As Integer
    <DataMember()>
    Public Property Tipo_Entita As Integer
    <DataMember()>
    Public Property Elem_Cod As Integer
    <DataMember()>
    Public Property Pro_Cod As Integer
    <DataMember()>
    Public Property Mat_Cod As Integer
    <DataMember()>
    Public Property Udm_Cod As Integer
    <DataMember()>
    Public Property Qta As Double
    <DataMember()>
    Public Property Prezzo_Unitario As Double
    <DataMember()>
    Public Property Budget As Double
    <DataMember()>
    Public Property Modalita As Short
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property datainvio As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Validita_Fine As Nullable(Of Date)
    <DataMember()>
    Public Property Ordine_Dettaglio As Integer
    <DataMember()>
    Public Property Lotto As String
    <DataMember()>
    Public Property Turno_Cod As Integer
    <DataMember()>
    Public Property ID_Attivita As Integer
    <DataMember()>
    Public Property Qualifica_Cod As Integer
    <DataMember()>
    Public Property Tariffa_Cod As Integer
    <DataMember()>
    Public Property Tipo_Fase As Short
    <DataMember()>
    Public Property Descrizione As String
    <DataMember()>
    Public Property ID As Integer

End Class
