'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class IoT_Sorgenti

    'Simple Properties
    <DataMember()>
    Public Property Id As Integer
    <DataMember()>
    Public Property Descrizione As String
    <DataMember()>
    Public Property Ordine As Nullable(Of Integer)
    <DataMember()>
    Public Property Note As String

End Class
