'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class Listini_PrezzixContatti

    'Simple Properties
    <DataMember()>
    Public Property Piva_SuperUser As String
    <DataMember()>
    Public Property Piva As String
    <DataMember()>
    Public Property Listino_Cod As Integer
    <DataMember()>
    Public Property Sa_Cod As Integer
    <DataMember()>
    Public Property Cod_Rapporto As Integer
    <DataMember()>
    Public Property Cod_Contatto As String
    <DataMember()>
    Public Property Cod_Contatto_Produttore As String
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property datainvio As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Date
    <DataMember()>
    Public Property Validita_Fine As Date

End Class
