'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class Materie_Prime_XLingue_IT_ch

    'Simple Properties
    <DataMember()>
    Public Property Cal_Cod As Nullable(Of Integer)
    <DataMember()>
    Public Property CAT_COD As Nullable(Of Integer)
    <DataMember()>
    Public Property Categoria_Vino_Cod As Nullable(Of Short)
    <DataMember()>
    Public Property ChkAlias As Nullable(Of Short)
    <DataMember()>
    Public Property ChkContenitore As Short
    <DataMember()>
    Public Property ChkEscludi_Magazzino As Nullable(Of Short)
    <DataMember()>
    Public Property ChkEscludi_Preparazione As Nullable(Of Short)
    <DataMember()>
    Public Property ChkImballaggio As Short
    <DataMember()>
    Public Property ChkListino As Short
    <DataMember()>
    Public Property ChkReferenza As Nullable(Of Short)
    <DataMember()>
    Public Property ChkStampa_Dettagli As Nullable(Of Short)
    <DataMember()>
    Public Property ClToss_Cod As String
    <DataMember()>
    Public Property Cod_Articolo As String
    <DataMember()>
    Public Property Cod_TecnologiaSementi As Nullable(Of Integer)
    <DataMember()>
    Public Property Codice_Esterno As String
    <DataMember()>
    Public Property Codice_NC As String
    <DataMember()>
    Public Property Codice_Prodotto As Integer
    <DataMember()>
    Public Property Colore As Integer
    <DataMember()>
    Public Property Confezione_Cod As String
    <DataMember()>
    Public Property Cul_Cod As Nullable(Of Integer)
    <DataMember()>
    Public Property data_creazione As Nullable(Of Date)
    <DataMember()>
    Public Property data_modifica As Nullable(Of Date)
    <DataMember()>
    Public Property datainvio As Nullable(Of Date)
    <DataMember()>
    Public Property Ditta_Cod As Nullable(Of Integer)
    <DataMember()>
    Public Property eBacchus As String
    <DataMember()>
    Public Property Elem_Cod As Integer
    <DataMember()>
    Public Property Extra_Date As Nullable(Of Date)
    <DataMember()>
    Public Property Extra_Int As Nullable(Of Integer)
    <DataMember()>
    Public Property Extra_Str As String
    <DataMember()>
    Public Property Flag_AusiliareFabbricazione As Nullable(Of Short)
    <DataMember()>
    Public Property Flag_Biologico As Nullable(Of Short)
    <DataMember()>
    Public Property Flag_Convenzionale As Nullable(Of Short)
    <DataMember()>
    Public Property Flag_Extra As Short
    <DataMember()>
    Public Property Flag_Importato As Nullable(Of Short)
    <DataMember()>
    Public Property Flag_NonAgricolo As Nullable(Of Short)
    <DataMember()>
    Public Property Flag_Variazione As Nullable(Of Short)
    <DataMember()>
    Public Property GEN_COD As Nullable(Of Integer)
    <DataMember()>
    Public Property Germinabilita As Nullable(Of Double)
    <DataMember()>
    Public Property Grfi_Cod As Integer
    <DataMember()>
    Public Property GRVA_COD_VEG As Nullable(Of Integer)
    <DataMember()>
    Public Property Id_Accisa_Cod As Nullable(Of Integer)
    <DataMember()>
    Public Property ID_DisciplinareAcquisti As Nullable(Of Integer)
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property IPRO_COD As Nullable(Of Integer)
    <DataMember()>
    Public Property K2O As Nullable(Of Double)
    <DataMember()>
    Public Property Linea_Cod As Nullable(Of Integer)
    <DataMember()>
    Public Property Lotto_Default As String
    <DataMember()>
    Public Property Manipolazioni As Integer
    <DataMember()>
    Public Property Mat_Cod As Integer
    <DataMember()>
    Public Property Mat_Cod_Origine As Nullable(Of Integer)
    <DataMember()>
    Public Property Mat_Cod_Referenza As Nullable(Of Integer)
    <DataMember()>
    Public Property Mat_Des As String
    <DataMember()>
    Public Property MgO As Nullable(Of Double)
    <DataMember()>
    Public Property N As Nullable(Of Double)
    <DataMember()>
    Public Property NewClToss_Cod As String
    <DataMember()>
    Public Property Note As String
    <DataMember()>
    Public Property OTabella_Cod_Base As Nullable(Of Integer)
    <DataMember()>
    Public Property P2O5 As Nullable(Of Double)
    <DataMember()>
    Public Property Peso_Set As Short
    <DataMember()>
    Public Property Piva As String
    <DataMember()>
    Public Property Piva_SuperUser_Origine As String
    <DataMember()>
    Public Property Prezzo_Unitario As Nullable(Of Double)
    <DataMember()>
    Public Property Priorita As Nullable(Of Short)
    <DataMember()>
    Public Property Provenienza_TR As String
    <DataMember()>
    Public Property Qta_Contenitore As Double
    <DataMember()>
    Public Property Qta_Extra As Double
    <DataMember()>
    Public Property RAZ_COD As Nullable(Of Integer)
    <DataMember()>
    Public Property Regolamento As Nullable(Of Integer)
    <DataMember()>
    Public Property Sa_Cod As Integer
    <DataMember()>
    Public Property Sem_Cod As Nullable(Of Integer)
    <DataMember()>
    Public Property SPE_COD As Nullable(Of Integer)
    <DataMember()>
    Public Property Taglio As Short
    <DataMember()>
    Public Property Tara As Double
    <DataMember()>
    Public Property Tipo_Default As Nullable(Of Integer)
    <DataMember()>
    Public Property Tipo_Peso As Short
    <DataMember()>
    Public Property Tipo_Reg_Alcoli As String
    <DataMember()>
    Public Property Titolo_Alcol As Double
    <DataMember()>
    Public Property Trap_Dur As Nullable(Of Integer)
    <DataMember()>
    Public Property Udm_Cod As Integer
    <DataMember()>
    Public Property Udm_Cod_Extra As Integer
    <DataMember()>
    Public Property username_creazione As String
    <DataMember()>
    Public Property username_modifica As String
    <DataMember()>
    Public Property Uso As Nullable(Of Integer)
    <DataMember()>
    Public Property validita_fine As Nullable(Of Date)
    <DataMember()>
    Public Property validita_inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Veg_Cod As Nullable(Of Integer)

End Class
