'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class Mov_Dettagli_Interfacciamenti

    'Simple Properties
    <DataMember()>
    Public Property Piva_SuperUser As String
    <DataMember()>
    Public Property Piva As String
    <DataMember()>
    Public Property Tipo_Cod As Integer
    <DataMember()>
    Public Property Codice As String
    <DataMember()>
    Public Property Codice_Extra As Integer
    <DataMember()>
    Public Property Sa_Cod_Destinazione As Nullable(Of Integer)
    <DataMember()>
    Public Property Tipo_Destinazione As Nullable(Of Short)
    <DataMember()>
    Public Property Id_Destinazione As Nullable(Of Integer)
    <DataMember()>
    Public Property Elem_Cod As Nullable(Of Integer)
    <DataMember()>
    Public Property Pro_Cod As Nullable(Of Integer)
    <DataMember()>
    Public Property Mat_Cod As Nullable(Of Integer)
    <DataMember()>
    Public Property Mat_Cod_Alias As Nullable(Of Integer)
    <DataMember()>
    Public Property Listino_Cod As Nullable(Of Integer)
    <DataMember()>
    Public Property Listino_Cod_Des As String
    <DataMember()>
    Public Property Udm_Cod As Nullable(Of Integer)
    <DataMember()>
    Public Property Lotto As String
    <DataMember()>
    Public Property Qta As Nullable(Of Double)
    <DataMember()>
    Public Property Cal_Cod As Nullable(Of Integer)
    <DataMember()>
    Public Property Contenitore_Cod As Nullable(Of Integer)
    <DataMember()>
    Public Property Sconto_Modalita As Nullable(Of Short)
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property datainvio As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Validita_Fine As Nullable(Of Date)
    <DataMember()>
    Public Property Tipo_Classe As Nullable(Of Short)
    <DataMember()>
    Public Property Note As String
    <DataMember()>
    Public Property Cod_Conto_Int_Default As Nullable(Of Integer)
    <DataMember()>
    Public Property ChkTouchScreen As Nullable(Of Short)
    <DataMember()>
    Public Property DirPicture As String
    <DataMember()>
    Public Property Modulo_Interfaccia As Integer
    <DataMember()>
    Public Property Descrizione_Addizionale As String
    <DataMember()>
    Public Property Cod_IvaIndetraibile As Integer
    <DataMember()>
    Public Property Iva_Indetraibile_Perc As Double

End Class
