'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class Movimenti_Imputazioni_Dettagli

    'Simple Properties
    <DataMember()>
    Public Property Piva As String
    <DataMember()>
    Public Property Sa_Cod As Integer
    <DataMember()>
    Public Property Id_Agenda As Integer
    <DataMember()>
    Public Property Id_Mov As Integer
    <DataMember()>
    Public Property Id_Mov_Det As Integer
    <DataMember()>
    Public Property Id_Imputazione As Integer
    <DataMember()>
    Public Property Imputazione_Cod_Dettaglio As Integer
    <DataMember()>
    Public Property Imputazione_Fase_Cod_Dettaglio As Integer
    <DataMember()>
    Public Property Valore_Dettaglio As Double
    <DataMember()>
    Public Property Percentuale_Dettaglio As Double
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property datainvio As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Validita_Fine As Nullable(Of Date)
    <DataMember()>
    Public Property Id_Attivita As Integer
    <DataMember()>
    Public Property Turno_Cod As Integer
    <DataMember()>
    Public Property Valore_Unitario As Double

End Class
