'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class OMetaschema_Parametri

    'Simple Properties
    <DataMember()>
    Public Property ID As Integer
    <DataMember()>
    Public Property Metaschema_Cod As Integer
    <DataMember()>
    Public Property Modulo_Generazione As Integer
    <DataMember()>
    Public Property Vox_Par_Str1 As String
    <DataMember()>
    Public Property Vox_Par_Str2 As String
    <DataMember()>
    Public Property Vox_Par_Str3 As String
    <DataMember()>
    Public Property Vox_Par_Str4 As String
    <DataMember()>
    Public Property Vox_Par_Str5 As String
    <DataMember()>
    Public Property Vox_Par_Dbl1 As Double
    <DataMember()>
    Public Property Vox_Par_Dbl2 As Double
    <DataMember()>
    Public Property Vox_Par_Dbl3 As Double
    <DataMember()>
    Public Property Vox_Par_Dbl4 As Double
    <DataMember()>
    Public Property Vox_Par_Dbl5 As Double
    <DataMember()>
    Public Property Note As String
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property datainvio As Nullable(Of Date)
    <DataMember()>
    Public Property data_creazione As Nullable(Of Date)
    <DataMember()>
    Public Property data_modifica As Nullable(Of Date)
    <DataMember()>
    Public Property username_creazione As String
    <DataMember()>
    Public Property username_modifica As String
    <DataMember()>
    Public Property validita_inizio As Nullable(Of Date)
    <DataMember()>
    Public Property validita_fine As Nullable(Of Date)
    <DataMember()>
    Public Property Vox_Par_Dbl6 As Double
    <DataMember()>
    Public Property Vox_Par_Dbl7 As Double

End Class
