'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class OTabelle_Parametri

    'Simple Properties
    <DataMember()>
    Public Property Piva As String
    <DataMember()>
    Public Property Tabella_Cod As Integer
    <DataMember()>
    Public Property Tabella_Par_Cod As Integer
    <DataMember()>
    Public Property Modulo_Generazione As Short
    <DataMember()>
    Public Property Descrizione As String
    <DataMember()>
    Public Property Sigla As String
    <DataMember()>
    Public Property Codice_Origine As String
    <DataMember()>
    Public Property ChkInvisibile As Short
    <DataMember()>
    Public Property Valore_Min As Double
    <DataMember()>
    Public Property Valore_Max As Double
    <DataMember()>
    Public Property OFiltro_Veg_Cod As String
    <DataMember()>
    Public Property OFiltro_Cul_Cod As String
    <DataMember()>
    Public Property OFiltro_Colore As String
    <DataMember()>
    Public Property OFiltro_Categoria As String
    <DataMember()>
    Public Property OFiltro_Classificazione As String
    <DataMember()>
    Public Property OFiltro_Dicitura As String
    <DataMember()>
    Public Property OFiltro_Caratteristica As String
    <DataMember()>
    Public Property OFiltro_Deno As String
    <DataMember()>
    Public Property OFiltro_Finalita As String
    <DataMember()>
    Public Property OFiltro_Regolamento As String
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property datainvio As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Validita_Fine As Nullable(Of Date)
    <DataMember()>
    Public Property Codice_Generazione_Link As Nullable(Of Integer)
    <DataMember()>
    Public Property Mat_Cod_Generazione_Link As Integer

End Class
