'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class ParticelleCatastaliClassamento

    'Simple Properties
    <DataMember()>
    Public Property PROV As String
    <DataMember()>
    Public Property COM As String
    <DataMember()>
    Public Property SEZIONE As String
    <DataMember()>
    Public Property FOGLIO As Integer
    <DataMember()>
    Public Property NUMERO As Integer
    <DataMember()>
    Public Property SUBALTERNO As String
    <DataMember()>
    Public Property QUALITA_COD As Integer
    <DataMember()>
    Public Property Porzione As String
    <DataMember()>
    Public Property CLASSE As String
    <DataMember()>
    Public Property Sup_Classe As Nullable(Of Double)
    <DataMember()>
    Public Property REDDITO_DOMINICALE As Nullable(Of Double)
    <DataMember()>
    Public Property REDDITO_AGRARIO As Nullable(Of Double)
    <DataMember()>
    Public Property Deduzione As String
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property datainvio As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Validita_Fine As Nullable(Of Date)

End Class
