'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class PDC_MarketAccess

    'Simple Properties
    <DataMember()>
    Public Property PivaSuperUser As String
    <DataMember()>
    Public Property ID_PDC_Testata As Integer
    <DataMember()>
    Public Property ID_PDC_Dettagli As Integer
    <DataMember()>
    Public Property Piva As String
    <DataMember()>
    Public Property Sa_Cod As Integer
    <DataMember()>
    Public Property Appezza As Integer
    <DataMember()>
    Public Property Id_Reg As Integer
    <DataMember()>
    Public Property CapitolatoCliente_Cod As Integer
    <DataMember()>
    Public Property Esito As Integer
    <DataMember()>
    Public Property Decision As String
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property datainvio As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Validita_Fine As Nullable(Of Date)
    <DataMember()>
    Public Property Codice_Campione As String
    <DataMember()>
    Public Property Resa As Nullable(Of Double)
    <DataMember()>
    Public Property Blocco_Flag As Nullable(Of Short)
    <DataMember()>
    Public Property Blocco_Data As Nullable(Of Date)
    <DataMember()>
    Public Property Blocco_Username As String

End Class
