'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class Prenotazione_Piante_Categoria_XLingue_fr

    'Simple Properties
    <DataMember()>
    Public Property Calibro As Nullable(Of Integer)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property datainvio As Nullable(Of Date)
    <DataMember()>
    Public Property Forma_Allevamento As Nullable(Of Integer)
    <DataMember()>
    Public Property ID_Categoria As Integer
    <DataMember()>
    Public Property ID_MacroCategoria As Integer
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property MacroCategoria As String
    <DataMember()>
    Public Property NomeCategoria As String
    <DataMember()>
    Public Property Numero_Marze As Nullable(Of Integer)
    <DataMember()>
    Public Property Numero_Piante As Nullable(Of Integer)
    <DataMember()>
    Public Property Portinnesto As Nullable(Of Integer)
    <DataMember()>
    Public Property Sesto_impianto As Nullable(Of Integer)
    <DataMember()>
    Public Property Specie As Nullable(Of Integer)
    <DataMember()>
    Public Property Tipologia As Nullable(Of Integer)
    <DataMember()>
    Public Property Tipologia_Varietale As Nullable(Of Integer)
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Fine As Nullable(Of Date)
    <DataMember()>
    Public Property Validita_Inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Varieta As Nullable(Of Integer)

End Class
