'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
<KnownType(GetType(Imprese))>
Partial Public Class ProduzioniQualita

    'Simple Properties
    <DataMember()>
    Public Property PIVA As String
    <DataMember()>
    Public Property CodMacroarea As String
    <DataMember()>
    Public Property CodProduzione As String
    <DataMember()>
    Public Property descrMacroarea As String
    <DataMember()>
    Public Property descrProduzione As String
    <DataMember()>
    Public Property Fonte As String
    <DataMember()>
    Public Property ID_Utente As String
    <DataMember()>
    Public Property DT_Variazione As Nullable(Of Date)
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property datainvio As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Validita_Fine As Nullable(Of Date)

    'Navigation Properties
    <DataMember()>
    Public Overridable Property Imprese As Imprese

End Class
