'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class PUA_Consistenze_Animali

    'Simple Properties
    <DataMember()>
    Public Property Piva_SuperUser As String
    <DataMember()>
    Public Property PUA_Cod As Integer
    <DataMember()>
    Public Property Cons_Cod As Integer
    <DataMember()>
    Public Property Gen_Cod As Integer
    <DataMember()>
    Public Property Spe_Cod As Integer
    <DataMember()>
    Public Property Ipro_Cod As Integer
    <DataMember()>
    Public Property Cat_Cod As Integer
    <DataMember()>
    Public Property Cod_Fabb As String
    <DataMember()>
    Public Property num_capi As Integer
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property Data_Creazione As Date
    <DataMember()>
    Public Property Data_Modifica As Date
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Date
    <DataMember()>
    Public Property Validita_Fine As Date
    <DataMember()>
    Public Property Regolamento_Cod As Integer

End Class
