'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class PUA_Testata

    'Simple Properties
    <DataMember()>
    Public Property Piva_SuperUser As String
    <DataMember()>
    Public Property PUA_Cod As Integer
    <DataMember()>
    Public Property Piva As String
    <DataMember()>
    Public Property Note As String
    <DataMember()>
    Public Property Colture_Vernine As Short
    <DataMember()>
    Public Property Sup_Lagoni As Double
    <DataMember()>
    Public Property PUA_Anno As Integer
    <DataMember()>
    Public Property PUA_Tipo As Integer
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property Data_Creazione As Date
    <DataMember()>
    Public Property Data_Modifica As Date
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Date
    <DataMember()>
    Public Property Validita_Fine As Date
    <DataMember()>
    Public Property Legge59 As Nullable(Of Short)
    <DataMember()>
    Public Property Coeff_Efficienza As Nullable(Of Double)
    <DataMember()>
    Public Property Perc_Zootecnico As Nullable(Of Double)
    <DataMember()>
    Public Property Matrice_Prevalente As Nullable(Of Integer)
    <DataMember()>
    Public Property Regolamento_Cod As Integer
    <DataMember()>
    Public Property Tipo_Allevamento As Nullable(Of Integer)
    <DataMember()>
    Public Property Blocco_Flag As Nullable(Of Short)
    <DataMember()>
    Public Property Blocco_Data As Nullable(Of Date)
    <DataMember()>
    Public Property Blocco_Username As String
    <DataMember()>
    Public Property Flag_NonUtilizzo_Fertilizzanti As Nullable(Of Short)
    <DataMember()>
    Public Property Sa_Cod As Nullable(Of Integer)

End Class
