'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class Suoli_Lotti

    'Simple Properties
    <DataMember()>
    Public Property SUOLO_COD As String
    <DataMember()>
    Public Property ID_Lotto As String
    <DataMember()>
    Public Property Sabbia As Nullable(Of Double)
    <DataMember()>
    Public Property Limo As Nullable(Of Double)
    <DataMember()>
    Public Property Argilla As Nullable(Of Double)
    <DataMember()>
    Public Property PH As Nullable(Of Double)
    <DataMember()>
    Public Property CalTot As Nullable(Of Double)
    <DataMember()>
    Public Property CalAtt As Nullable(Of Double)
    <DataMember()>
    Public Property CSC As Nullable(Of Double)
    <DataMember()>
    Public Property MatOrg As Nullable(Of Double)
    <DataMember()>
    Public Property K2OAss As Nullable(Of Double)
    <DataMember()>
    Public Property P2O5Ass As Nullable(Of Double)
    <DataMember()>
    Public Property NTot As Nullable(Of Double)
    <DataMember()>
    Public Property Note As String
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property datainvio As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Validita_Fine As Nullable(Of Date)

End Class
