'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class Trasformazioni_Scheduling_Testata

    'Simple Properties
    <DataMember()>
    Public Property Piva_SuperUser As String
    <DataMember()>
    Public Property Piva As String
    <DataMember()>
    Public Property Id_Scheduling_Testata As Integer
    <DataMember()>
    Public Property Titolo_Testata As String
    <DataMember()>
    Public Property Data_Testata As Date
    <DataMember()>
    Public Property Note As String
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property datainvio As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Validita_Fine As Nullable(Of Date)
    <DataMember()>
    Public Property Tipo_Testata As Short
    <DataMember()>
    Public Property Testata_Extra_Dbl1 As Double
    <DataMember()>
    Public Property Testata_Extra_Dbl2 As Double
    <DataMember()>
    Public Property Testata_Extra_Dbl3 As Double
    <DataMember()>
    Public Property Testata_Extra_Dbl4 As Double
    <DataMember()>
    Public Property Testata_Extra_Dbl5 As Double
    <DataMember()>
    Public Property Testata_Extra_Str1 As String
    <DataMember()>
    Public Property Testata_Extra_Str2 As String
    <DataMember()>
    Public Property Testata_Extra_Str3 As String
    <DataMember()>
    Public Property Testata_Extra_Str4 As String
    <DataMember()>
    Public Property Testata_Extra_Str5 As String
    <DataMember()>
    Public Property Testata_Extra_Int1 As Integer
    <DataMember()>
    Public Property Testata_Extra_Int2 As Integer
    <DataMember()>
    Public Property Testata_Extra_Int3 As Integer
    <DataMember()>
    Public Property Testata_Extra_Int4 As Integer
    <DataMember()>
    Public Property Testata_Extra_Int5 As Integer

End Class
