'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
<KnownType(GetType(Verifica_Conformita_Esiti))>
<KnownType(GetType(Verifica_Conformita_Esiti_Giacenze))>
<KnownType(GetType(Verifica_Conformita_Esiti_Magazzino))>
<KnownType(GetType(Verifica_Conformita_Risultati))>
Partial Public Class Verifica_Conformita_Testata

    'Simple Properties
    <DataMember()>
    Public Property Id_Testata As Integer
    <DataMember()>
    Public Property Piva As String
    <DataMember()>
    Public Property Sa_Cod As Integer
    <DataMember()>
    Public Property Veg_Cod As Integer
    <DataMember()>
    Public Property Intervallo_Inizio As Date
    <DataMember()>
    Public Property Intervallo_Fine As Date
    <DataMember()>
    Public Property Dpi_Cod As String
    <DataMember()>
    Public Property Flag_Solo_Controlli_Utente As Boolean
    <DataMember()>
    Public Property Flag_Verifica_Magazzino As Boolean
    <DataMember()>
    Public Property Flag_Verifica_IAF As Boolean
    <DataMember()>
    Public Property Tempo_Impiegato_ss As Double
    <DataMember()>
    Public Property Numero_Operazioni_Verificate As Integer
    <DataMember()>
    Public Property Origine As Integer
    <DataMember()>
    Public Property Inviato As Nullable(Of Short)
    <DataMember()>
    Public Property DataInvio As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Validita_Fine As Nullable(Of Date)
    <DataMember()>
    Public Property GUID As String
    <DataMember()>
    Public Property Payload As String
    <DataMember()>
    Public Property Response As String
    <DataMember()>
    Public Property Status As Integer
    <DataMember()>
    Public Property Tipo_Operazioni As String
    <DataMember()>
    Public Property Errore As String
    <DataMember()>
    Public Property Conforme_Normative As Nullable(Of Short)
    <DataMember()>
    Public Property Conforme_Magazzino As Nullable(Of Short)
    <DataMember()>
    Public Property Flag_Verifica_Normative As Boolean

    'Navigation Properties
    <DataMember()>
    Public Overridable Property Verifica_Conformita_Esiti As ICollection(Of Verifica_Conformita_Esiti) = New HashSet(Of Verifica_Conformita_Esiti)
    <DataMember()>
    Public Overridable Property Verifica_Conformita_Esiti_Giacenze As ICollection(Of Verifica_Conformita_Esiti_Giacenze) = New HashSet(Of Verifica_Conformita_Esiti_Giacenze)
    <DataMember()>
    Public Overridable Property Verifica_Conformita_Esiti_Magazzino As ICollection(Of Verifica_Conformita_Esiti_Magazzino) = New HashSet(Of Verifica_Conformita_Esiti_Magazzino)
    <DataMember()>
    Public Overridable Property Verifica_Conformita_Risultati As ICollection(Of Verifica_Conformita_Risultati) = New HashSet(Of Verifica_Conformita_Risultati)

End Class
