'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
<KnownType(GetType(ws_SQNPI_Domanda_Soggetto))>
Partial Public Class ws_SQNPI_Domanda_Soggetto_Catasto_Terreno

    'Simple Properties
    <DataMember()>
    Public Property PROV As String
    <DataMember()>
    Public Property COM As String
    <DataMember()>
    Public Property SEZIONE As String
    <DataMember()>
    Public Property FOGLIO As Integer
    <DataMember()>
    Public Property NUMERO As Integer
    <DataMember()>
    Public Property SUBALTERNO As String
    <DataMember()>
    Public Property Prodotto_AGEA As String
    <DataMember()>
    Public Property Varietà_AGEA As String
    <DataMember()>
    Public Property IdentificativoFlusso As String
    <DataMember()>
    Public Property SoggettoCUAA As String
    <DataMember()>
    Public Property ResaMedia As Integer
    <DataMember()>
    Public Property SUP_INVESTITA_CENTIARE As Nullable(Of Integer)
    <DataMember()>
    Public Property MacroUso As String
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property datainvio As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Validita_Fine As Nullable(Of Date)

    'Navigation Properties
    <DataMember()>
    Public Overridable Property ws_SQNPI_Domanda_Soggetto As ws_SQNPI_Domanda_Soggetto

End Class
