var reportBioResx = [];
var resxArrPath = [
    "GestioneStampe/Biologico/App_LocalResources/Filtro_ReportBiologico.aspx.resx",
    "App_GlobalResources/AgronicaStampe_2010.resx",
    "AgronicaCoreDataProvider.dll/AgronicaCoreDataProvider.Gias"
];

var enumTipiReport = {
    SchedaMateriePrime: 21,
    SchedaVendite: 22,
    RegistroPreparazioni: 153,
    CarichiScarichi: 1,
    ReportTerzisti: 2
};

var enumAgendaCausali = {
    carico: 7300,
    scarico: 7350
};

var elencoTipiAppezzamento = [];

var dataSourceGrid = [];

var categorieMatPrimeDefault = "3|191|204|10";
var categorieVenditeDefault = "201|210";
var categorieCarichiScarichiDefault = "201|10|3|191|304";

var bindReportFilterAlt = {
    [enumTipiReport.SchedaMateriePrime]: {
        boxImpresa: true,
        boxCentroAziendale: true,
        boxMagazzino: true,
        boxDataInizio: true,
        boxDataFine: true,
        boxCategorieMagazzino: true,
        boxTipoAppezzamento: false,
        boxClasseProdotto: true,
        boxArrotondamento: true,
        boxStampaLotto: false,
        boxCodiceArticolo: true,
        boxConsistenzaVasca: true,
        boxProdotto: false,
        boxContatto: false,
        boxRegione: true,
        boxLogoRegione: false,
        boxSemilavoratoTrasformato: false,
        boxPreparazioni: false,
        boxSezioneA: false,
        boxSezioneB: false,
        boxTipoMovimento: false,
        boxOrigineDatiCauScarichi: false,
        boxGiacenzeMagazzino: false,
        boxMultiSelProdotti: false,
        boxLivelloDettaglio: false,
        boxFornitore: false,
        boxAssistenza: true,
        boxMostraDataStampa: true,
        boxMostraFirmaODC: cFlagMostraFirmaODC 
    },
    [enumTipiReport.SchedaVendite]: {
        boxImpresa: true,
        boxCentroAziendale: true,
        boxMagazzino: true,
        boxDataInizio: true,
        boxDataFine: true,
        boxCategorieMagazzino: true,
        boxTipoAppezzamento: false,
        boxClasseProdotto: true,
        boxArrotondamento: true,
        boxStampaLotto: true,
        boxCodiceArticolo: true,
        boxConsistenzaVasca: false,
        boxProdotto: true,
        boxContatto: true,
        boxRegione: true,
        boxLogoRegione: false,
        boxSemilavoratoTrasformato: false,
        boxPreparazioni: false,
        boxSezioneA: false,
        boxSezioneB: false,
        boxTipoMovimento: false,
        boxOrigineDatiCauScarichi: false,
        boxGiacenzeMagazzino: false,
        boxMultiSelProdotti: false,
        boxLivelloDettaglio: false,
        boxFornitore: false,
        boxAssistenza: false,
        boxMostraDataStampa: true,
        boxMostraFirmaODC: cFlagMostraFirmaODC 
    },
    [enumTipiReport.RegistroPreparazioni]: {
        boxImpresa: true,
        boxCentroAziendale: true,
        boxMagazzino: true,
        boxDataInizio: true,
        boxDataFine: true,
        boxCategorieMagazzino: false,
        boxTipoAppezzamento: false,
        boxClasseProdotto: false,
        boxArrotondamento: false,
        boxStampaLotto: false,
        boxCodiceArticolo: false,
        boxConsistenzaVasca: false,
        boxProdotto: false,
        boxContatto: false,
        boxRegione: true,
        boxLogoRegione: true,
        boxSemilavoratoTrasformato: true,
        boxPreparazioni: true,
        boxSezioneA: true,
        boxSezioneB: true,
        boxGiacenzeMagazzino: false,
        boxTipoMovimento: false,
        boxOrigineDatiCauScarichi: false,
        boxMultiSelProdotti: false,
        boxLivelloDettaglio: false,
        boxFornitore: false,
        boxAssistenza: false,
        boxMostraDataStampa: false,
        boxMostraFirmaODC: false 
    },
    [enumTipiReport.CarichiScarichi]: {
        boxImpresa: false,
        boxCentroAziendale: false,
        boxMagazzino: false,
        boxDataInizio: true,
        boxDataFine: true,
        boxCategorieMagazzino: true,
        boxTipoAppezzamento: true,
        boxClasseProdotto: false,
        boxArrotondamento: false,
        boxStampaLotto: false,
        boxCodiceArticolo: false,
        boxConsistenzaVasca: false,
        boxProdotto: false,
        boxContatto: false,
        boxRegione: false,
        boxLogoRegione: false,
        boxSemilavoratoTrasformato: false,
        boxPreparazioni: false,
        boxSezioneA: false,
        boxSezioneB: false,
        boxTipoMovimento: true,
        boxOrigineDatiCauScarichi: true,
        boxGiacenzeMagazzino: true,
        boxMultiSelProdotti: false,
        boxLivelloDettaglio: false,
        boxFornitore: false,
        boxAssistenza: false,
        boxMostraDataStampa: false,
        boxMostraFirmaODC: false
    },
    [enumTipiReport.ReportTerzisti]: {
        boxImpresa: true,
        boxCentroAziendale: true,
        boxMagazzino: false,
        boxDataInizio: true,
        boxDataFine: true,
        boxCategorieMagazzino: false,
        boxClasseProdotto: false,
        boxArrotondamento: false,
        boxStampaLotto: false,
        boxCodiceArticolo: false,
        boxConsistenzaVasca: false,
        boxProdotto: false,
        boxContatto: false,
        boxRegione: false,
        boxLogoRegione: false,
        boxSemilavoratoTrasformato: false,
        boxPreparazioni: false,
        boxSezioneA: false,
        boxSezioneB: false,
        boxTipoMovimento: false,
        boxGiacenzeMagazzino: false,
        boxMultiSelProdotti: true,
        boxLivelloDettaglio: true,
        boxFornitore: true,
        boxAssistenza: false,
        boxMostraDataStampa: false,
        boxMostraFirmaODC: false
    }
};