<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AgronicaCoreStd\AgronicaCoreDTOStd\AgronicaCoreDTOStd.csproj" />
    <ProjectReference Include="..\..\AgronicaNetCore\AgronicaNetCore.Base\AgronicaNetCore.Base.csproj" />
    <ProjectReference Include="..\..\AgronicaNetCore\AgronicaNetCore.Magazzino.DAL\AgronicaNetCore.Magazzino.DAL.csproj" />
    <ProjectReference Include="..\..\AgronicaNetCore\AgronicaNetCore.MetaSchema.DAL\AgronicaNetCore.MetaSchema.DAL.csproj" />
  </ItemGroup>

</Project>
