<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:gml="http://www.opengis.net/gml" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.agronica.it/grafica/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:import schemaLocation=".\gml_small.xsd" namespace="http://www.opengis.net/gml" />
  <xs:element name="DatiEntita">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="layersdescrizioni">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="layer">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="valori">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="codice" type="xs:unsignedLong" use="required" />
                            <xs:attribute name="colore_primario" type="xs:unsignedByte" use="required" />
                            <xs:attribute name="colore_secondario" type="xs:unsignedByte" use="required" />
                            <xs:attribute name="varianza" type="xs:unsignedByte" use="required" />
                            <xs:attribute name="icona16" type="xs:string" use="required" />
                            <xs:attribute name="icona32" type="xs:string" use="required" />
                            <xs:attribute name="ZIndex" type="xs:unsignedByte" use="required" />
                            <xs:attribute name="TipoNodoAlberoAnagrafe" type="xs:string" use="optional" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="0" name="tiles">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="tile">
                            <xs:complexType>
                              <xs:attribute name="codice" type="xs:string" use="required" />
                              <xs:attribute name="colore_primario" type="xs:unsignedByte" use="required" />
                              <xs:attribute name="colore_secondario" type="xs:unsignedByte" use="required" />
                              <xs:attribute name="varianza" type="xs:unsignedByte" use="required" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="tipologia_layer" type="xs:unsignedByte" use="required" />
                  <xs:attribute name="nome_layer" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="unbounded" name="Entita">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="layers">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="layer">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:unsignedLong">
                            <xs:attribute name="tipologia_layer" type="xs:unsignedByte" use="required" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Dettaglio">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="PrecisionFarming">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="AppIdRate" type="xs:string" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="DatiAnagrafici">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Impianto">
                      <xs:complexType>
                        <xs:sequence minOccurs="0">
                          <xs:element name="veg_cod" type="xs:unsignedInt" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Planning">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="programmazione_entita">
                      <xs:complexType>
                        <xs:sequence minOccurs="0">
                          <xs:element name="veg_cod" type="xs:unsignedInt" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="autorizzazioni">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="gis">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="inserimento" type="xs:string" />
                          <xs:element name="modifica" type="xs:string" />
                          <xs:element name="cancellazione" type="xs:string" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="EntitaGIAS">
                <xs:complexType>
                  <xs:sequence>                    
                    <xs:element name="DatoGias">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="PivaSuperUser" type="xs:unsignedLong" />
                          <xs:element name="Entita_Cod" type="xs:unsignedByte" />
                          <xs:element name="TipoEntita_Cod" type="xs:unsignedByte" />
                          <xs:element name="Piva" type="xs:unsignedLong" />
                          <xs:element name="Sa_Cod" type="xs:unsignedByte" />
                          <xs:element name="Appezza" type="xs:unsignedByte" />
                          <xs:element name="Campo_Cod" type="xs:unsignedByte" />
                          <xs:element name="Id_Imp" type="xs:unsignedByte" />
                          <xs:element name="PROV" type="xs:unsignedByte" />
                          <xs:element name="COM" type="xs:unsignedByte" />
                          <xs:element name="SEZIONE" type="xs:byte" />
                          <xs:element name="FOGLIO" type="xs:byte" />
                          <xs:element name="NUMERO" type="xs:byte" />
                          <xs:element name="SUBALTERNO" type="xs:byte" />
                          <xs:element name="Programmazione_Entita_Cod" type="xs:byte" />
                          <xs:element name="Programmazione_Cod" type="xs:byte" />
                          <xs:element name="ID_Agenda" type="xs:byte" />
                          <xs:element name="id_mov_det" type="xs:byte" />
                          <xs:element name="Ricetta_Cod"  type="xs:byte" />
                          <xs:element name="Ricetta_Operazione_Cod"  type="xs:byte" />
                          <xs:element name="TipoNodoAlberoAnagrafe"  type="xs:byte" />                          
                          <xs:element name="part_cod" type="xs:unsignedShort" />
                          <xs:element name="OLDGrafica_ID"  type="xs:string" />
                          <xs:element name="inviato" type="xs:unsignedByte" />
                          <xs:element name="Data_Creazione" type="xs:dateTime" />
                          <xs:element name="Data_Modifica" type="xs:dateTime" />
                          <xs:element name="Username_Creazione" type="xs:string" />
                          <xs:element name="Username_Modifica" type="xs:string" />
                          <xs:element name="Validita_Inizio" type="xs:dateTime" />
                          <xs:element name="Validita_Fine" type="xs:dateTime" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="geodata">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element ref="gml:Polygon" />
                    <xs:element minOccurs="0" name="DatiCalcolati">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="geodata_Area" type="xs:double" />
                          <xs:element name="geodata_Perimetro" type="xs:double" />
                          <xs:element name="geodata_Baricentro" type="xs:double" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>                  
                  <xs:attribute name="Flag_GPS" type="xs:unsignedByte" use="required" />
                  <xs:attribute name="ElementoGrafico_Cod" type="xs:unsignedByte" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="TipoOperazioneDB" type="xs:unsignedByte" use="required" />
            <xs:attribute name="ecolor" type="xs:unsignedShort" use="required" />
            <xs:attribute name="eline" type="xs:unsignedShort" use="required" />
            <xs:attribute name="rad" type="xs:unsignedByte" use="required" />
            <xs:attribute name="text" type="xs:string" use="required" />
            <xs:attribute name="validita_inizio" type="xs:string" use="required" />
            <xs:attribute name="validita_fine" type="xs:string" use="required" />
            <xs:attribute name="username_creazione" type="xs:string" use="required" />
            <xs:attribute name="username_modifica" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>