<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:tns="http://www.opengis.net/gml" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.opengis.net/gml" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Polygon">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="exterior">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="LinearRing">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="posList" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Point">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="pos" type="xs:string" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>