'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace wsAssociazioniAziende
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://bdr.izs.it/webservices", ConfigurationName:="wsAssociazioniAziende.wsAssociazioniAziendeSoap")>  _
    Public Interface wsAssociazioniAziendeSoap
        
        'CODEGEN: Generazione di un contratto di messaggio perché il messaggio Insert_Azienda_Consorzio_STRRequest ha intestazioni
        <System.ServiceModel.OperationContractAttribute(Action:="http://bdr.izs.it/webservices/Insert_Azienda_Consorzio_STR", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Insert_Azienda_Consorzio_STR(ByVal request As wsAssociazioniAziende.Insert_Azienda_Consorzio_STRRequest) As wsAssociazioniAziende.Insert_Azienda_Consorzio_STRResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://bdr.izs.it/webservices/Insert_Azienda_Consorzio_STR", ReplyAction:="*")>  _
        Function Insert_Azienda_Consorzio_STRAsync(ByVal request As wsAssociazioniAziende.Insert_Azienda_Consorzio_STRRequest) As System.Threading.Tasks.Task(Of wsAssociazioniAziende.Insert_Azienda_Consorzio_STRResponse)
        
        'CODEGEN: Generazione di un contratto di messaggio perché il messaggio Insert_Azienda_ConsorzioRequest ha intestazioni
        <System.ServiceModel.OperationContractAttribute(Action:="http://bdr.izs.it/webservices/Insert_Azienda_Consorzio", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Insert_Azienda_Consorzio(ByVal request As wsAssociazioniAziende.Insert_Azienda_ConsorzioRequest) As wsAssociazioniAziende.Insert_Azienda_ConsorzioResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://bdr.izs.it/webservices/Insert_Azienda_Consorzio", ReplyAction:="*")>  _
        Function Insert_Azienda_ConsorzioAsync(ByVal request As wsAssociazioniAziende.Insert_Azienda_ConsorzioRequest) As System.Threading.Tasks.Task(Of wsAssociazioniAziende.Insert_Azienda_ConsorzioResponse)
        
        'CODEGEN: Generazione di un contratto di messaggio perché il messaggio Delete_Azienda_Consorzio_STRRequest ha intestazioni
        <System.ServiceModel.OperationContractAttribute(Action:="http://bdr.izs.it/webservices/Delete_Azienda_Consorzio_STR", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Delete_Azienda_Consorzio_STR(ByVal request As wsAssociazioniAziende.Delete_Azienda_Consorzio_STRRequest) As wsAssociazioniAziende.Delete_Azienda_Consorzio_STRResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://bdr.izs.it/webservices/Delete_Azienda_Consorzio_STR", ReplyAction:="*")>  _
        Function Delete_Azienda_Consorzio_STRAsync(ByVal request As wsAssociazioniAziende.Delete_Azienda_Consorzio_STRRequest) As System.Threading.Tasks.Task(Of wsAssociazioniAziende.Delete_Azienda_Consorzio_STRResponse)
        
        'CODEGEN: Generazione di un contratto di messaggio perché il messaggio Delete_Azienda_ConsorzioRequest ha intestazioni
        <System.ServiceModel.OperationContractAttribute(Action:="http://bdr.izs.it/webservices/Delete_Azienda_Consorzio", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Delete_Azienda_Consorzio(ByVal request As wsAssociazioniAziende.Delete_Azienda_ConsorzioRequest) As wsAssociazioniAziende.Delete_Azienda_ConsorzioResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://bdr.izs.it/webservices/Delete_Azienda_Consorzio", ReplyAction:="*")>  _
        Function Delete_Azienda_ConsorzioAsync(ByVal request As wsAssociazioniAziende.Delete_Azienda_ConsorzioRequest) As System.Threading.Tasks.Task(Of wsAssociazioniAziende.Delete_Azienda_ConsorzioResponse)
        
        'CODEGEN: Generazione di un contratto di messaggio perché il messaggio Get_Aziende_ConsorzioRequest ha intestazioni
        <System.ServiceModel.OperationContractAttribute(Action:="http://bdr.izs.it/webservices/Get_Aziende_Consorzio", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Get_Aziende_Consorzio(ByVal request As wsAssociazioniAziende.Get_Aziende_ConsorzioRequest) As wsAssociazioniAziende.Get_Aziende_ConsorzioResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://bdr.izs.it/webservices/Get_Aziende_Consorzio", ReplyAction:="*")>  _
        Function Get_Aziende_ConsorzioAsync(ByVal request As wsAssociazioniAziende.Get_Aziende_ConsorzioRequest) As System.Threading.Tasks.Task(Of wsAssociazioniAziende.Get_Aziende_ConsorzioResponse)
        
        'CODEGEN: Generazione di un contratto di messaggio perché il messaggio Get_Aziende_Consorzio_STRRequest ha intestazioni
        <System.ServiceModel.OperationContractAttribute(Action:="http://bdr.izs.it/webservices/Get_Aziende_Consorzio_STR", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Get_Aziende_Consorzio_STR(ByVal request As wsAssociazioniAziende.Get_Aziende_Consorzio_STRRequest) As wsAssociazioniAziende.Get_Aziende_Consorzio_STRResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://bdr.izs.it/webservices/Get_Aziende_Consorzio_STR", ReplyAction:="*")>  _
        Function Get_Aziende_Consorzio_STRAsync(ByVal request As wsAssociazioniAziende.Get_Aziende_Consorzio_STRRequest) As System.Threading.Tasks.Task(Of wsAssociazioniAziende.Get_Aziende_Consorzio_STRResponse)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://bdr.izs.it/webservices")>  _
    Partial Public Class SOAPAutenticazione
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private usernameField As String
        
        Private passwordField As String
        
        Private ruolo_codiceField As String
        
        Private valore_ruolo_codiceField As String
        
        Private tokenField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
                Me.RaisePropertyChanged("username")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("password")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property ruolo_codice() As String
            Get
                Return Me.ruolo_codiceField
            End Get
            Set
                Me.ruolo_codiceField = value
                Me.RaisePropertyChanged("ruolo_codice")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property valore_ruolo_codice() As String
            Get
                Return Me.valore_ruolo_codiceField
            End Get
            Set
                Me.valore_ruolo_codiceField = value
                Me.RaisePropertyChanged("valore_ruolo_codice")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
                Me.RaisePropertyChanged("token")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
                Me.RaisePropertyChanged("AnyAttr")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Insert_Azienda_Consorzio_STR", WrapperNamespace:="http://bdr.izs.it/webservices", IsWrapped:=true)>  _
    Partial Public Class Insert_Azienda_Consorzio_STRRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://bdr.izs.it/webservices")>  _
        Public SOAPAutenticazione As wsAssociazioniAziende.SOAPAutenticazione
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://bdr.izs.it/webservices", Order:=0)>  _
        Public strRecord As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SOAPAutenticazione As wsAssociazioniAziende.SOAPAutenticazione, ByVal strRecord As String)
            MyBase.New
            Me.SOAPAutenticazione = SOAPAutenticazione
            Me.strRecord = strRecord
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Insert_Azienda_Consorzio_STRResponse", WrapperNamespace:="http://bdr.izs.it/webservices", IsWrapped:=true)>  _
    Partial Public Class Insert_Azienda_Consorzio_STRResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://bdr.izs.it/webservices", Order:=0)>  _
        Public Insert_Azienda_Consorzio_STRResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Insert_Azienda_Consorzio_STRResult As String)
            MyBase.New
            Me.Insert_Azienda_Consorzio_STRResult = Insert_Azienda_Consorzio_STRResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Insert_Azienda_Consorzio", WrapperNamespace:="http://bdr.izs.it/webservices", IsWrapped:=true)>  _
    Partial Public Class Insert_Azienda_ConsorzioRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://bdr.izs.it/webservices")>  _
        Public SOAPAutenticazione As wsAssociazioniAziende.SOAPAutenticazione
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://bdr.izs.it/webservices", Order:=0)>  _
        Public strRecord As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SOAPAutenticazione As wsAssociazioniAziende.SOAPAutenticazione, ByVal strRecord As String)
            MyBase.New
            Me.SOAPAutenticazione = SOAPAutenticazione
            Me.strRecord = strRecord
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Insert_Azienda_ConsorzioResponse", WrapperNamespace:="http://bdr.izs.it/webservices", IsWrapped:=true)>  _
    Partial Public Class Insert_Azienda_ConsorzioResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://bdr.izs.it/webservices", Order:=0)>  _
        Public Insert_Azienda_ConsorzioResult As System.Xml.XmlNode
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Insert_Azienda_ConsorzioResult As System.Xml.XmlNode)
            MyBase.New
            Me.Insert_Azienda_ConsorzioResult = Insert_Azienda_ConsorzioResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Delete_Azienda_Consorzio_STR", WrapperNamespace:="http://bdr.izs.it/webservices", IsWrapped:=true)>  _
    Partial Public Class Delete_Azienda_Consorzio_STRRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://bdr.izs.it/webservices")>  _
        Public SOAPAutenticazione As wsAssociazioniAziende.SOAPAutenticazione
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://bdr.izs.it/webservices", Order:=0)>  _
        Public strRecord As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SOAPAutenticazione As wsAssociazioniAziende.SOAPAutenticazione, ByVal strRecord As String)
            MyBase.New
            Me.SOAPAutenticazione = SOAPAutenticazione
            Me.strRecord = strRecord
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Delete_Azienda_Consorzio_STRResponse", WrapperNamespace:="http://bdr.izs.it/webservices", IsWrapped:=true)>  _
    Partial Public Class Delete_Azienda_Consorzio_STRResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://bdr.izs.it/webservices", Order:=0)>  _
        Public Delete_Azienda_Consorzio_STRResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Delete_Azienda_Consorzio_STRResult As String)
            MyBase.New
            Me.Delete_Azienda_Consorzio_STRResult = Delete_Azienda_Consorzio_STRResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Delete_Azienda_Consorzio", WrapperNamespace:="http://bdr.izs.it/webservices", IsWrapped:=true)>  _
    Partial Public Class Delete_Azienda_ConsorzioRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://bdr.izs.it/webservices")>  _
        Public SOAPAutenticazione As wsAssociazioniAziende.SOAPAutenticazione
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://bdr.izs.it/webservices", Order:=0)>  _
        Public strRecord As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SOAPAutenticazione As wsAssociazioniAziende.SOAPAutenticazione, ByVal strRecord As String)
            MyBase.New
            Me.SOAPAutenticazione = SOAPAutenticazione
            Me.strRecord = strRecord
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Delete_Azienda_ConsorzioResponse", WrapperNamespace:="http://bdr.izs.it/webservices", IsWrapped:=true)>  _
    Partial Public Class Delete_Azienda_ConsorzioResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://bdr.izs.it/webservices", Order:=0)>  _
        Public Delete_Azienda_ConsorzioResult As System.Xml.XmlNode
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Delete_Azienda_ConsorzioResult As System.Xml.XmlNode)
            MyBase.New
            Me.Delete_Azienda_ConsorzioResult = Delete_Azienda_ConsorzioResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Get_Aziende_Consorzio", WrapperNamespace:="http://bdr.izs.it/webservices", IsWrapped:=true)>  _
    Partial Public Class Get_Aziende_ConsorzioRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://bdr.izs.it/webservices")>  _
        Public SOAPAutenticazione As wsAssociazioniAziende.SOAPAutenticazione
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://bdr.izs.it/webservices", Order:=0)>  _
        Public p_azienda_codice As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://bdr.izs.it/webservices", Order:=1)>  _
        Public p_asspro_codice As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SOAPAutenticazione As wsAssociazioniAziende.SOAPAutenticazione, ByVal p_azienda_codice As String, ByVal p_asspro_codice As String)
            MyBase.New
            Me.SOAPAutenticazione = SOAPAutenticazione
            Me.p_azienda_codice = p_azienda_codice
            Me.p_asspro_codice = p_asspro_codice
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Get_Aziende_ConsorzioResponse", WrapperNamespace:="http://bdr.izs.it/webservices", IsWrapped:=true)>  _
    Partial Public Class Get_Aziende_ConsorzioResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://bdr.izs.it/webservices", Order:=0)>  _
        Public Get_Aziende_ConsorzioResult As System.Xml.XmlNode
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Get_Aziende_ConsorzioResult As System.Xml.XmlNode)
            MyBase.New
            Me.Get_Aziende_ConsorzioResult = Get_Aziende_ConsorzioResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Get_Aziende_Consorzio_STR", WrapperNamespace:="http://bdr.izs.it/webservices", IsWrapped:=true)>  _
    Partial Public Class Get_Aziende_Consorzio_STRRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://bdr.izs.it/webservices")>  _
        Public SOAPAutenticazione As wsAssociazioniAziende.SOAPAutenticazione
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://bdr.izs.it/webservices", Order:=0)>  _
        Public p_azienda_codice As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://bdr.izs.it/webservices", Order:=1)>  _
        Public p_asspro_codice As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SOAPAutenticazione As wsAssociazioniAziende.SOAPAutenticazione, ByVal p_azienda_codice As String, ByVal p_asspro_codice As String)
            MyBase.New
            Me.SOAPAutenticazione = SOAPAutenticazione
            Me.p_azienda_codice = p_azienda_codice
            Me.p_asspro_codice = p_asspro_codice
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Get_Aziende_Consorzio_STRResponse", WrapperNamespace:="http://bdr.izs.it/webservices", IsWrapped:=true)>  _
    Partial Public Class Get_Aziende_Consorzio_STRResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://bdr.izs.it/webservices", Order:=0)>  _
        Public Get_Aziende_Consorzio_STRResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Get_Aziende_Consorzio_STRResult As String)
            MyBase.New
            Me.Get_Aziende_Consorzio_STRResult = Get_Aziende_Consorzio_STRResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface wsAssociazioniAziendeSoapChannel
        Inherits wsAssociazioniAziende.wsAssociazioniAziendeSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class wsAssociazioniAziendeSoapClient
        Inherits System.ServiceModel.ClientBase(Of wsAssociazioniAziende.wsAssociazioniAziendeSoap)
        Implements wsAssociazioniAziende.wsAssociazioniAziendeSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsAssociazioniAziende_wsAssociazioniAziendeSoap_Insert_Azienda_Consorzio_STR(ByVal request As wsAssociazioniAziende.Insert_Azienda_Consorzio_STRRequest) As wsAssociazioniAziende.Insert_Azienda_Consorzio_STRResponse Implements wsAssociazioniAziende.wsAssociazioniAziendeSoap.Insert_Azienda_Consorzio_STR
            Return MyBase.Channel.Insert_Azienda_Consorzio_STR(request)
        End Function
        
        Public Function Insert_Azienda_Consorzio_STR(ByVal SOAPAutenticazione As wsAssociazioniAziende.SOAPAutenticazione, ByVal strRecord As String) As String
            Dim inValue As wsAssociazioniAziende.Insert_Azienda_Consorzio_STRRequest = New wsAssociazioniAziende.Insert_Azienda_Consorzio_STRRequest()
            inValue.SOAPAutenticazione = SOAPAutenticazione
            inValue.strRecord = strRecord
            Dim retVal As wsAssociazioniAziende.Insert_Azienda_Consorzio_STRResponse = CType(Me,wsAssociazioniAziende.wsAssociazioniAziendeSoap).Insert_Azienda_Consorzio_STR(inValue)
            Return retVal.Insert_Azienda_Consorzio_STRResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsAssociazioniAziende_wsAssociazioniAziendeSoap_Insert_Azienda_Consorzio_STRAsync(ByVal request As wsAssociazioniAziende.Insert_Azienda_Consorzio_STRRequest) As System.Threading.Tasks.Task(Of wsAssociazioniAziende.Insert_Azienda_Consorzio_STRResponse) Implements wsAssociazioniAziende.wsAssociazioniAziendeSoap.Insert_Azienda_Consorzio_STRAsync
            Return MyBase.Channel.Insert_Azienda_Consorzio_STRAsync(request)
        End Function
        
        Public Function Insert_Azienda_Consorzio_STRAsync(ByVal SOAPAutenticazione As wsAssociazioniAziende.SOAPAutenticazione, ByVal strRecord As String) As System.Threading.Tasks.Task(Of wsAssociazioniAziende.Insert_Azienda_Consorzio_STRResponse)
            Dim inValue As wsAssociazioniAziende.Insert_Azienda_Consorzio_STRRequest = New wsAssociazioniAziende.Insert_Azienda_Consorzio_STRRequest()
            inValue.SOAPAutenticazione = SOAPAutenticazione
            inValue.strRecord = strRecord
            Return CType(Me,wsAssociazioniAziende.wsAssociazioniAziendeSoap).Insert_Azienda_Consorzio_STRAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsAssociazioniAziende_wsAssociazioniAziendeSoap_Insert_Azienda_Consorzio(ByVal request As wsAssociazioniAziende.Insert_Azienda_ConsorzioRequest) As wsAssociazioniAziende.Insert_Azienda_ConsorzioResponse Implements wsAssociazioniAziende.wsAssociazioniAziendeSoap.Insert_Azienda_Consorzio
            Return MyBase.Channel.Insert_Azienda_Consorzio(request)
        End Function
        
        Public Function Insert_Azienda_Consorzio(ByVal SOAPAutenticazione As wsAssociazioniAziende.SOAPAutenticazione, ByVal strRecord As String) As System.Xml.XmlNode
            Dim inValue As wsAssociazioniAziende.Insert_Azienda_ConsorzioRequest = New wsAssociazioniAziende.Insert_Azienda_ConsorzioRequest()
            inValue.SOAPAutenticazione = SOAPAutenticazione
            inValue.strRecord = strRecord
            Dim retVal As wsAssociazioniAziende.Insert_Azienda_ConsorzioResponse = CType(Me,wsAssociazioniAziende.wsAssociazioniAziendeSoap).Insert_Azienda_Consorzio(inValue)
            Return retVal.Insert_Azienda_ConsorzioResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsAssociazioniAziende_wsAssociazioniAziendeSoap_Insert_Azienda_ConsorzioAsync(ByVal request As wsAssociazioniAziende.Insert_Azienda_ConsorzioRequest) As System.Threading.Tasks.Task(Of wsAssociazioniAziende.Insert_Azienda_ConsorzioResponse) Implements wsAssociazioniAziende.wsAssociazioniAziendeSoap.Insert_Azienda_ConsorzioAsync
            Return MyBase.Channel.Insert_Azienda_ConsorzioAsync(request)
        End Function
        
        Public Function Insert_Azienda_ConsorzioAsync(ByVal SOAPAutenticazione As wsAssociazioniAziende.SOAPAutenticazione, ByVal strRecord As String) As System.Threading.Tasks.Task(Of wsAssociazioniAziende.Insert_Azienda_ConsorzioResponse)
            Dim inValue As wsAssociazioniAziende.Insert_Azienda_ConsorzioRequest = New wsAssociazioniAziende.Insert_Azienda_ConsorzioRequest()
            inValue.SOAPAutenticazione = SOAPAutenticazione
            inValue.strRecord = strRecord
            Return CType(Me,wsAssociazioniAziende.wsAssociazioniAziendeSoap).Insert_Azienda_ConsorzioAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsAssociazioniAziende_wsAssociazioniAziendeSoap_Delete_Azienda_Consorzio_STR(ByVal request As wsAssociazioniAziende.Delete_Azienda_Consorzio_STRRequest) As wsAssociazioniAziende.Delete_Azienda_Consorzio_STRResponse Implements wsAssociazioniAziende.wsAssociazioniAziendeSoap.Delete_Azienda_Consorzio_STR
            Return MyBase.Channel.Delete_Azienda_Consorzio_STR(request)
        End Function
        
        Public Function Delete_Azienda_Consorzio_STR(ByVal SOAPAutenticazione As wsAssociazioniAziende.SOAPAutenticazione, ByVal strRecord As String) As String
            Dim inValue As wsAssociazioniAziende.Delete_Azienda_Consorzio_STRRequest = New wsAssociazioniAziende.Delete_Azienda_Consorzio_STRRequest()
            inValue.SOAPAutenticazione = SOAPAutenticazione
            inValue.strRecord = strRecord
            Dim retVal As wsAssociazioniAziende.Delete_Azienda_Consorzio_STRResponse = CType(Me,wsAssociazioniAziende.wsAssociazioniAziendeSoap).Delete_Azienda_Consorzio_STR(inValue)
            Return retVal.Delete_Azienda_Consorzio_STRResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsAssociazioniAziende_wsAssociazioniAziendeSoap_Delete_Azienda_Consorzio_STRAsync(ByVal request As wsAssociazioniAziende.Delete_Azienda_Consorzio_STRRequest) As System.Threading.Tasks.Task(Of wsAssociazioniAziende.Delete_Azienda_Consorzio_STRResponse) Implements wsAssociazioniAziende.wsAssociazioniAziendeSoap.Delete_Azienda_Consorzio_STRAsync
            Return MyBase.Channel.Delete_Azienda_Consorzio_STRAsync(request)
        End Function
        
        Public Function Delete_Azienda_Consorzio_STRAsync(ByVal SOAPAutenticazione As wsAssociazioniAziende.SOAPAutenticazione, ByVal strRecord As String) As System.Threading.Tasks.Task(Of wsAssociazioniAziende.Delete_Azienda_Consorzio_STRResponse)
            Dim inValue As wsAssociazioniAziende.Delete_Azienda_Consorzio_STRRequest = New wsAssociazioniAziende.Delete_Azienda_Consorzio_STRRequest()
            inValue.SOAPAutenticazione = SOAPAutenticazione
            inValue.strRecord = strRecord
            Return CType(Me,wsAssociazioniAziende.wsAssociazioniAziendeSoap).Delete_Azienda_Consorzio_STRAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsAssociazioniAziende_wsAssociazioniAziendeSoap_Delete_Azienda_Consorzio(ByVal request As wsAssociazioniAziende.Delete_Azienda_ConsorzioRequest) As wsAssociazioniAziende.Delete_Azienda_ConsorzioResponse Implements wsAssociazioniAziende.wsAssociazioniAziendeSoap.Delete_Azienda_Consorzio
            Return MyBase.Channel.Delete_Azienda_Consorzio(request)
        End Function
        
        Public Function Delete_Azienda_Consorzio(ByVal SOAPAutenticazione As wsAssociazioniAziende.SOAPAutenticazione, ByVal strRecord As String) As System.Xml.XmlNode
            Dim inValue As wsAssociazioniAziende.Delete_Azienda_ConsorzioRequest = New wsAssociazioniAziende.Delete_Azienda_ConsorzioRequest()
            inValue.SOAPAutenticazione = SOAPAutenticazione
            inValue.strRecord = strRecord
            Dim retVal As wsAssociazioniAziende.Delete_Azienda_ConsorzioResponse = CType(Me,wsAssociazioniAziende.wsAssociazioniAziendeSoap).Delete_Azienda_Consorzio(inValue)
            Return retVal.Delete_Azienda_ConsorzioResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsAssociazioniAziende_wsAssociazioniAziendeSoap_Delete_Azienda_ConsorzioAsync(ByVal request As wsAssociazioniAziende.Delete_Azienda_ConsorzioRequest) As System.Threading.Tasks.Task(Of wsAssociazioniAziende.Delete_Azienda_ConsorzioResponse) Implements wsAssociazioniAziende.wsAssociazioniAziendeSoap.Delete_Azienda_ConsorzioAsync
            Return MyBase.Channel.Delete_Azienda_ConsorzioAsync(request)
        End Function
        
        Public Function Delete_Azienda_ConsorzioAsync(ByVal SOAPAutenticazione As wsAssociazioniAziende.SOAPAutenticazione, ByVal strRecord As String) As System.Threading.Tasks.Task(Of wsAssociazioniAziende.Delete_Azienda_ConsorzioResponse)
            Dim inValue As wsAssociazioniAziende.Delete_Azienda_ConsorzioRequest = New wsAssociazioniAziende.Delete_Azienda_ConsorzioRequest()
            inValue.SOAPAutenticazione = SOAPAutenticazione
            inValue.strRecord = strRecord
            Return CType(Me,wsAssociazioniAziende.wsAssociazioniAziendeSoap).Delete_Azienda_ConsorzioAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsAssociazioniAziende_wsAssociazioniAziendeSoap_Get_Aziende_Consorzio(ByVal request As wsAssociazioniAziende.Get_Aziende_ConsorzioRequest) As wsAssociazioniAziende.Get_Aziende_ConsorzioResponse Implements wsAssociazioniAziende.wsAssociazioniAziendeSoap.Get_Aziende_Consorzio
            Return MyBase.Channel.Get_Aziende_Consorzio(request)
        End Function
        
        Public Function Get_Aziende_Consorzio(ByVal SOAPAutenticazione As wsAssociazioniAziende.SOAPAutenticazione, ByVal p_azienda_codice As String, ByVal p_asspro_codice As String) As System.Xml.XmlNode
            Dim inValue As wsAssociazioniAziende.Get_Aziende_ConsorzioRequest = New wsAssociazioniAziende.Get_Aziende_ConsorzioRequest()
            inValue.SOAPAutenticazione = SOAPAutenticazione
            inValue.p_azienda_codice = p_azienda_codice
            inValue.p_asspro_codice = p_asspro_codice
            Dim retVal As wsAssociazioniAziende.Get_Aziende_ConsorzioResponse = CType(Me,wsAssociazioniAziende.wsAssociazioniAziendeSoap).Get_Aziende_Consorzio(inValue)
            Return retVal.Get_Aziende_ConsorzioResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsAssociazioniAziende_wsAssociazioniAziendeSoap_Get_Aziende_ConsorzioAsync(ByVal request As wsAssociazioniAziende.Get_Aziende_ConsorzioRequest) As System.Threading.Tasks.Task(Of wsAssociazioniAziende.Get_Aziende_ConsorzioResponse) Implements wsAssociazioniAziende.wsAssociazioniAziendeSoap.Get_Aziende_ConsorzioAsync
            Return MyBase.Channel.Get_Aziende_ConsorzioAsync(request)
        End Function
        
        Public Function Get_Aziende_ConsorzioAsync(ByVal SOAPAutenticazione As wsAssociazioniAziende.SOAPAutenticazione, ByVal p_azienda_codice As String, ByVal p_asspro_codice As String) As System.Threading.Tasks.Task(Of wsAssociazioniAziende.Get_Aziende_ConsorzioResponse)
            Dim inValue As wsAssociazioniAziende.Get_Aziende_ConsorzioRequest = New wsAssociazioniAziende.Get_Aziende_ConsorzioRequest()
            inValue.SOAPAutenticazione = SOAPAutenticazione
            inValue.p_azienda_codice = p_azienda_codice
            inValue.p_asspro_codice = p_asspro_codice
            Return CType(Me,wsAssociazioniAziende.wsAssociazioniAziendeSoap).Get_Aziende_ConsorzioAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsAssociazioniAziende_wsAssociazioniAziendeSoap_Get_Aziende_Consorzio_STR(ByVal request As wsAssociazioniAziende.Get_Aziende_Consorzio_STRRequest) As wsAssociazioniAziende.Get_Aziende_Consorzio_STRResponse Implements wsAssociazioniAziende.wsAssociazioniAziendeSoap.Get_Aziende_Consorzio_STR
            Return MyBase.Channel.Get_Aziende_Consorzio_STR(request)
        End Function
        
        Public Function Get_Aziende_Consorzio_STR(ByVal SOAPAutenticazione As wsAssociazioniAziende.SOAPAutenticazione, ByVal p_azienda_codice As String, ByVal p_asspro_codice As String) As String
            Dim inValue As wsAssociazioniAziende.Get_Aziende_Consorzio_STRRequest = New wsAssociazioniAziende.Get_Aziende_Consorzio_STRRequest()
            inValue.SOAPAutenticazione = SOAPAutenticazione
            inValue.p_azienda_codice = p_azienda_codice
            inValue.p_asspro_codice = p_asspro_codice
            Dim retVal As wsAssociazioniAziende.Get_Aziende_Consorzio_STRResponse = CType(Me,wsAssociazioniAziende.wsAssociazioniAziendeSoap).Get_Aziende_Consorzio_STR(inValue)
            Return retVal.Get_Aziende_Consorzio_STRResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsAssociazioniAziende_wsAssociazioniAziendeSoap_Get_Aziende_Consorzio_STRAsync(ByVal request As wsAssociazioniAziende.Get_Aziende_Consorzio_STRRequest) As System.Threading.Tasks.Task(Of wsAssociazioniAziende.Get_Aziende_Consorzio_STRResponse) Implements wsAssociazioniAziende.wsAssociazioniAziendeSoap.Get_Aziende_Consorzio_STRAsync
            Return MyBase.Channel.Get_Aziende_Consorzio_STRAsync(request)
        End Function
        
        Public Function Get_Aziende_Consorzio_STRAsync(ByVal SOAPAutenticazione As wsAssociazioniAziende.SOAPAutenticazione, ByVal p_azienda_codice As String, ByVal p_asspro_codice As String) As System.Threading.Tasks.Task(Of wsAssociazioniAziende.Get_Aziende_Consorzio_STRResponse)
            Dim inValue As wsAssociazioniAziende.Get_Aziende_Consorzio_STRRequest = New wsAssociazioniAziende.Get_Aziende_Consorzio_STRRequest()
            inValue.SOAPAutenticazione = SOAPAutenticazione
            inValue.p_azienda_codice = p_azienda_codice
            inValue.p_asspro_codice = p_asspro_codice
            Return CType(Me,wsAssociazioniAziende.wsAssociazioniAziendeSoap).Get_Aziende_Consorzio_STRAsync(inValue)
        End Function
    End Class
End Namespace
