<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>AgronicaCoreVarieStdDAL</RootNamespace>
    <TargetFramework>netstandard2.0</TargetFramework>
    <OptionStrict>On</OptionStrict>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugSymbols>false</DebugSymbols>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AgronicaCoreEntityFrameworkSTD\AgronicaCoreEntityFrameworkSTD.csproj" />
    <ProjectReference Include="..\AgronicaCoreEntityFrameworkSTD_POCO\AgronicaCoreEntityFrameworkSTD_POCO.csproj" />
  </ItemGroup>

</Project>
