'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
'
Namespace smssender.gateway.sms
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SMSSoap", [Namespace]:="http://tempuri.org/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(BaseResult))>  _
    Partial Public Class SMS
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CreditoResiduoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private InvioSmsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private StatoSmsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.AgronicaCoreMailBIZ.My.MySettings.Default.AgronicaCoreMailBIZ_smssender_gateway_sms_SMS
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CreditoResiduoCompleted As CreditoResiduoCompletedEventHandler
        
        '''<remarks/>
        Public Event InvioSmsCompleted As InvioSmsCompletedEventHandler
        
        '''<remarks/>
        Public Event StatoSmsCompleted As StatoSmsCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreditoResiduo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CreditoResiduo(ByVal UserId As String, ByVal Password As String) As CreditoResiduoResult
            Dim results() As Object = Me.Invoke("CreditoResiduo", New Object() {UserId, Password})
            Return CType(results(0),CreditoResiduoResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CreditoResiduoAsync(ByVal UserId As String, ByVal Password As String)
            Me.CreditoResiduoAsync(UserId, Password, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreditoResiduoAsync(ByVal UserId As String, ByVal Password As String, ByVal userState As Object)
            If (Me.CreditoResiduoOperationCompleted Is Nothing) Then
                Me.CreditoResiduoOperationCompleted = AddressOf Me.OnCreditoResiduoOperationCompleted
            End If
            Me.InvokeAsync("CreditoResiduo", New Object() {UserId, Password}, Me.CreditoResiduoOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreditoResiduoOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreditoResiduoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreditoResiduoCompleted(Me, New CreditoResiduoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InvioSms", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InvioSms(ByVal UserId As String, ByVal Password As String, ByVal Mittente As String, ByVal Numeri() As String, ByVal Testo As String) As InvioSmsResult
            Dim results() As Object = Me.Invoke("InvioSms", New Object() {UserId, Password, Mittente, Numeri, Testo})
            Return CType(results(0),InvioSmsResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub InvioSmsAsync(ByVal UserId As String, ByVal Password As String, ByVal Mittente As String, ByVal Numeri() As String, ByVal Testo As String)
            Me.InvioSmsAsync(UserId, Password, Mittente, Numeri, Testo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InvioSmsAsync(ByVal UserId As String, ByVal Password As String, ByVal Mittente As String, ByVal Numeri() As String, ByVal Testo As String, ByVal userState As Object)
            If (Me.InvioSmsOperationCompleted Is Nothing) Then
                Me.InvioSmsOperationCompleted = AddressOf Me.OnInvioSmsOperationCompleted
            End If
            Me.InvokeAsync("InvioSms", New Object() {UserId, Password, Mittente, Numeri, Testo}, Me.InvioSmsOperationCompleted, userState)
        End Sub
        
        Private Sub OnInvioSmsOperationCompleted(ByVal arg As Object)
            If (Not (Me.InvioSmsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InvioSmsCompleted(Me, New InvioSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StatoSms", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function StatoSms(ByVal UserId As String, ByVal Password As String, ByVal IdUnivoco As String) As StatoSmsResult
            Dim results() As Object = Me.Invoke("StatoSms", New Object() {UserId, Password, IdUnivoco})
            Return CType(results(0),StatoSmsResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub StatoSmsAsync(ByVal UserId As String, ByVal Password As String, ByVal IdUnivoco As String)
            Me.StatoSmsAsync(UserId, Password, IdUnivoco, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub StatoSmsAsync(ByVal UserId As String, ByVal Password As String, ByVal IdUnivoco As String, ByVal userState As Object)
            If (Me.StatoSmsOperationCompleted Is Nothing) Then
                Me.StatoSmsOperationCompleted = AddressOf Me.OnStatoSmsOperationCompleted
            End If
            Me.InvokeAsync("StatoSms", New Object() {UserId, Password, IdUnivoco}, Me.StatoSmsOperationCompleted, userState)
        End Sub
        
        Private Sub OnStatoSmsOperationCompleted(ByVal arg As Object)
            If (Not (Me.StatoSmsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent StatoSmsCompleted(Me, New StatoSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class CreditoResiduoResult
        Inherits BaseResult
        
        Private creditoField As Long
        
        '''<remarks/>
        Public Property Credito() As Long
            Get
                Return Me.creditoField
            End Get
            Set
                Me.creditoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(StatoSmsResult)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(InvioSmsResult)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(CreditoResiduoResult)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class BaseResult
        
        Private codiceErroreField As String
        
        Private messaggioErroreField As String
        
        Private successoField As Boolean
        
        '''<remarks/>
        Public Property CodiceErrore() As String
            Get
                Return Me.codiceErroreField
            End Get
            Set
                Me.codiceErroreField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MessaggioErrore() As String
            Get
                Return Me.messaggioErroreField
            End Get
            Set
                Me.messaggioErroreField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Successo() As Boolean
            Get
                Return Me.successoField
            End Get
            Set
                Me.successoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class StatoSms
        
        Private dataOraField As String
        
        Private numeroField As String
        
        Private statusField As String
        
        Private messaggioField As String
        
        Private gatewayField As String
        
        '''<remarks/>
        Public Property DataOra() As String
            Get
                Return Me.dataOraField
            End Get
            Set
                Me.dataOraField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Numero() As String
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Messaggio() As String
            Get
                Return Me.messaggioField
            End Get
            Set
                Me.messaggioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Gateway() As String
            Get
                Return Me.gatewayField
            End Get
            Set
                Me.gatewayField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class StatoSmsResult
        Inherits BaseResult
        
        Private statiSmsField() As StatoSms
        
        '''<remarks/>
        Public Property StatiSms() As StatoSms()
            Get
                Return Me.statiSmsField
            End Get
            Set
                Me.statiSmsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class InvioSmsResult
        Inherits BaseResult
        
        Private idUnivocoField As String
        
        '''<remarks/>
        Public Property IdUnivoco() As String
            Get
                Return Me.idUnivocoField
            End Get
            Set
                Me.idUnivocoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub CreditoResiduoCompletedEventHandler(ByVal sender As Object, ByVal e As CreditoResiduoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreditoResiduoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CreditoResiduoResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CreditoResiduoResult)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub InvioSmsCompletedEventHandler(ByVal sender As Object, ByVal e As InvioSmsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InvioSmsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As InvioSmsResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),InvioSmsResult)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub StatoSmsCompletedEventHandler(ByVal sender As Object, ByVal e As StatoSmsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class StatoSmsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As StatoSmsResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),StatoSmsResult)
            End Get
        End Property
    End Class
End Namespace
