name: $(Date:yyyyMMdd).$(Rev:r)

trigger: none

schedules:
  - cron: '30 1 * * *' # cron syntax defining a schedule (02:30)
    displayName: nightly
    branches:
      include: [ develop ] # which branches the schedule applies to

parameters:
  - name: executeDeploy
    displayName: Flag controllo deploy
    type: boolean
    default: false

variables:
- group: Destinations
- template: ../../templates/variables/deploy-path.yml
  parameters:
    branchName: ${{ replace(variables['Build.SourceBranch'], 'refs/heads/', '') }}

extends:
  template: ../../templates/pipelines/net-agro-web-pipeline.yml  # Template reference
  parameters:
    solution: AgronicaAgenda
    target: "AgronicaAgenda_2010"
    artifactName: AgronicaAgenda
    path: 'GiasOnline_2010'
    artifactBasePath: 'GiasOnline_2010\AgronicaAgenda_2010'
    outdir: 'GiasOnline_2010\AgronicaAgenda_2010'
    sonarExcludeDuplicates: true
    execDeploy: ${{ parameters.executeDeploy }}
    deployPath: $(PathDeployFinal)
    preBuildSteps:
      - template: ../../templates/steps/sonar-pre-build.yml
        parameters:
          scannerMode: 'dotnet'
          projectKey: 'Gias_GiasDotNet_AY505uBisb2wmyKfofkO'
          projectName: 'GiasDotNet - Agenda'
          projectVersion: '$(SonarVersion)'
          verbose: 'true'

        #   extraProperties: |
        #     sonar.javascript.node.maxspace=2048
        # env:
        #   SONAR_DOTNET_ENABLE_CONCURRENT_EXECUTION: true
        #   SONAR_SCANNER_OPTS: -Xmx768M

    postBuildSteps:
      - task: CopyFiles@2
        displayName: 'Copia file minificati'
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)\GiasOnline_2010\AgroAgenda_2010'
          Contents: |
            **\\*.build.min.js
            Classi\\Minify\\Min_Config_pers.xml
          TargetFolder: '$(Build.ArtifactStagingDirectory)\GiasOnline_2010\AgronicaAgenda_2010'
          OverWrite: true

      - template: ../../templates/steps/sonar-post-build.yml
        # env: # su Analyze
        #   SONAR_DOTNET_ENABLE_CONCURRENT_EXECUTION: true
        #   SONAR_SCANNER_OPTS: -Xmx768M
