'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'Codice sorgente generato automaticamente da xsd, versione=4.0.30319.1.
'
Namespace DAA.Messaggi
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://emcs.dgtaxud.ec/v10/cd810/ie"),  _
     System.Xml.Serialization.XmlRootAttribute("CD810A", [Namespace]:="http://emcs.dgtaxud.ec/v10/cd810/ie", IsNullable:=false)>  _
    Partial Public Class CD810AType
        
        Private headerMessageField As HeaderMessageType
        
        Private bodyMessageField() As CancellationOfEADType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://emcs.dgtaxud.ec/v10/tms")>  _
        Public Property HeaderMessage() As HeaderMessageType
            Get
                Return Me.headerMessageField
            End Get
            Set
                Me.headerMessageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("CancellationOfEAD", IsNullable:=false)>  _
        Public Property BodyMessage() As CancellationOfEADType()
            Get
                Return Me.bodyMessageField
            End Get
            Set
                Me.bodyMessageField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://emcs.dgtaxud.ec/v10/tms"),  _
     System.Xml.Serialization.XmlRootAttribute("HeaderMessage", [Namespace]:="http://emcs.dgtaxud.ec/v10/tms", IsNullable:=false)>  _
    Partial Public Class HeaderMessageType
        
        Private messageSenderCodeField As String
        
        Private officeReservedField As String
        
        Private flowNameField As String
        
        Private officeReserved1Field As String
        
        Private officeCodeField As String
        
        Private officeReserved2Field As String
        
        Private vATAutorizedSenderField As String
        
        Private officeNumberAutorizedSenderField As String
        
        Private officeReserved3Field As String
        
        Private recordFlowNumberField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="token", Order:=0)>  _
        Public Property MessageSenderCode() As String
            Get
                Return Me.messageSenderCodeField
            End Get
            Set
                Me.messageSenderCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="token", Order:=1)>  _
        Public Property OfficeReserved() As String
            Get
                Return Me.officeReservedField
            End Get
            Set
                Me.officeReservedField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="token", Order:=2)>  _
        Public Property FlowName() As String
            Get
                Return Me.flowNameField
            End Get
            Set
                Me.flowNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("OfficeReserved", DataType:="token", Order:=3)>  _
        Public Property OfficeReserved1() As String
            Get
                Return Me.officeReserved1Field
            End Get
            Set
                Me.officeReserved1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="token", Order:=4)>  _
        Public Property OfficeCode() As String
            Get
                Return Me.officeCodeField
            End Get
            Set
                Me.officeCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("OfficeReserved", DataType:="token", Order:=5)>  _
        Public Property OfficeReserved2() As String
            Get
                Return Me.officeReserved2Field
            End Get
            Set
                Me.officeReserved2Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="token", Order:=6)>  _
        Public Property VATAutorizedSender() As String
            Get
                Return Me.vATAutorizedSenderField
            End Get
            Set
                Me.vATAutorizedSenderField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="token", Order:=7)>  _
        Public Property OfficeNumberAutorizedSender() As String
            Get
                Return Me.officeNumberAutorizedSenderField
            End Get
            Set
                Me.officeNumberAutorizedSenderField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("OfficeReserved", DataType:="token", Order:=8)>  _
        Public Property OfficeReserved3() As String
            Get
                Return Me.officeReserved3Field
            End Get
            Set
                Me.officeReserved3Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="token", Order:=9)>  _
        Public Property RecordFlowNumber() As String
            Get
                Return Me.recordFlowNumberField
            End Get
            Set
                Me.recordFlowNumberField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://emcs.dgtaxud.ec/v10/cd810/ie")>  _
    Partial Public Class LSDComplementaryInformationType
        
        Private languageField As String
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")>  _
        Public Property language() As String
            Get
                Return Me.languageField
            End Get
            Set
                Me.languageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(DataType:="token")>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://emcs.dgtaxud.ec/v10/tms"),  _
     System.Xml.Serialization.XmlRootAttribute("Header", [Namespace]:="http://emcs.dgtaxud.ec/v10/tms", IsNullable:=false)>  _
    Partial Public Class HeaderType
        
        Private messageCodeField As HeaderTypeMessageCode
        
        Private declaratorIdentifyCodeField As HeaderTypeDeclaratorIdentifyCode
        
        Private itemField As Object
        
        Private transmissionFileDateField As HeaderTypeTransmissionFileDate
        
        Private recordTypeField As HeaderTypeRecordType
        
        Private recordNumberInFileField As String
        
        Private recordNumberFileField As String
        
        Private totalRecordBField As String
        
        Private totalRecordCField As String
        
        Private totalRecordFField As String
        
        Private totalRecordKField As String
        
        Private submissionMessageTypeField As HeaderTypeSubmissionMessageType
        
        '''<remarks/>
        Public Property MessageCode() As HeaderTypeMessageCode
            Get
                Return Me.messageCodeField
            End Get
            Set
                Me.messageCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DeclaratorIdentifyCode() As HeaderTypeDeclaratorIdentifyCode
            Get
                Return Me.declaratorIdentifyCodeField
            End Get
            Set
                Me.declaratorIdentifyCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("IdentifyDraftCode", GetType(HeaderTypeIdentifyDraftCode)),  _
         System.Xml.Serialization.XmlElementAttribute("IdentityARCCode", GetType(HeaderTypeIdentityARCCode))>  _
        Public Property Item() As Object
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TransmissionFileDate() As HeaderTypeTransmissionFileDate
            Get
                Return Me.transmissionFileDateField
            End Get
            Set
                Me.transmissionFileDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RecordType() As HeaderTypeRecordType
            Get
                Return Me.recordTypeField
            End Get
            Set
                Me.recordTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="token")>  _
        Public Property RecordNumberInFile() As String
            Get
                Return Me.recordNumberInFileField
            End Get
            Set
                Me.recordNumberInFileField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="token")>  _
        Public Property RecordNumberFile() As String
            Get
                Return Me.recordNumberFileField
            End Get
            Set
                Me.recordNumberFileField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public Property TotalRecordB() As String
            Get
                Return Me.totalRecordBField
            End Get
            Set
                Me.totalRecordBField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public Property TotalRecordC() As String
            Get
                Return Me.totalRecordCField
            End Get
            Set
                Me.totalRecordCField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public Property TotalRecordF() As String
            Get
                Return Me.totalRecordFField
            End Get
            Set
                Me.totalRecordFField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public Property TotalRecordK() As String
            Get
                Return Me.totalRecordKField
            End Get
            Set
                Me.totalRecordKField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SubmissionMessageType() As HeaderTypeSubmissionMessageType
            Get
                Return Me.submissionMessageTypeField
            End Get
            Set
                Me.submissionMessageTypeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://emcs.dgtaxud.ec/v10/tms")>  _
    Partial Public Class HeaderTypeMessageCode
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(DataType:="token")>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://emcs.dgtaxud.ec/v10/tms")>  _
    Partial Public Class HeaderTypeDeclaratorIdentifyCode
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://emcs.dgtaxud.ec/v10/tms")>  _
    Partial Public Class HeaderTypeIdentifyDraftCode
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(DataType:="token")>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://emcs.dgtaxud.ec/v10/tms")>  _
    Partial Public Class HeaderTypeIdentityARCCode
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(DataType:="token")>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://emcs.dgtaxud.ec/v10/tms")>  _
    Partial Public Class HeaderTypeTransmissionFileDate
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://emcs.dgtaxud.ec/v10/tms")>  _
    Partial Public Class HeaderTypeRecordType
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(DataType:="token")>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://emcs.dgtaxud.ec/v10/tms")>  _
    Partial Public Class HeaderTypeSubmissionMessageType
        
        Private valueField As SubmissionType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Value() As SubmissionType
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://emcs.dgtaxud.ec/v10/tms")>  _
    Public Enum SubmissionType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("1")>  _
        Item1
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("2")>  _
        Item2
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://emcs.dgtaxud.ec/v10/cd810/ie")>  _
    Partial Public Class CancellationOfEADType
        
        Private headerField As HeaderType
        
        Private cancellationField As CancellationType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://emcs.dgtaxud.ec/v10/tms")>  _
        Public Property Header() As HeaderType
            Get
                Return Me.headerField
            End Get
            Set
                Me.headerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cancellation() As CancellationType
            Get
                Return Me.cancellationField
            End Get
            Set
                Me.cancellationField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://emcs.dgtaxud.ec/v10/cd810/ie"),  _
     System.Xml.Serialization.XmlRootAttribute("Cancellation", [Namespace]:="http://emcs.dgtaxud.ec/v10/cd810/ie", IsNullable:=false)>  _
    Partial Public Class CancellationType
        
        Private cancellationReasonCodeField As String
        
        Private complementaryInformationField As LSDComplementaryInformationType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="token")>  _
        Public Property CancellationReasonCode() As String
            Get
                Return Me.cancellationReasonCodeField
            End Get
            Set
                Me.cancellationReasonCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ComplementaryInformation() As LSDComplementaryInformationType
            Get
                Return Me.complementaryInformationField
            End Get
            Set
                Me.complementaryInformationField = value
            End Set
        End Property
    End Class
End Namespace
