name: $(Date:yyyyMMdd).$(Rev:r)

trigger: none

schedules:
  - cron: '0 20 * * *' # cron syntax defining a schedule (21:00)
    displayName: nightly
    branches:
      include: [ develop ] # which branches the schedule applies to

parameters:
  - name: executeDeploy
    displayName: Flag controllo deploy
    type: boolean
    default: true

variables:
- group: Destinations
- template: ../../templates/variables/deploy-path.yml
  parameters:
    branchName: ${{ replace(variables['Build.SourceBranch'], 'refs/heads/', '') }}

extends:
  template: ../../templates/pipelines/net-agro-web-pipeline.yml  # Template reference
  parameters:
    solution: AgronicaWebService2010
    target: AgronicaWebApiProfilatore
    artifactName: 'AgronicaWebApiProfilatore'
    path: 'AgronicaWebService2010'
    artifactBasePath: AgronicaWebApiProfilatore
    outdir: 'AgronicaWebApiProfilatore'
    execDeploy: ${{ parameters.executeDeploy }}
    deployPath: $(PathDeployFinal)