'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("DS_EC_Bolle_Conf"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class DS_EC_Bolle_Conf
    Inherits Global.System.Data.DataSet
    
    Private tableDT_EC_Bolle_Conf As DT_EC_Bolle_ConfDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("DT_EC_Bolle_Conf")) Is Nothing) Then
                MyBase.Tables.Add(New DT_EC_Bolle_ConfDataTable(ds.Tables("DT_EC_Bolle_Conf")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0"),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property DT_EC_Bolle_Conf() As DT_EC_Bolle_ConfDataTable
        Get
            Return Me.tableDT_EC_Bolle_Conf
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0"),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As DS_EC_Bolle_Conf = CType(MyBase.Clone,DS_EC_Bolle_Conf)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXml(reader)
            If (Not (ds.Tables("DT_EC_Bolle_Conf")) Is Nothing) Then
                MyBase.Tables.Add(New DT_EC_Bolle_ConfDataTable(ds.Tables("DT_EC_Bolle_Conf")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableDT_EC_Bolle_Conf = CType(MyBase.Tables("DT_EC_Bolle_Conf"),DT_EC_Bolle_ConfDataTable)
        If (initTable = true) Then
            If (Not (Me.tableDT_EC_Bolle_Conf) Is Nothing) Then
                Me.tableDT_EC_Bolle_Conf.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Private Sub InitClass()
        Me.DataSetName = "DS_EC_Bolle_Conf"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/DS_EC_Bolle_Conf.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tableDT_EC_Bolle_Conf = New DT_EC_Bolle_ConfDataTable()
        MyBase.Tables.Add(Me.tableDT_EC_Bolle_Conf)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Private Function ShouldSerializeDT_EC_Bolle_Conf() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As DS_EC_Bolle_Conf = New DS_EC_Bolle_Conf()
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Public Delegate Sub DT_EC_Bolle_ConfRowChangeEventHandler(ByVal sender As Object, ByVal e As DT_EC_Bolle_ConfRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class DT_EC_Bolle_ConfDataTable
        Inherits Global.System.Data.TypedTableBase(Of DT_EC_Bolle_ConfRow)
        
        Private columnCodice_Conferente As Global.System.Data.DataColumn
        
        Private columnRagSoc_Conferente As Global.System.Data.DataColumn
        
        Private columnData_Bolla As Global.System.Data.DataColumn
        
        Private columnNumero_Bolla As Global.System.Data.DataColumn
        
        Private columnData_DDT As Global.System.Data.DataColumn
        
        Private columnNumero_DDT As Global.System.Data.DataColumn
        
        Private columnPeso_Totale As Global.System.Data.DataColumn
        
        Private columnPeso_Totale_Str As Global.System.Data.DataColumn
        
        Private columnTara_Veicolo As Global.System.Data.DataColumn
        
        Private columnTara_Veicolo_Str As Global.System.Data.DataColumn
        
        Private columnPeso_Lordo As Global.System.Data.DataColumn
        
        Private columnPeso_Lordo_Str As Global.System.Data.DataColumn
        
        Private columnTara_Imballi As Global.System.Data.DataColumn
        
        Private columnTara_Imballi_Str As Global.System.Data.DataColumn
        
        Private columnPeso_Netto As Global.System.Data.DataColumn
        
        Private columnPeso_Netto_Str As Global.System.Data.DataColumn
        
        Private columnDegrado_Perc As Global.System.Data.DataColumn
        
        Private columnDegrado_Perc_Str As Global.System.Data.DataColumn
        
        Private columnDegrado As Global.System.Data.DataColumn
        
        Private columnDegrado_Str As Global.System.Data.DataColumn
        
        Private columnNetto_Pag As Global.System.Data.DataColumn
        
        Private columnNetto_Pag_Str As Global.System.Data.DataColumn
        
        Private columnIndice_Qualitativo As Global.System.Data.DataColumn
        
        Private columnPunteggio As Global.System.Data.DataColumn
        
        Private columnCodice_Specie As Global.System.Data.DataColumn
        
        Private columnDescr_Specie As Global.System.Data.DataColumn
        
        Private columnCodice_Articolo As Global.System.Data.DataColumn
        
        Private columnDescr_Articolo As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "DT_EC_Bolle_Conf"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Codice_ConferenteColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCodice_Conferente
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property RagSoc_ConferenteColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnRagSoc_Conferente
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Data_BollaColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnData_Bolla
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Numero_BollaColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnNumero_Bolla
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Data_DDTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnData_DDT
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Numero_DDTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnNumero_DDT
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Peso_TotaleColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPeso_Totale
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Peso_Totale_StrColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPeso_Totale_Str
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Tara_VeicoloColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTara_Veicolo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Tara_Veicolo_StrColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTara_Veicolo_Str
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Peso_LordoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPeso_Lordo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Peso_Lordo_StrColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPeso_Lordo_Str
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Tara_ImballiColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTara_Imballi
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Tara_Imballi_StrColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTara_Imballi_Str
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Peso_NettoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPeso_Netto
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Peso_Netto_StrColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPeso_Netto_Str
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Degrado_PercColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDegrado_Perc
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Degrado_Perc_StrColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDegrado_Perc_Str
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property DegradoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDegrado
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Degrado_StrColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDegrado_Str
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Netto_PagColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnNetto_Pag
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Netto_Pag_StrColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnNetto_Pag_Str
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Indice_QualitativoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnIndice_Qualitativo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property PunteggioColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPunteggio
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Codice_SpecieColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCodice_Specie
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Descr_SpecieColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDescr_Specie
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Codice_ArticoloColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCodice_Articolo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Descr_ArticoloColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDescr_Articolo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0"),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As DT_EC_Bolle_ConfRow
            Get
                Return CType(Me.Rows(index),DT_EC_Bolle_ConfRow)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Event DT_EC_Bolle_ConfRowChanging As DT_EC_Bolle_ConfRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Event DT_EC_Bolle_ConfRowChanged As DT_EC_Bolle_ConfRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Event DT_EC_Bolle_ConfRowDeleting As DT_EC_Bolle_ConfRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Event DT_EC_Bolle_ConfRowDeleted As DT_EC_Bolle_ConfRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Overloads Sub AddDT_EC_Bolle_ConfRow(ByVal row As DT_EC_Bolle_ConfRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Overloads Function AddDT_EC_Bolle_ConfRow( _
                    ByVal Codice_Conferente As String,  _
                    ByVal RagSoc_Conferente As String,  _
                    ByVal Data_Bolla As String,  _
                    ByVal Numero_Bolla As String,  _
                    ByVal Data_DDT As String,  _
                    ByVal Numero_DDT As String,  _
                    ByVal Peso_Totale As Single,  _
                    ByVal Peso_Totale_Str As String,  _
                    ByVal Tara_Veicolo As Single,  _
                    ByVal Tara_Veicolo_Str As String,  _
                    ByVal Peso_Lordo As Single,  _
                    ByVal Peso_Lordo_Str As String,  _
                    ByVal Tara_Imballi As Single,  _
                    ByVal Tara_Imballi_Str As String,  _
                    ByVal Peso_Netto As Single,  _
                    ByVal Peso_Netto_Str As String,  _
                    ByVal Degrado_Perc As Single,  _
                    ByVal Degrado_Perc_Str As String,  _
                    ByVal Degrado As Single,  _
                    ByVal Degrado_Str As String,  _
                    ByVal Netto_Pag As Single,  _
                    ByVal Netto_Pag_Str As String,  _
                    ByVal Indice_Qualitativo As String,  _
                    ByVal Punteggio As Single,  _
                    ByVal Codice_Specie As String,  _
                    ByVal Descr_Specie As String,  _
                    ByVal Codice_Articolo As String,  _
                    ByVal Descr_Articolo As String) As DT_EC_Bolle_ConfRow
            Dim rowDT_EC_Bolle_ConfRow As DT_EC_Bolle_ConfRow = CType(Me.NewRow,DT_EC_Bolle_ConfRow)
            Dim columnValuesArray() As Object = New Object() {Codice_Conferente, RagSoc_Conferente, Data_Bolla, Numero_Bolla, Data_DDT, Numero_DDT, Peso_Totale, Peso_Totale_Str, Tara_Veicolo, Tara_Veicolo_Str, Peso_Lordo, Peso_Lordo_Str, Tara_Imballi, Tara_Imballi_Str, Peso_Netto, Peso_Netto_Str, Degrado_Perc, Degrado_Perc_Str, Degrado, Degrado_Str, Netto_Pag, Netto_Pag_Str, Indice_Qualitativo, Punteggio, Codice_Specie, Descr_Specie, Codice_Articolo, Descr_Articolo}
            rowDT_EC_Bolle_ConfRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowDT_EC_Bolle_ConfRow)
            Return rowDT_EC_Bolle_ConfRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As DT_EC_Bolle_ConfDataTable = CType(MyBase.Clone,DT_EC_Bolle_ConfDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New DT_EC_Bolle_ConfDataTable()
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Friend Sub InitVars()
            Me.columnCodice_Conferente = MyBase.Columns("Codice_Conferente")
            Me.columnRagSoc_Conferente = MyBase.Columns("RagSoc_Conferente")
            Me.columnData_Bolla = MyBase.Columns("Data_Bolla")
            Me.columnNumero_Bolla = MyBase.Columns("Numero_Bolla")
            Me.columnData_DDT = MyBase.Columns("Data_DDT")
            Me.columnNumero_DDT = MyBase.Columns("Numero_DDT")
            Me.columnPeso_Totale = MyBase.Columns("Peso_Totale")
            Me.columnPeso_Totale_Str = MyBase.Columns("Peso_Totale_Str")
            Me.columnTara_Veicolo = MyBase.Columns("Tara_Veicolo")
            Me.columnTara_Veicolo_Str = MyBase.Columns("Tara_Veicolo_Str")
            Me.columnPeso_Lordo = MyBase.Columns("Peso_Lordo")
            Me.columnPeso_Lordo_Str = MyBase.Columns("Peso_Lordo_Str")
            Me.columnTara_Imballi = MyBase.Columns("Tara_Imballi")
            Me.columnTara_Imballi_Str = MyBase.Columns("Tara_Imballi_Str")
            Me.columnPeso_Netto = MyBase.Columns("Peso_Netto")
            Me.columnPeso_Netto_Str = MyBase.Columns("Peso_Netto_Str")
            Me.columnDegrado_Perc = MyBase.Columns("Degrado_Perc")
            Me.columnDegrado_Perc_Str = MyBase.Columns("Degrado_Perc_Str")
            Me.columnDegrado = MyBase.Columns("Degrado")
            Me.columnDegrado_Str = MyBase.Columns("Degrado_Str")
            Me.columnNetto_Pag = MyBase.Columns("Netto_Pag")
            Me.columnNetto_Pag_Str = MyBase.Columns("Netto_Pag_Str")
            Me.columnIndice_Qualitativo = MyBase.Columns("Indice_Qualitativo")
            Me.columnPunteggio = MyBase.Columns("Punteggio")
            Me.columnCodice_Specie = MyBase.Columns("Codice_Specie")
            Me.columnDescr_Specie = MyBase.Columns("Descr_Specie")
            Me.columnCodice_Articolo = MyBase.Columns("Codice_Articolo")
            Me.columnDescr_Articolo = MyBase.Columns("Descr_Articolo")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Private Sub InitClass()
            Me.columnCodice_Conferente = New Global.System.Data.DataColumn("Codice_Conferente", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCodice_Conferente)
            Me.columnRagSoc_Conferente = New Global.System.Data.DataColumn("RagSoc_Conferente", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnRagSoc_Conferente)
            Me.columnData_Bolla = New Global.System.Data.DataColumn("Data_Bolla", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnData_Bolla)
            Me.columnNumero_Bolla = New Global.System.Data.DataColumn("Numero_Bolla", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnNumero_Bolla)
            Me.columnData_DDT = New Global.System.Data.DataColumn("Data_DDT", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnData_DDT)
            Me.columnNumero_DDT = New Global.System.Data.DataColumn("Numero_DDT", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnNumero_DDT)
            Me.columnPeso_Totale = New Global.System.Data.DataColumn("Peso_Totale", GetType(Single), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPeso_Totale)
            Me.columnPeso_Totale_Str = New Global.System.Data.DataColumn("Peso_Totale_Str", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPeso_Totale_Str)
            Me.columnTara_Veicolo = New Global.System.Data.DataColumn("Tara_Veicolo", GetType(Single), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTara_Veicolo)
            Me.columnTara_Veicolo_Str = New Global.System.Data.DataColumn("Tara_Veicolo_Str", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTara_Veicolo_Str)
            Me.columnPeso_Lordo = New Global.System.Data.DataColumn("Peso_Lordo", GetType(Single), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPeso_Lordo)
            Me.columnPeso_Lordo_Str = New Global.System.Data.DataColumn("Peso_Lordo_Str", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPeso_Lordo_Str)
            Me.columnTara_Imballi = New Global.System.Data.DataColumn("Tara_Imballi", GetType(Single), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTara_Imballi)
            Me.columnTara_Imballi_Str = New Global.System.Data.DataColumn("Tara_Imballi_Str", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTara_Imballi_Str)
            Me.columnPeso_Netto = New Global.System.Data.DataColumn("Peso_Netto", GetType(Single), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPeso_Netto)
            Me.columnPeso_Netto_Str = New Global.System.Data.DataColumn("Peso_Netto_Str", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPeso_Netto_Str)
            Me.columnDegrado_Perc = New Global.System.Data.DataColumn("Degrado_Perc", GetType(Single), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDegrado_Perc)
            Me.columnDegrado_Perc_Str = New Global.System.Data.DataColumn("Degrado_Perc_Str", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDegrado_Perc_Str)
            Me.columnDegrado = New Global.System.Data.DataColumn("Degrado", GetType(Single), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDegrado)
            Me.columnDegrado_Str = New Global.System.Data.DataColumn("Degrado_Str", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDegrado_Str)
            Me.columnNetto_Pag = New Global.System.Data.DataColumn("Netto_Pag", GetType(Single), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnNetto_Pag)
            Me.columnNetto_Pag_Str = New Global.System.Data.DataColumn("Netto_Pag_Str", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnNetto_Pag_Str)
            Me.columnIndice_Qualitativo = New Global.System.Data.DataColumn("Indice_Qualitativo", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnIndice_Qualitativo)
            Me.columnPunteggio = New Global.System.Data.DataColumn("Punteggio", GetType(Single), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPunteggio)
            Me.columnCodice_Specie = New Global.System.Data.DataColumn("Codice_Specie", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCodice_Specie)
            Me.columnDescr_Specie = New Global.System.Data.DataColumn("Descr_Specie", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDescr_Specie)
            Me.columnCodice_Articolo = New Global.System.Data.DataColumn("Codice_Articolo", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCodice_Articolo)
            Me.columnDescr_Articolo = New Global.System.Data.DataColumn("Descr_Articolo", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDescr_Articolo)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function NewDT_EC_Bolle_ConfRow() As DT_EC_Bolle_ConfRow
            Return CType(Me.NewRow,DT_EC_Bolle_ConfRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New DT_EC_Bolle_ConfRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(DT_EC_Bolle_ConfRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.DT_EC_Bolle_ConfRowChangedEvent) Is Nothing) Then
                RaiseEvent DT_EC_Bolle_ConfRowChanged(Me, New DT_EC_Bolle_ConfRowChangeEvent(CType(e.Row,DT_EC_Bolle_ConfRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.DT_EC_Bolle_ConfRowChangingEvent) Is Nothing) Then
                RaiseEvent DT_EC_Bolle_ConfRowChanging(Me, New DT_EC_Bolle_ConfRowChangeEvent(CType(e.Row,DT_EC_Bolle_ConfRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.DT_EC_Bolle_ConfRowDeletedEvent) Is Nothing) Then
                RaiseEvent DT_EC_Bolle_ConfRowDeleted(Me, New DT_EC_Bolle_ConfRowChangeEvent(CType(e.Row,DT_EC_Bolle_ConfRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.DT_EC_Bolle_ConfRowDeletingEvent) Is Nothing) Then
                RaiseEvent DT_EC_Bolle_ConfRowDeleting(Me, New DT_EC_Bolle_ConfRowChangeEvent(CType(e.Row,DT_EC_Bolle_ConfRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub RemoveDT_EC_Bolle_ConfRow(ByVal row As DT_EC_Bolle_ConfRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
            Dim ds As DS_EC_Bolle_Conf = New DS_EC_Bolle_Conf()
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "DT_EC_Bolle_ConfDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    Partial Public Class DT_EC_Bolle_ConfRow
        Inherits Global.System.Data.DataRow
        
        Private tableDT_EC_Bolle_Conf As DT_EC_Bolle_ConfDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableDT_EC_Bolle_Conf = CType(Me.Table,DT_EC_Bolle_ConfDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property Codice_Conferente() As String
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.Codice_ConferenteColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'Codice_Conferente' nella tabella 'DT_EC_Bolle_Conf' è DB"& _ 
                            "Null.", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.Codice_ConferenteColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property RagSoc_Conferente() As String
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.RagSoc_ConferenteColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'RagSoc_Conferente' nella tabella 'DT_EC_Bolle_Conf' è DB"& _ 
                            "Null.", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.RagSoc_ConferenteColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property Data_Bolla() As String
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.Data_BollaColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'Data_Bolla' nella tabella 'DT_EC_Bolle_Conf' è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.Data_BollaColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property Numero_Bolla() As String
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.Numero_BollaColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'Numero_Bolla' nella tabella 'DT_EC_Bolle_Conf' è DBNull."& _ 
                            "", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.Numero_BollaColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property Data_DDT() As String
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.Data_DDTColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'Data_DDT' nella tabella 'DT_EC_Bolle_Conf' è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.Data_DDTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property Numero_DDT() As String
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.Numero_DDTColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'Numero_DDT' nella tabella 'DT_EC_Bolle_Conf' è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.Numero_DDTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property Peso_Totale() As Single
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.Peso_TotaleColumn),Single)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'Peso_Totale' nella tabella 'DT_EC_Bolle_Conf' è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.Peso_TotaleColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property Peso_Totale_Str() As String
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.Peso_Totale_StrColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'Peso_Totale_Str' nella tabella 'DT_EC_Bolle_Conf' è DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.Peso_Totale_StrColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property Tara_Veicolo() As Single
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.Tara_VeicoloColumn),Single)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'Tara_Veicolo' nella tabella 'DT_EC_Bolle_Conf' è DBNull."& _ 
                            "", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.Tara_VeicoloColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property Tara_Veicolo_Str() As String
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.Tara_Veicolo_StrColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'Tara_Veicolo_Str' nella tabella 'DT_EC_Bolle_Conf' è DBN"& _ 
                            "ull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.Tara_Veicolo_StrColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property Peso_Lordo() As Single
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.Peso_LordoColumn),Single)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'Peso_Lordo' nella tabella 'DT_EC_Bolle_Conf' è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.Peso_LordoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property Peso_Lordo_Str() As String
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.Peso_Lordo_StrColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'Peso_Lordo_Str' nella tabella 'DT_EC_Bolle_Conf' è DBNul"& _ 
                            "l.", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.Peso_Lordo_StrColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property Tara_Imballi() As Single
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.Tara_ImballiColumn),Single)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'Tara_Imballi' nella tabella 'DT_EC_Bolle_Conf' è DBNull."& _ 
                            "", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.Tara_ImballiColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property Tara_Imballi_Str() As String
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.Tara_Imballi_StrColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'Tara_Imballi_Str' nella tabella 'DT_EC_Bolle_Conf' è DBN"& _ 
                            "ull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.Tara_Imballi_StrColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property Peso_Netto() As Single
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.Peso_NettoColumn),Single)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'Peso_Netto' nella tabella 'DT_EC_Bolle_Conf' è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.Peso_NettoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property Peso_Netto_Str() As String
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.Peso_Netto_StrColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'Peso_Netto_Str' nella tabella 'DT_EC_Bolle_Conf' è DBNul"& _ 
                            "l.", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.Peso_Netto_StrColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property Degrado_Perc() As Single
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.Degrado_PercColumn),Single)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'Degrado_Perc' nella tabella 'DT_EC_Bolle_Conf' è DBNull."& _ 
                            "", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.Degrado_PercColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property Degrado_Perc_Str() As String
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.Degrado_Perc_StrColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'Degrado_Perc_Str' nella tabella 'DT_EC_Bolle_Conf' è DBN"& _ 
                            "ull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.Degrado_Perc_StrColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property Degrado() As Single
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.DegradoColumn),Single)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'Degrado' nella tabella 'DT_EC_Bolle_Conf' è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.DegradoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property Degrado_Str() As String
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.Degrado_StrColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'Degrado_Str' nella tabella 'DT_EC_Bolle_Conf' è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.Degrado_StrColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property Netto_Pag() As Single
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.Netto_PagColumn),Single)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'Netto_Pag' nella tabella 'DT_EC_Bolle_Conf' è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.Netto_PagColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property Netto_Pag_Str() As String
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.Netto_Pag_StrColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'Netto_Pag_Str' nella tabella 'DT_EC_Bolle_Conf' è DBNull"& _ 
                            ".", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.Netto_Pag_StrColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property Indice_Qualitativo() As String
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.Indice_QualitativoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'Indice_Qualitativo' nella tabella 'DT_EC_Bolle_Conf' è D"& _ 
                            "BNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.Indice_QualitativoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property Punteggio() As Single
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.PunteggioColumn),Single)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'Punteggio' nella tabella 'DT_EC_Bolle_Conf' è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.PunteggioColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property Codice_Specie() As String
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.Codice_SpecieColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'Codice_Specie' nella tabella 'DT_EC_Bolle_Conf' è DBNull"& _ 
                            ".", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.Codice_SpecieColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property Descr_Specie() As String
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.Descr_SpecieColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'Descr_Specie' nella tabella 'DT_EC_Bolle_Conf' è DBNull."& _ 
                            "", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.Descr_SpecieColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property Codice_Articolo() As String
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.Codice_ArticoloColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'Codice_Articolo' nella tabella 'DT_EC_Bolle_Conf' è DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.Codice_ArticoloColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property Descr_Articolo() As String
            Get
                Try 
                    Return CType(Me(Me.tableDT_EC_Bolle_Conf.Descr_ArticoloColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("Il valore della colonna 'Descr_Articolo' nella tabella 'DT_EC_Bolle_Conf' è DBNul"& _ 
                            "l.", e)
                End Try
            End Get
            Set
                Me(Me.tableDT_EC_Bolle_Conf.Descr_ArticoloColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsCodice_ConferenteNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.Codice_ConferenteColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetCodice_ConferenteNull()
            Me(Me.tableDT_EC_Bolle_Conf.Codice_ConferenteColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsRagSoc_ConferenteNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.RagSoc_ConferenteColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetRagSoc_ConferenteNull()
            Me(Me.tableDT_EC_Bolle_Conf.RagSoc_ConferenteColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsData_BollaNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.Data_BollaColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetData_BollaNull()
            Me(Me.tableDT_EC_Bolle_Conf.Data_BollaColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsNumero_BollaNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.Numero_BollaColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetNumero_BollaNull()
            Me(Me.tableDT_EC_Bolle_Conf.Numero_BollaColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsData_DDTNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.Data_DDTColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetData_DDTNull()
            Me(Me.tableDT_EC_Bolle_Conf.Data_DDTColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsNumero_DDTNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.Numero_DDTColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetNumero_DDTNull()
            Me(Me.tableDT_EC_Bolle_Conf.Numero_DDTColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsPeso_TotaleNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.Peso_TotaleColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetPeso_TotaleNull()
            Me(Me.tableDT_EC_Bolle_Conf.Peso_TotaleColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsPeso_Totale_StrNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.Peso_Totale_StrColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetPeso_Totale_StrNull()
            Me(Me.tableDT_EC_Bolle_Conf.Peso_Totale_StrColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsTara_VeicoloNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.Tara_VeicoloColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetTara_VeicoloNull()
            Me(Me.tableDT_EC_Bolle_Conf.Tara_VeicoloColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsTara_Veicolo_StrNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.Tara_Veicolo_StrColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetTara_Veicolo_StrNull()
            Me(Me.tableDT_EC_Bolle_Conf.Tara_Veicolo_StrColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsPeso_LordoNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.Peso_LordoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetPeso_LordoNull()
            Me(Me.tableDT_EC_Bolle_Conf.Peso_LordoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsPeso_Lordo_StrNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.Peso_Lordo_StrColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetPeso_Lordo_StrNull()
            Me(Me.tableDT_EC_Bolle_Conf.Peso_Lordo_StrColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsTara_ImballiNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.Tara_ImballiColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetTara_ImballiNull()
            Me(Me.tableDT_EC_Bolle_Conf.Tara_ImballiColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsTara_Imballi_StrNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.Tara_Imballi_StrColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetTara_Imballi_StrNull()
            Me(Me.tableDT_EC_Bolle_Conf.Tara_Imballi_StrColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsPeso_NettoNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.Peso_NettoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetPeso_NettoNull()
            Me(Me.tableDT_EC_Bolle_Conf.Peso_NettoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsPeso_Netto_StrNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.Peso_Netto_StrColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetPeso_Netto_StrNull()
            Me(Me.tableDT_EC_Bolle_Conf.Peso_Netto_StrColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsDegrado_PercNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.Degrado_PercColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetDegrado_PercNull()
            Me(Me.tableDT_EC_Bolle_Conf.Degrado_PercColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsDegrado_Perc_StrNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.Degrado_Perc_StrColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetDegrado_Perc_StrNull()
            Me(Me.tableDT_EC_Bolle_Conf.Degrado_Perc_StrColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsDegradoNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.DegradoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetDegradoNull()
            Me(Me.tableDT_EC_Bolle_Conf.DegradoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsDegrado_StrNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.Degrado_StrColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetDegrado_StrNull()
            Me(Me.tableDT_EC_Bolle_Conf.Degrado_StrColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsNetto_PagNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.Netto_PagColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetNetto_PagNull()
            Me(Me.tableDT_EC_Bolle_Conf.Netto_PagColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsNetto_Pag_StrNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.Netto_Pag_StrColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetNetto_Pag_StrNull()
            Me(Me.tableDT_EC_Bolle_Conf.Netto_Pag_StrColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsIndice_QualitativoNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.Indice_QualitativoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetIndice_QualitativoNull()
            Me(Me.tableDT_EC_Bolle_Conf.Indice_QualitativoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsPunteggioNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.PunteggioColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetPunteggioNull()
            Me(Me.tableDT_EC_Bolle_Conf.PunteggioColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsCodice_SpecieNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.Codice_SpecieColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetCodice_SpecieNull()
            Me(Me.tableDT_EC_Bolle_Conf.Codice_SpecieColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsDescr_SpecieNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.Descr_SpecieColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetDescr_SpecieNull()
            Me(Me.tableDT_EC_Bolle_Conf.Descr_SpecieColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsCodice_ArticoloNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.Codice_ArticoloColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetCodice_ArticoloNull()
            Me(Me.tableDT_EC_Bolle_Conf.Codice_ArticoloColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsDescr_ArticoloNull() As Boolean
            Return Me.IsNull(Me.tableDT_EC_Bolle_Conf.Descr_ArticoloColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetDescr_ArticoloNull()
            Me(Me.tableDT_EC_Bolle_Conf.Descr_ArticoloColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Public Class DT_EC_Bolle_ConfRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As DT_EC_Bolle_ConfRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub New(ByVal row As DT_EC_Bolle_ConfRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Row() As DT_EC_Bolle_ConfRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
