export enum enum_Impostazioni_Utenti {

  //CODICI IMPOSTAZIONE UTENTI
  //documentazione su: \\rubino2\DOCUMENTAZIONE\GIAS --- Utenti\Utenti_Impostazioni.docx

  //SUPERUSER
  SUPERUSER_COD_DISTRIBUZIONE_ACQUA = 1,
  SUPERUSER_COD_IMPIANTO_DISTINTA = 2,
  SUPERUSER_COD_BLOCCO_PARTICELLE = 10,
  SUPERUSER_COD_ANALISI_COSTI = 12,

  SUPERUSER_DEFAULT_NOTE_CAMPIONI = 57,
  SUPERUSER_Codice_Campione_Progressivo_Inizio_Anno = 62,
  SUPERUSER_Label_Codice_Campione = 63,

  SUPERUSER_Blocca_Impianti_Smart = 73,
  SUPERUSER_Smart_NuovoImpianto_OrganismoReferente = 74,
  SUPERUSER_Smart_NuovoImpianto_DestinazioneUso = 75,
  SUPERUSER_Smart_NuovaImpresa_ImpresaPadre = 76,
  SUPERUSER_Smart_NuovoImpianto_DefaultOrganismoReferente = 77,

  SUPERUSER_Label_Codice_Analisi = 84,
  SUPERUSER_Label_Codice_Griglia = 85,
  SUPERUSER_Stampa_Rapida_WorkFlow = 87,
  SUPERUSER_Codice_Campione_Zani = 92,
  SUPERUSER_Codice_Campione_TERREMERSE = 98,
  SUPERUSER_ComportamentoComboFF = 104,
  SUPERUSER_GESTIONE_MAGAZZINO_ABILITATA = 208,
  SuperUser_FiltroSQL_MateriePrime = 187,
  SuperUser_Gestione_Esercizi = 188,
  SuperUser_Albero_Anagrafiche = 190,
  SuperUser_Ereditatore = 192,
  SuperUser_KPIN_BlockName = 193,
  SuperUser_Visualizza_Codici_Anagrafici = 194,
  SuperUser_Impostazioni_PDC = 198,
  SuperUser_Gestione_PDC_Analisi = 199,
  SUPERUSER_NuovoImpianto_DefaultTecnico = 216,

  SUPERUSER_COD_FILE_IMPORTAZIONE_DATI = 500,
  SUPERUSER_COD_FILE_ESPORTAZIONE_DATI = 501,
  SUPERUSER_COD_FILE_ESPORTAZIONE_DATI_2 = 502,
  SUPERUSER_COD_IP_BILANCIA = 600,
  SUPERUSER_COD_TARA_BILANCIA = 601,
  SUPERUSER_COD_FILTRO_MATERIE_PRIME = 666,
  SUPERUSER_COD_COOP_REFERENTE_OBBLIGATORIA = 670,
  SUPERUSER_COD_ORG_REFERENTE_OBBLIGATORIO = 670,
  SUPERUSER_COD_ORG_REFERENTE_DA_PADRE = 671,
  SUPERUSER_COD_IMPOSTAZIONE_IMBALLAGGI = 700,
  SUPERUSER_COD_IMPOSTAZIONE_CONTENITORI = 701,
  SUPERUSER_COD_CONTABILITA_MULTIPLA = 710,
  SUPERUSER_COD_IVA_DEFAULT = 712,
  SUPERUSER_COD_CAUSALE_TRASPORTO_DEFAULT = 713,
  SUPERUSER_COD_NOTE_DEFAULT_BOLLA_EMESSA = 714,
  SUPERUSER_COD_NOTE_DEFAULT_FATTURA_EMESSA = 715,
  SUPERUSER_COD_LISTINI_PRODUZIONE = 720,
  UTENTE_RapportoContabileDefault = 722,
  SUPERUSER_COD_MODALITA_TRASPORTO_DEFAULT = 723,
  SUPERUSER_COD_Aspetto_Beni_Default = 724,
  SuperUser_LayOut_Peso_DDT = 727,
  SuperUser_LayOut_Prezzo_DDT = 728,
  SuperUser_LayOut_Riscontrato_DDT = 729,
  SUPERUSER_COD_GESTIONE_AGENTI = 734,
  SUPERUSER_COD_GESTIONE_SEZIONALI = 746,
  SUPERUSER_COD_GEST_AUTO_CONSISTENZE_ENOLOGICHE = 750,
  SUPERUSER_COD_ZONA_VITICOLA = 751,
  SUPERUSER_COD_GESTIONE_REG_VINIFICAZIONE = 756,
  SuperUser_StampaCapacitaEffettivaVascaRegCantina = 757,
  SuperUser_StampaIndentificativoVascaRegCantina = 758,

  SUPERUSER_COD_VISUAL_CODARTICOLO_DOCUMENTI = 764,

  SuperUser_ContributoConai = 766,
  SUPERUSER_COD_PERMETTI_OPERAZIONI_SU_IMPIANTI_BLOCCATI = 767,
  SUPERUSER_COD_PERMETTI_MODIFICA_RICETTE_CON_OPERAZIONI_REGISTRATE = 768,
  SuperUser_NoteIntegrative1DDT = 770,
  SuperUser_NoteIntegrative2DDT = 771,
  SuperUser_NoteIntegrative3DDT = 772,
  SuperUser_Articolo62DDT = 773,
  SuperUser_NoteIntegrative1DDTCorrispettivi = 774,
  SuperUser_NoteIntegrative2DDTCorrispettivi = 775,
  SuperUser_NoteIntegrative3DDTCorrispettivi = 776,
  SuperUser_Articolo62DDTCorrispettivi = 777,
  SuperUser_NoteIntegrative1Ordini = 778,
  SuperUser_NoteIntegrative2Ordini = 779,
  SuperUser_NoteIntegrative3Ordini = 780,
  SuperUser_Articolo62Ordini = 781,
  SuperUser_NoteIntegrative1Fatture = 782,
  SuperUser_NoteIntegrative2Fatture = 783,
  SuperUser_NoteIntegrative3Fatture = 784,
  SuperUser_Articolo62Fatture = 785,
  SuperUser_GestioneVisualNumVascaRegImbott = 791,
  SUPERUSER_COD_TIPO_DOC_ACCETTAZIONE_DEFAULT = 795,
  SUPERUSER_COD_CHKCOGE_MANUALE_DEFAULT = 797,
  SuperUser_StampaLottoTrasformazioneRegCantina = 801,
  SUPERUSER_COD_GESTIONE_CAPOAREA = 807,
  SuperUser_ApriFiltroFattura = 810,
  SuperUser_ApriFiltroDDT = 811,
  SuperUser_StPersDDTAccetta = 812,
  SuperUser_StRifOrdine = 813,
  SUPERUSER_COD_ALGORITMO_COSTI_ACCESSORI = 814,
  SUPERUSER_COD_SQPNI_FILTROSPECIE = 815,
  SUPERUSER_COD_SQPNI_FILTROMACRO_USI = 816,
  SUPERUSER_COD_SQPNI_FILTRODESTINAZIONE_USO = 817,

  SUPERUSER_COD_PERSON_RILIEVO_FASI_FENOLOGICHE = 819,
  SUPERUSER_COD_PERSON_RILIEVO_AVVERSITA = 820,
  SUPERUSER_COD_PERSON_RILIEVO_ERBE_INFESTANTI = 821,
  SUPERUSER_COD_PERSON_RILIEVO_INDICI_MATURITA = 822,
  SUPERUSER_COD_PERSON_RILIEVO_INDICI_RESE_RACCOLTA = 832,
  SUPERUSER_COD_PERSON_RILIEVO_DANNI_ALLA_RACCOLTA = 833,

  SUPERUSER_COD_TOLLERANZA_PESO_GIACENZE_DISTINTA = 825,
  SUPERUSER_COD_NUOVA_MODALITA_ARROTONDAMENTO_LAN = 826,

  SUPERUSER_GiasAPP_NUOVA_RICETTA = 827,
  SUPERUSER_GiasAPP_NUOVO_INTERVENTO = 828,
  SUPERUSER_GiasAPP_INTERVENTI_DA_FARE = 829,
  SUPERUSER_GiasAPP_SCARICO_ORE = 830,
  SUPERUSER_UTILIZZO_ORARI_INIZIO_FINE = 831,

  SUPERUSER_COD_RICETTE_CREA_UNA_OPERAZIONE_PER_OGNI_IMPIANTO = 834,
  SUPERUSER_GiasAPP_MAX_AZIENDE = 835,
  SUPERUSER_ArrotondamentoIVA4Dec_DataAttivazione = 836,
  SUPERUSER_Consenti_ContattoCod_Duplicato = 838,
  SUPERUSER_PRODOTTOCOD_MAX_LENGTH = 839,
  SUPERUSER_ContattoCod_Max_Lenght = 840,
  SUPERUSER_StampaAlcolTotale = 841,
  SUPERUSER_ConsentiNumDocDuplicati = 842,
  SUPERUSER_JoinCacPivaSuperUser = 843,

  SUPERUSER_SoloLottiDisponibiliInOrdineVendita = 844,
  SUPERUSER_PrezzoNulloInListino = 845,
  SUPERUSER_TipoValorizzazioneCostiCdG = 846,
  SUPERUSER_Applica_Listini_Non_Associati = 847,

  SUPERUSER_FF_GEST_MATERIALE_VIVAISTICO = 848,
  SUPERUSER_DOCUMENTALE_SALVA_ALLEGATO_SU_DB = 849,

  SUPERUSER_GiasAPP_ENTRATAUSCITA = 850,
  SUPERUSER_GiasAPP_LAMIAPOSIZIONE = 851,
  SUPERUSER_GiasAPP_VISITE = 852,
  SUPERUSER_GiasAPP_FREQUENZARILIEVO_MINUTI = 853,
  SUPERUSER_GiasAPP_FREQUENZASINCRO_MINUTI = 854,
  SUPERUSER_Licenza_Giorni_Franchigia = 855,

  SUPERUSER_Livello_Applicazione_Listini = 857,
  SUPERUSER_GiasAPP_IMPOSTAZIONI = 860,
  SUPERUSER_GiasAPP_DOCUMENTI = 861,
  SUPERUSER_GiasAPP_RILIEVI = 862,
  SUPERUSER_GiasAPP_GIS = 863,
  SUPERUSER_GiasAPP_InCab = 864,
  SUPERUSER_Conferimento_Ripartizione_Impianti = 865,
  SUPERUSER_Conferimento_Ripartizione_Obbligatoria = 866,
  SUPERUSER_GiasAPP_Permessi = 867,
  SUPERUSER_Mod_Ricerca_Impresa = 868,
  Operazioni_Contab_Collegate_QdC = 888,
  SUPERUSER_IMPEDISCI_INS_MOD_BROGLIACCIO = 889,
  SUPERUSER_IMPEDISCI_ELIMINAZIONE_CONTATTI_E_RISORSE_UMANE = 886,
  UTENTE_COD_PREFERITI_REPORT_PIANO_COLTURALE_CATASTO_GRID = 890,
  SUPERUSER_Mod_Filtro_Ricerca = 891,
  SUPERUSER_Mod_Analisi_Terreno = 892,

  SUPERUSER_NuovaAzienda_ProprietaContatti = 897,
  SUPERUSER_NuovaAzienda_ContattiPubblici = 898,
  SUPERUSER_NuovaAzienda_DefaultRappContabile = 903,

  SUPERUSER_EDIT_LOTTO = 990,
  SUPERUSER_OPERATORE_ACCETTAZIONE = 998,
  SUPERUSER_Consenti_ProdottoCod_Duplicato = 999,

  SuperUser_StampaLitriDDTFatture = 1050,
  SuperUser_CessionariAggiuntivi = 1051,
  SuperUser_RifDoc_EnteConsorzio = 1052,
  SuperUser_PesiColli_Riscontrati = 1053,
  SuperUser_TipoDestinazione_Default = 1054,

  SUPERUSER_LIVELLO_GESTIONE_CONTABILITA = 1058,
  SUPERUSER_ACCETTAZIONE_CON_GERARCHIA = 1059,
  SUPERUSER_DocContabili_SceltaImputazione = 1061,
  IMPRESA_DocContabili_Cod_Tipo_Imputazione = 1062,
  Raccolta_Con_Carico_Magazzino = 1065, // Livelli: SUPERUSER, IMPRESA
  SUPERUSER_Creazione_Prodotti = 1081,
  SUPERUSER_NR_ORE_VISITA = 1084,
  SUPERUSER_ZOO_IN_VISITA = 1088,
  SUPERUSER_STATO_VISITA = 1089,
  SUPERUSER_SETUP_GIS = 1090,
  SUPERUSER_CARICO_ZOO_GRIGLIA = 1091,
  /** Visibilità: Superuser, Impresa */
  SUPERUSER_ELABORAZIONE_DSS_DA_IMPIANTI = 1093,
  SUPERUSER_ELABORAZIONE_DSS_FORECAST = 1095,
  RICERCA_CON_FILTRO_CESSIONARIO_DOC_CONT = 1099,

  SUPERUSER_COD_IMPORTAZIONE_AGREA = 3001,
  SUPERUSER_COD_IMPORTAZIONE_ANAGRAFEEMILIAROMAGNA = 3002,
  SUPERUSER_COD_IMPORTAZIONE_AVEPA = 3003,

  SUPERUSER_CALO_PESO_DEFAULT_CONTATTO = 1101,
  SUPERUSER_COD_REGISTRA_ALIMENTAZIONE_DATA_SINGOLA_ZOO = 1102,


  ////UTENTE
  UTENTE_COD_FILTRO_GRUPPI_VEGETALI = 3,
  UTENTE_COD_FILTRO_VARIETA = 4,
  UTENTE_COD_DEFAULT_SINGOLE_GRUPPI_AVVERSITA = 5,  //valore: 88=gruppi 77=singole
  UTENTE_COD_FILTRO_SPECIE_VEGETALI = 6,
  UTENTE_COD_FILTRO_LAVORAZIONI = 7,
  UTENTE_COD_FILTRO_GRUPPI_OPERAZIONI = 8,
  UTENTE_COD_MAGAZZINO_RIFERIMENTO = 9,
  UTENTE_COD_DEFAULT_SINGOLE_GRUPPI_INFESTANTI = 11,   //valore: 88=gruppi 77=singole
  UTENTE_COD_DEFAULT_DPI = 13,   //valore: 0=nessun DPI 1=con DPI
  UTENTE_COD_DEFAULT_BLOCCO_SALVA_NOCONFORME = 14,   //valore: 0=nessun blocco 1=blocco salvataggio
  UTENTE_COD_DEFAULT_QTA_PRODOTTO = 15,   //valore: 88=totale 77=ettaro
  UTENTE_COD_DEFAULT_QTA_ACQUA = 16,      //valore: 88=totale 77=ettaro
  UTENTE_COD_DEFAULT_GESTIONE_MAGAZZINO = 18,     //0=nessun magazzino  1=con magazzino
  UTENTE_COD_DEFAULT_FILTRO_PRODOTTI = 19,     //0 = nessuno - 1 = coltura - 2 = coltura/ avversità/ infestante

  UTENTE_COD_DEFAULT_FILTRO_PRODOTTI_RICETTE = 176,     //0 = nessuno - 1 = coltura - 2 = coltura/ avversità/ infestante

  UTENTE_COD_ColonneVisibili_TabellaImpianti_Semina = 24,
  UTENTE_COD_ColonneVisibili_TabellaImpiantiAgenda = 26,
  UTENTE_COD_ColonneVisibili_PAN_PianoColturale = 57,
  UTENTE_COD_FILTRO_STAMPA_RICETTA_NUMERO_RICETTA = 27,
  UTENTE_COD_FILTRO_STAMPA_RICETTA_MACCHINE = 28,
  UTENTE_COD_FILTRO_STAMPA_RICETTA_OPERATORI = 29,
  UTENTE_COD_FILTRO_STAMPA_RICETTA_TECNICO_AUTORIZZANTE = 30,
  UTENTE_COD_FILTRO_STAMPA_RICETTA_FIRMA_AGRICOLTORE = 31,
  UTENTE_COD_FILTRO_STAMPA_RICETTA_DATA_ULTIMA_MANUTENZIONE = 44,

  UTENTE_COD_FILTRO_STAMPA_SCHEDA_CAMPAGNA_ARROTONDA_ACQUA = 32,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_CAMPAGNA_MACCHINE = 33,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_CAMPAGNA_OPERATORI = 34,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_CAMPAGNA_TECNICO_AUTORIZZANTE = 35,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_CAMPAGNA_DATA_FIRMA = 36,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_CAMPAGNA_NUMERO_RICETTA = 42,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_CAMPAGNA_DATA_ULTIMA_MANUTENZIONE = 45,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_CAMPAGNA_FASE_EPOCA_ETICHETTA = 117,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_CAMPAGNA_FILTRA_FASCICOLO = 112,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_CAMPAGNA_VISUALCAMPO_SOLOFRONTESPIZIO = 177,

  UTENTE_COD_SCHEDA_CAMPAGNA_NUM_APPEZZAMENTO = 109,

  UTENTE_COD_FILTRO_STAMPA_SCHEDA_GLOBAL_ARROTONDA_ACQUA = 37,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_GLOBAL_MACCHINE = 38,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_GLOBAL_OPERATORI = 39,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_GLOBAL_TECNICO_AUTORIZZANTE = 40,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_GLOBAL_DATA_FIRMA = 41,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_GLOBAL_NUMERO_RICETTA = 43,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_GLOBAL_DATA_ULTIMA_MANUTENZIONE = 46,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_GLOBAL_FASE_EPOCA_ETICHETTA = 118,

  //blocchi di etichetta inserimento
  UTENTE_COD_BLOCCA_DOSEMASSIMA_ETICHETTA = 47,
  UTENTE_COD_BLOCCA_DOSEMINIMA_ETICHETTA = 48,
  UTENTE_COD_BLOCCA_ACQUAMASSIMA_ETICHETTA = 49,
  UTENTE_COD_BLOCCA_ACQUAMINIMA_ETICHETTA = 50,
  UTENTE_COD_BLOCCA_NUMERO_MASSIMO_TRATTAMENTI_ETICHETTA = 51,
  UTENTE_COD_BLOCCA_FINO_FIORITURA_ETICHETTA = 52,
  UTENTE_COD_BLOCCA_CARENZA_NON_RISPETTATA = 53,
  UTENTE_COD_BLOCCA_BUFFERZONE_ETICHETTA = 169,

  //Livello di Controllo del DPI --> 1 livello base 2 livello avanzato
  UTENTE_COD_LIVELLO_CHK_DPI = 54,
  UTENTE_COD_TUTTI_I_CENTRI = 55,
  UTENTE_COD_CHILI_LITRI = 56,

  UTENTE_MODALITA_NERO = 58,

  UTENTE_GESTIONE_MAGAZZINO_2 = 59,    //0=nessuna gestione  1= carica magazzini super user 2= carica magazzini impresa padre

  UTENTE_OPERAZIONI_QDC_PREFERITE = 60, //Lav_cod separati da |

  UTENTE_COD_ColonneVisibili_Planning = 61,
  UTENTE_COD_ColParticelleVisibili_Planning = 91,

  UTENTE_NumAppezza_Progr_Modalita = 64,
  UTENTE_MultiModificaImpianti_FiltroProprieta = 65,

  UTENTE_COD_ColonneVisibili_PDC_da_campagna = 66,
  UTENTE_COD_ColonneVisibili_PDC_acquisti = 67,

  UTENTE_COD_DEFAULT_DPI_PREDEFINITO = 68,   //valore: es 34/1 emilia romagna 2012

  UTENTE_COD_DEFAULT_RiferimentoRicetteOperazioni = 69, //0= non salva il riferimento in ricettaxagenda, 1 o non impostato= salva il riferimento

  UTENTE_StampaPDF_RicFiscali_ConSenzaPreview = 70, //0= con preview,1=senza preview

  UTENTE_OPERAZIONI_TIPI_GRUPPI_OPERAZIONI_VISIBILI_MENU_AGENDA = 71, //Tipo gruppo separati da | (E,P,C,Z,E6,E10) tipo E separato in E6, E!= per magazzino e contabili))

  UTENTE_Nome_Stampante_Ricevuta_A5 = 72, //Tipo gruppo separati da | (E,P,C,Z,E6,E10) tipo E separato in E6, E!= per magazzino e contabili))

  UTENTE_COD_FILTRO_STAMPA_RICETTA_ARROTONDA_ACQUA = 78,

  UTENTE_AlberoAnagrafica_visualizzaRiferimentoAlfanumericoImpianto = 79,

  UTENTE_AlberoAnagrafica_ordinaDataUltimoImpianto = 80,

  UTENTE_COD_BLOCCA_SE_SENZA_MAGAZZINO = 81,
  UTENTE_COD_BLOCCA_SE_SUPERA_GIACENZE = 82,
  UTENTE_COD_BLOCCA_SE_SENZA_DISCIPLINARE = 168,
  UTENTE_COD_BLOCCA_SE_DATA_FATTURA_SUPERA_ALLEGATI = 83,

  UTENTE_COD_ColonneVisibili_PDC_AltreAnalisi = 86,

  UTENTE_LINK_PREFERITE = 88,
  UTENTE_LINK_PREFERITE_MENUBS2017 = 171,

  UTENTE_COD_AZIENDA_PREDEFINITA_ALL_AVVIO = 182,

  UTENTE_LINK_PREFERITE_MENU_ONLINE = 119,

  //CATEGORIE MAGAZZINO
  UTENTE_COD_CATEGORIAMAGAZZINO_DEFAULT = 711,
  UTENTE_COD_CATEGORIAMAGAZZINO_COSTI_DEFAULT = 721,
  UTENTE_COD_FILTRO_CATEGORIAMAGAZZINO = 89,   //Elem_cod separati da |
  UTENTE_COD_FILTRO_CATEGORIAMAGAZZINO_UDM_DEFAULT = 90,   //Elem_cod_Udm_Cod separati da |
  UTENTE_COD_FILTRO_CATEGORIAMAGAZZINO_GIACENZE = 180,   //Elem_cod_Valore separati da |
  UTENTE_COD_FILTRO_CATEGORIAMAGAZZINO_LOTTI = 181,   //Elem_cod_Valore separati da |
  UTENTE_COD_FILTRO_CATEGORIAMAGAZZINO_GIACENZE_APP = 183,   //Per APP Elem_cod_Valore separati da |

  UTENTE_COD_BLOCCA_SE_SUPERA_LIMITIMAS = 93,  // Blocca se vengono superati i limiti di azoto, fosforo, potassio e magnesio dell//impianto

  UTENTE_COD_DEFAULT_ProdottiTossiciPatentinoMovimenti = 94, //0= permetti 1:avvisa 2: blocca

  UTENTE_COD_BLOCCA_INTERVALLOTRATTAMENTI_ETICHETTA = 95,

  UTENTE_Menu_Agenda_Selezione_Tipo_Operazioni = 96,
  UTENTE_Menu_Agenda_Selezione_GruppoOperazioni = 97,

  UTENTE_COD_ColonneVisibili_Analisi_PDC = 99,

  // Nitrati Piano di concimazione
  UTENTE_Nitrati_PC_Analisi = 100,     //Analisi_Entita_Cod separati da |

  UTENTE_STAMPE_PREFERITE = 101, //cod_report, enum_CodificaStampe, tabella StampeReport  separati da |

  UTENTE_Nitrati_RegolamentoPC_Default = 102,

  UTENTE_FILTRONE_PDC = 103,

  UTENTE_InizioFineAnnataAgraria = 105,

  UTENTE_Planning_Date = 106,
  UTENTE_Planning_NValidazioneNome = 107,
  UTENTE_Ribaltamento_CreaCampi = 108,

  UTENTE_COD_UTILIZZA_SUP_APP_AGENDA = 151,

  UTENTE_COD_RACCOLTA_TIPO = 110,
  UTENTE_COD_RACCOLTA_TIPOLOGIA_PRODOTTO = 111,

  UTENTE_TABACCO_EXPORT_ALL = 113,
  UTENTE_TABACCO_EXPORT_APPEZZA = 114,
  UTENTE_TABACCO_EXPORT_CORONA = 115,
  UTENTE_TABACCO_EXPORT_GRADO = 116,
  UTENTE_TABACCO_EXPORT_BUCHI = 121,

  UTENTE_Attiva_Configurazione_Pratica = 172,

  UTENTE_COD_BLOCCA_RACCOLTA_CARENZA_NON_RISPETTATA = 120,

  UTENTE_COD_BLOCCA_SEMINA_SE_SENZA_QTA = 122,

  //blocchi  etichetta/dpi salvataggio
  UTENTE_COD_DEFAULT_BLOCCO_INSERIMENTO_NONCONFORME = 125,

  UTENTE_COD_BLOCCA_DOSEMASSIMA_ETICHETTA_SALVATAGGIO = 126,
  UTENTE_COD_BLOCCA_DOSEMINIMA_ETICHETTA_SALVATAGGIO = 127,
  UTENTE_COD_BLOCCA_ACQUAMASSIMA_ETICHETTA_SALVATAGGIO = 128,
  UTENTE_COD_BLOCCA_ACQUAMINIMA_ETICHETTA_SALVATAGGIO = 129,
  UTENTE_COD_BLOCCA_NUMERO_MASSIMO_TRATTAMENTI_ETICHETTA_SALVATAGGIO = 130,
  UTENTE_COD_BLOCCA_FINO_FIORITURA_ETICHETTA_SALVATAGGIO = 131,
  UTENTE_COD_BLOCCA_CARENZA_NON_RISPETTATA_SALVATAGGIO = 132,
  UTENTE_COD_BLOCCA_INTERVALLOTRATTAMENTI_ETICHETTA_SALVATAGGIO = 133,

  UTENTE_COD_BLOCCA_AVVERSITANODPI_SALVATAGGIO = 134,
  UTENTE_COD_BLOCCA_PRODOTTONOAVVERSITA_SALVATAGGIO = 135,

  UTENTE_COD_BLOCCA_DOSENONDISPONIBILE_SALVATAGGIO = 136,
  UTENTE_COD_BLOCCA_DOSEUDMNONCONFORME_SALVATAGGIO = 137,
  UTENTE_COD_BLOCCA_DATADPIMIN_SALVATAGGIO = 138,
  UTENTE_COD_BLOCCA_DATADPIMAX_SALVATAGGIO = 139,
  UTENTE_COD_BLOCCA_IMPIANTINONCOERENTIDPI_SALVATAGGIO = 140,

  UTENTE_COD_BLOCCA_DOSEDPIDISERBOMAX_SALVATAGGIO = 141,
  UTENTE_COD_BLOCCA_DOSEDPIDISERBOANNOMAX_SALVATAGGIO = 142,

  UTENTE_COD_BLOCCA_NUMERO_MASSIMO_TRATTAMENTI_DPI_SALVATAGGIO = 143,
  UTENTE_COD_BLOCCA_NUMERO_MINIMO_TRATTAMENTI_DPI_SALVATAGGIO = 174,

  UTENTE_COD_BLOCCA_DOSERAMEANNOMAX_SALVATAGGIO = 144,
  UTENTE_COD_BLOCCA_DOSERAME5ANNIMAX_SALVATAGGIO = 145,

  UTENTE_COD_BLOCCA_EPOCADPINONCONFORME_SALVATAGGIO = 146,

  UTENTE_COD_BLOCCA_BUFFERZONE_ETICHETTA_SALVATAGGIO = 170,

  UTENTE_COD_DEFAULT_BLOCCO_INSERIMENTO_NOTE = 163,
  UTENTE_COD_DEFAULT_BLOCCO_INSERIMENTO_MACCHINE = 164,
  UTENTE_COD_DEFAULT_BLOCCO_INSERIMENTO_OPERATORE = 165,

  UTENTE_COD_BLOCCA_ACQUAMASSIMA_DPI_SALVATAGGIO = 173,

  UTENTE_COD_BLOCCA_DOSEMASSIMA_ANNO_ETICHETTA_SALVATAGGIO = 206,
  UTENTE_COD_BLOCCA_DOSEMASSIMA_ANNO_AVVERSITA_ETICHETTA_SALVATAGGIO = 207,

  // Impostazioni Campagna e GLobal
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_CAMPAGNA_CODICE_PRODUTTORE = 147,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_CAMPAGNA_TECNICO_RIFERIMENTO = 148,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_GLOBAL_CODICE_PRODUTTORE = 149,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_GLOBAL_TECNICO_RIFERIMENTO = 150,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_CAMPAGNA_DOSE_ETICHETTA = 161,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_GLOBAL_DOSE_ETICHETTA = 162,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_GLOBAL_NASCONDI_CAMPO = 166,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_CAMPAGNA_NASCONDI_CAMPO = 167,

  ////impostazioni BIO
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_BIO_MACCHINE = 152,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_BIO_OPERATORI = 153,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_BIO_TECNICO_AUTORIZZANTE = 154,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_BIO_DATA_FIRMA = 155,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_BIO_DATA_ULTIMA_MANUTENZIONE = 156,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_BIO_CAMPO = 157,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_BIO_NUM_APPEZZAMENTO = 158,
  UTENTE_COD_FILTRO_STAMPA_SCHEDA_BIO_NUM_APPEZZAMENTO_BIO = 159,
  UTENTE_COD_SCHEDA_CAMPAGNA_BIO_NUM_APPEZZAMENTO = 160,

  UTENTE_COD_FILTRO_STAMPA_PIANOCONCIMAZIONE_CAMPAGNA_DATA_FIRMA = 205,

  UTENTE_COD_SEMINA_TIPO = 175,

  UTENTE_WS_SCARICO_FASCICOLO = 178, //enum_WS_Esterni separati da |
  UTENTE_PRATICHE_DA_ATTIVARE_SCARICO_FASCICOLO = 179, //servizi separati da |

  UTENTE_WS_GESIONE_AZIENDE = 189,

  UTENTE_COD_FORMULATI_STATO = 184,

  Utente_SchedaColtBio_VisualizzaLottoSemine = 185,
  Utente_SchedaColtBio_VisualizzaLottoRaccolte = 186,

  UTENTE_GESTORE_AZIENDE = 191,

  Codice_Univoco_Appezzamento = 195,
  Codice_Univoco_Impianto = 196,
  Codice_Univoco_Progetto = 197,

  Utente_Lingua_Stampa = 200,

  UTENTE_COD_FINALITA = 201,
  UTENTE_COD_REGOLAMENTO = 202,
  UTENTE_NUOVA_PARTICELLA = 203,
  UTENTE_COD_RACCOLTA_TIPO_NUOVO_IMPIANTO = 204,
  Utente_OpzioneChiusuraAbbattimenti = 218,

  UTENTE_OPERAZIONI_ZOO_PREFERITE = 207,
  Visualizza_UdmAggiuntiva_xSup = 215,

  UTENTE_InterpretazioneInizioFineAnnataAgraria = 217, // in riferimento a UTENTE_InizioFineAnnataAgraria (105)
  //=================================================

  UTENTE_DAA = 753,
  Utente_ChkAccettazioneDaDiversi = 761,

  UTENTE_COD_TIPO_ALLERTA_PREZZO_0_VENDITA = 798,
  UTENTE_COD_TIPO_FATTURA_DEFAULT = 799,

  UTENTE_COD_PERSONALIZZAZIONI_GRIGLIE_KENDO = 818,
  UTENTE_COD_PREFERITI_MENU = 823,
  UTENTE_COD_MODALITA_STAMPA = 824,
  UTENTE_COD_PREFERITI_REPORT_VENDITE = 837,

  // Gestisce se il check mostra firma ODC e' visibile o no, raggiona sulle 3 stampe bio: Op colturali, Materie Prime e Vendite
  UTENTE_Cod_MostraFirmaODCBio = 893,
  // Gestisce se il check mostra data e' precheckato o no, raggiona sulle 3 stampe bio: Op colturali, Materie Prime e Vendite
  Utente_Cod_DefaultMostraDataBio = 894,
  // Gestisce se il check mostra data e' precheckato o no, raggiona sulla stampa Registri ACA
  Utente_Cod_DefaultMostraDataACA = 895,
  // Solo in tipi enumerativi
  UTENTE_COD_PREFERITI_REPORT_ANALISI_ZOO = 896,


  //////costanti per il proxy
  UTENTE_COD_PROXY = 1000,
  UTENTE_COD_USERNAME_PROXY = 1001,
  UTENTE_COD_PASSWORD_PROXY = 1002,
  UTENTE_COD_HOST_PROXY = 1003,

  UTENTE_UDM_Area_COD = 1010,
  UTENTE_CATASTO_PercentoSogliaDifferenzeEvidenziate = 1011,

  UTENTE_GIS = 1012,

  //Impostazioni CDG
  UTENTE_CONTROLLO_SCARICO_CDG = 1055,
  UTENTE_MODALITA_SCARICO_PRODOTTI_CDG = 1055,

  UTENTE_STATI_PANEL_BAR = 1056,
  UTENTE_FILTRI_RICERCA_DOC_CONTABILI = 1057,
  UTENTE_FILTRI_RICERCA_DOCUMENTALE = 1067,

  UTENTE_FILTRI_RICERCA_BILANCIO_DI_MASSA = 1100,

  UTENTE_FILTRI_RICERCA_FILTRONE_VISITE = 1060,

  UTENTE_Operazione_Predefinita_Da_Impianto = 856,

  UTENTE_COD_PREFERITI_REPORT_ACQUISTI = 859,

  UTENTE_COD_PREFERITI_REPORT_ANALISI_PROGETTI = 870,

  FiltroDataScadenzaFarmaco = 900,
  SogliaMinimaPioggeGiornaliere = 901,

  /** Visibilità: SuperUser e per Azienda*/
  UTENTE_MOSTRA_DDT_MENU_AGENDA = 1072,

  /** Visibilità: Superuser, Impresa */
  MENU_AGENDA_VISIBILITA_DOC_CONTABILI = 1078,

  StampaArticolo62ElemCod = 1092,
  ImpedisciCreazioneCarichiMultiriga = 1094,
  DSS_Difesa_Riepilogo_Copertura_Trattamento = 1103,
  ImpresaPadreDefault = 1105,
  SUPERUSER_ModalitaVerificaConformita = 1106,
  UTENTE_COD_DEFAULT_BLOCCO_SALVA_FERTILIZZAZIONI = 1107,
  UTENTE_COD_BLOCCA_DOSERAMEANNOMAX_FERTI = 1108,
  UTENTE_COD_BLOCCA_DOSERAME7ANNIMAX_FERTI = 1109,
  UTENTE_COD_BLOCCA_PRODOTTO_NON_BIO_REGOLAMENTO_BIO_FERTI = 1110,
  UTENTE_COD_BLOCCA_MASSIMALE_DISTRIBUZIONE_N_DPI_FERTI = 1111,
  UTENTE_COD_BLOCCA_INTERVENTO_NON_CONSENTITO = 1112,
  UTENTE_COD_BLOCCA_PRODOTTO_NON_UTILIZZABILE_X_DATA = 1113,
  UTENTE_COD_BLOCCA_PRODOTTO_NON_REGISTRATO_SU_COLTURA = 1114,
  UTENTE_COD_BLOCCA_AVVERSITA_NON_TRATTABILE_DPI = 1115,
  UTENTE_COD_BLOCCA_PRODOTTO_NON_REGISTRATO_SU_AVVERSITA_DPI = 1116,
  UTENTE_COD_BLOCCA_PRODOTTO_NON_UTILIZZABILE_DPI = 1117,
  UTENTE_COD_BLOCCA_PRODOTTO_NON_BIO_REGOLAMENTO_BIO_FITO = 1118,
  SUPERUSER_ModalitaDemetra = 1119,
  //------------------------------------------------------------------------------
  //------------------------------------------------------------------------------
  // AGGIORNARE IL FILE \\rubino2\DOCUMENTAZIONE\GIAS --- Utenti\Utenti_Impostazioni.docx
  //------------------------------------------------------------------------------
  //------------------------------------------------------------------------------

}
