'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.0.30319.1.
'
Namespace Entita.Semplificata

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0"),
     System.Xml.Serialization.XmlRootAttribute("FatturaElettronicaSemplificata", [Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0", IsNullable:=False)>
    Partial Public Class FatturaElettronicaType : Implements IFatturaElettronica

        Private fatturaElettronicaHeaderField As FatturaElettronicaHeaderType

        Private fatturaElettronicaBodyField() As FatturaElettronicaBodyType

        Private signatureField As SignatureType

        Private versioneField As FormatoTrasmissioneType

        Private sistemaEmittenteField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property FatturaElettronicaHeader() As FatturaElettronicaHeaderType
            Get
                Return Me.fatturaElettronicaHeaderField
            End Get
            Set
                Me.fatturaElettronicaHeaderField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("FatturaElettronicaBody", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property FatturaElettronicaBody() As FatturaElettronicaBodyType()
            Get
                Return Me.fatturaElettronicaBodyField
            End Get
            Set
                Me.fatturaElettronicaBodyField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>
        Public Property Signature() As SignatureType
            Get
                Return Me.signatureField
            End Get
            Set
                Me.signatureField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property versione() As FormatoTrasmissioneType
            Get
                Return Me.versioneField
            End Get
            Set
                Me.versioneField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="normalizedString")>
        Public Property SistemaEmittente() As String
            Get
                Return Me.sistemaEmittenteField
            End Get
            Set
                Me.sistemaEmittenteField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")>
    Partial Public Class FatturaElettronicaHeaderType

        Private datiTrasmissioneField As DatiTrasmissioneType

        Private cedentePrestatoreField As CedentePrestatoreType

        Private cessionarioCommittenteField As CessionarioCommittenteType

        Private soggettoEmittenteField As SoggettoEmittenteType

        Private soggettoEmittenteFieldSpecified As Boolean

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property DatiTrasmissione() As DatiTrasmissioneType
            Get
                Return Me.datiTrasmissioneField
            End Get
            Set
                Me.datiTrasmissioneField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property CedentePrestatore() As CedentePrestatoreType
            Get
                Return Me.cedentePrestatoreField
            End Get
            Set
                Me.cedentePrestatoreField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property CessionarioCommittente() As CessionarioCommittenteType
            Get
                Return Me.cessionarioCommittenteField
            End Get
            Set
                Me.cessionarioCommittenteField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property SoggettoEmittente() As SoggettoEmittenteType
            Get
                Return Me.soggettoEmittenteField
            End Get
            Set
                Me.soggettoEmittenteField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property SoggettoEmittenteSpecified() As Boolean
            Get
                Return Me.soggettoEmittenteFieldSpecified
            End Get
            Set
                Me.soggettoEmittenteFieldSpecified = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")>
    Partial Public Class DatiTrasmissioneType

        Private idTrasmittenteField As IdFiscaleType

        Private progressivoInvioField As String

        Private formatoTrasmissioneField As FormatoTrasmissioneType

        Private codiceDestinatarioField As String

        Private pECDestinatarioField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property IdTrasmittente() As IdFiscaleType
            Get
                Return Me.idTrasmittenteField
            End Get
            Set
                Me.idTrasmittenteField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString")>
        Public Property ProgressivoInvio() As String
            Get
                Return Me.progressivoInvioField
            End Get
            Set
                Me.progressivoInvioField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property FormatoTrasmissione() As FormatoTrasmissioneType
            Get
                Return Me.formatoTrasmissioneField
            End Get
            Set
                Me.formatoTrasmissioneField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property CodiceDestinatario() As String
            Get
                Return Me.codiceDestinatarioField
            End Get
            Set
                Me.codiceDestinatarioField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="token")>
        Public Property PECDestinatario() As String
            Get
                Return Me.pECDestinatarioField
            End Get
            Set
                Me.pECDestinatarioField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")>
    Partial Public Class IdFiscaleType

        Private idPaeseField As String

        Private idCodiceField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property IdPaese() As String
            Get
                Return Me.idPaeseField
            End Get
            Set
                Me.idPaeseField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property IdCodice() As String
            Get
                Return Me.idCodiceField
            End Get
            Set
                Me.idCodiceField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),
     System.Xml.Serialization.XmlRootAttribute("Object", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)>
    Partial Public Class ObjectType

        Private anyField() As System.Xml.XmlNode

        Private idField As String

        Private mimeTypeField As String

        Private encodingField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(),
         System.Xml.Serialization.XmlAnyElementAttribute()>
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property MimeType() As String
            Get
                Return Me.mimeTypeField
            End Get
            Set
                Me.mimeTypeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>
        Public Property Encoding() As String
            Get
                Return Me.encodingField
            End Get
            Set
                Me.encodingField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),
     System.Xml.Serialization.XmlRootAttribute("SPKIData", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)>
    Partial Public Class SPKIDataType

        Private sPKISexpField()() As Byte

        Private anyField As System.Xml.XmlElement

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("SPKISexp", DataType:="base64Binary")>
        Public Property SPKISexp() As Byte()()
            Get
                Return Me.sPKISexpField
            End Get
            Set
                Me.sPKISexpField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>
        Public Property Any() As System.Xml.XmlElement
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),
     System.Xml.Serialization.XmlRootAttribute("PGPData", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)>
    Partial Public Class PGPDataType

        Private itemsField() As Object

        Private itemsElementNameField() As ItemsChoiceType4

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute(),
         System.Xml.Serialization.XmlElementAttribute("PGPKeyID", GetType(Byte()), DataType:="base64Binary"),
         System.Xml.Serialization.XmlElementAttribute("PGPKeyPacket", GetType(Byte()), DataType:="base64Binary"),
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")>
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"),
         System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property ItemsElementName() As ItemsChoiceType4()
            Get
                Return Me.itemsElementNameField
            End Get
            Set
                Me.itemsElementNameField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema:=False)>
    Public Enum ItemsChoiceType4

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("##any:")>
        Item

        '''<remarks/>
        PGPKeyID

        '''<remarks/>
        PGPKeyPacket
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>
    Partial Public Class X509IssuerSerialType

        Private x509IssuerNameField As String

        Private x509SerialNumberField As String

        '''<remarks/>
        Public Property X509IssuerName() As String
            Get
                Return Me.x509IssuerNameField
            End Get
            Set
                Me.x509IssuerNameField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>
        Public Property X509SerialNumber() As String
            Get
                Return Me.x509SerialNumberField
            End Get
            Set
                Me.x509SerialNumberField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),
     System.Xml.Serialization.XmlRootAttribute("X509Data", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)>
    Partial Public Class X509DataType

        Private itemsField() As Object

        Private itemsElementNameField() As ItemsChoiceType3

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute(),
         System.Xml.Serialization.XmlElementAttribute("X509CRL", GetType(Byte()), DataType:="base64Binary"),
         System.Xml.Serialization.XmlElementAttribute("X509Certificate", GetType(Byte()), DataType:="base64Binary"),
         System.Xml.Serialization.XmlElementAttribute("X509IssuerSerial", GetType(X509IssuerSerialType)),
         System.Xml.Serialization.XmlElementAttribute("X509SKI", GetType(Byte()), DataType:="base64Binary"),
         System.Xml.Serialization.XmlElementAttribute("X509SubjectName", GetType(String)),
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")>
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"),
         System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property ItemsElementName() As ItemsChoiceType3()
            Get
                Return Me.itemsElementNameField
            End Get
            Set
                Me.itemsElementNameField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema:=False)>
    Public Enum ItemsChoiceType3

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("##any:")>
        Item

        '''<remarks/>
        X509CRL

        '''<remarks/>
        X509Certificate

        '''<remarks/>
        X509IssuerSerial

        '''<remarks/>
        X509SKI

        '''<remarks/>
        X509SubjectName
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),
     System.Xml.Serialization.XmlRootAttribute("RetrievalMethod", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)>
    Partial Public Class RetrievalMethodType

        Private transformsField() As TransformType

        Private uRIField As String

        Private typeField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable:=False)>
        Public Property Transforms() As TransformType()
            Get
                Return Me.transformsField
            End Get
            Set
                Me.transformsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>
        Public Property URI() As String
            Get
                Return Me.uRIField
            End Get
            Set
                Me.uRIField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),
     System.Xml.Serialization.XmlRootAttribute("Transform", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)>
    Partial Public Class TransformType

        Private itemsField() As Object

        Private textField() As String

        Private algorithmField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute(),
         System.Xml.Serialization.XmlElementAttribute("XPath", GetType(String))>
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),
     System.Xml.Serialization.XmlRootAttribute("RSAKeyValue", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)>
    Partial Public Class RSAKeyValueType

        Private modulusField() As Byte

        Private exponentField() As Byte

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>
        Public Property Modulus() As Byte()
            Get
                Return Me.modulusField
            End Get
            Set
                Me.modulusField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>
        Public Property Exponent() As Byte()
            Get
                Return Me.exponentField
            End Get
            Set
                Me.exponentField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),
     System.Xml.Serialization.XmlRootAttribute("DSAKeyValue", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)>
    Partial Public Class DSAKeyValueType

        Private pField() As Byte

        Private qField() As Byte

        Private gField() As Byte

        Private yField() As Byte

        Private jField() As Byte

        Private seedField() As Byte

        Private pgenCounterField() As Byte

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>
        Public Property P() As Byte()
            Get
                Return Me.pField
            End Get
            Set
                Me.pField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>
        Public Property Q() As Byte()
            Get
                Return Me.qField
            End Get
            Set
                Me.qField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>
        Public Property G() As Byte()
            Get
                Return Me.gField
            End Get
            Set
                Me.gField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>
        Public Property Y() As Byte()
            Get
                Return Me.yField
            End Get
            Set
                Me.yField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>
        Public Property J() As Byte()
            Get
                Return Me.jField
            End Get
            Set
                Me.jField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>
        Public Property Seed() As Byte()
            Get
                Return Me.seedField
            End Get
            Set
                Me.seedField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>
        Public Property PgenCounter() As Byte()
            Get
                Return Me.pgenCounterField
            End Get
            Set
                Me.pgenCounterField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),
     System.Xml.Serialization.XmlRootAttribute("KeyValue", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)>
    Partial Public Class KeyValueType

        Private itemField As Object

        Private textField() As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute(),
         System.Xml.Serialization.XmlElementAttribute("DSAKeyValue", GetType(DSAKeyValueType)),
         System.Xml.Serialization.XmlElementAttribute("RSAKeyValue", GetType(RSAKeyValueType))>
        Public Property Item() As Object
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),
     System.Xml.Serialization.XmlRootAttribute("KeyInfo", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)>
    Partial Public Class KeyInfoType

        Private itemsField() As Object

        Private itemsElementNameField() As ItemsChoiceType5

        Private textField() As String

        Private idField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute(),
         System.Xml.Serialization.XmlElementAttribute("KeyName", GetType(String)),
         System.Xml.Serialization.XmlElementAttribute("KeyValue", GetType(KeyValueType)),
         System.Xml.Serialization.XmlElementAttribute("MgmtData", GetType(String)),
         System.Xml.Serialization.XmlElementAttribute("PGPData", GetType(PGPDataType)),
         System.Xml.Serialization.XmlElementAttribute("RetrievalMethod", GetType(RetrievalMethodType)),
         System.Xml.Serialization.XmlElementAttribute("SPKIData", GetType(SPKIDataType)),
         System.Xml.Serialization.XmlElementAttribute("X509Data", GetType(X509DataType)),
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")>
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"),
         System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property ItemsElementName() As ItemsChoiceType5()
            Get
                Return Me.itemsElementNameField
            End Get
            Set
                Me.itemsElementNameField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema:=False)>
    Public Enum ItemsChoiceType5

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("##any:")>
        Item

        '''<remarks/>
        KeyName

        '''<remarks/>
        KeyValue

        '''<remarks/>
        MgmtData

        '''<remarks/>
        PGPData

        '''<remarks/>
        RetrievalMethod

        '''<remarks/>
        SPKIData

        '''<remarks/>
        X509Data
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),
     System.Xml.Serialization.XmlRootAttribute("SignatureValue", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)>
    Partial Public Class SignatureValueType

        Private idField As String

        Private valueField() As Byte

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(DataType:="base64Binary")>
        Public Property Value() As Byte()
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),
     System.Xml.Serialization.XmlRootAttribute("DigestMethod", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)>
    Partial Public Class DigestMethodType

        Private anyField() As System.Xml.XmlNode

        Private algorithmField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(),
         System.Xml.Serialization.XmlAnyElementAttribute()>
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),
     System.Xml.Serialization.XmlRootAttribute("Reference", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)>
    Partial Public Class ReferenceType

        Private transformsField() As TransformType

        Private digestMethodField As DigestMethodType

        Private digestValueField() As Byte

        Private idField As String

        Private uRIField As String

        Private typeField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable:=False)>
        Public Property Transforms() As TransformType()
            Get
                Return Me.transformsField
            End Get
            Set
                Me.transformsField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property DigestMethod() As DigestMethodType
            Get
                Return Me.digestMethodField
            End Get
            Set
                Me.digestMethodField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>
        Public Property DigestValue() As Byte()
            Get
                Return Me.digestValueField
            End Get
            Set
                Me.digestValueField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>
        Public Property URI() As String
            Get
                Return Me.uRIField
            End Get
            Set
                Me.uRIField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),
     System.Xml.Serialization.XmlRootAttribute("SignatureMethod", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)>
    Partial Public Class SignatureMethodType

        Private hMACOutputLengthField As String

        Private anyField() As System.Xml.XmlNode

        Private algorithmField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>
        Public Property HMACOutputLength() As String
            Get
                Return Me.hMACOutputLengthField
            End Get
            Set
                Me.hMACOutputLengthField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(),
         System.Xml.Serialization.XmlAnyElementAttribute()>
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),
     System.Xml.Serialization.XmlRootAttribute("CanonicalizationMethod", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)>
    Partial Public Class CanonicalizationMethodType

        Private anyField() As System.Xml.XmlNode

        Private algorithmField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(),
         System.Xml.Serialization.XmlAnyElementAttribute()>
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),
     System.Xml.Serialization.XmlRootAttribute("SignedInfo", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)>
    Partial Public Class SignedInfoType

        Private canonicalizationMethodField As CanonicalizationMethodType

        Private signatureMethodField As SignatureMethodType

        Private referenceField() As ReferenceType

        Private idField As String

        '''<remarks/>
        Public Property CanonicalizationMethod() As CanonicalizationMethodType
            Get
                Return Me.canonicalizationMethodField
            End Get
            Set
                Me.canonicalizationMethodField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property SignatureMethod() As SignatureMethodType
            Get
                Return Me.signatureMethodField
            End Get
            Set
                Me.signatureMethodField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Reference")>
        Public Property Reference() As ReferenceType()
            Get
                Return Me.referenceField
            End Get
            Set
                Me.referenceField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),
     System.Xml.Serialization.XmlRootAttribute("Signature", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)>
    Partial Public Class SignatureType

        Private signedInfoField As SignedInfoType

        Private signatureValueField As SignatureValueType

        Private keyInfoField As KeyInfoType

        Private objectField() As ObjectType

        Private idField As String

        '''<remarks/>
        Public Property SignedInfo() As SignedInfoType
            Get
                Return Me.signedInfoField
            End Get
            Set
                Me.signedInfoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property SignatureValue() As SignatureValueType
            Get
                Return Me.signatureValueField
            End Get
            Set
                Me.signatureValueField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property KeyInfo() As KeyInfoType
            Get
                Return Me.keyInfoField
            End Get
            Set
                Me.keyInfoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Object")>
        Public Property [Object]() As ObjectType()
            Get
                Return Me.objectField
            End Get
            Set
                Me.objectField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")>
    Partial Public Class AllegatiType

        Private nomeAttachmentField As String

        Private algoritmoCompressioneField As String

        Private formatoAttachmentField As String

        Private descrizioneAttachmentField As String

        Private attachmentField() As Byte

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString")>
        Public Property NomeAttachment() As String
            Get
                Return Me.nomeAttachmentField
            End Get
            Set
                Me.nomeAttachmentField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString")>
        Public Property AlgoritmoCompressione() As String
            Get
                Return Me.algoritmoCompressioneField
            End Get
            Set
                Me.algoritmoCompressioneField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString")>
        Public Property FormatoAttachment() As String
            Get
                Return Me.formatoAttachmentField
            End Get
            Set
                Me.formatoAttachmentField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString")>
        Public Property DescrizioneAttachment() As String
            Get
                Return Me.descrizioneAttachmentField
            End Get
            Set
                Me.descrizioneAttachmentField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>
        Public Property Attachment() As Byte()
            Get
                Return Me.attachmentField
            End Get
            Set
                Me.attachmentField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")>
    Partial Public Class DatiIVAType

        Private impostaField As Decimal

        Private impostaFieldSpecified As Boolean

        Private aliquotaField As Decimal

        Private aliquotaFieldSpecified As Boolean

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Imposta() As Decimal
            Get
                Return Me.impostaField
            End Get
            Set
                Me.impostaField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property ImpostaSpecified() As Boolean
            Get
                Return Me.impostaFieldSpecified
            End Get
            Set
                Me.impostaFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Aliquota() As Decimal
            Get
                Return Me.aliquotaField
            End Get
            Set
                Me.aliquotaField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property AliquotaSpecified() As Boolean
            Get
                Return Me.aliquotaFieldSpecified
            End Get
            Set
                Me.aliquotaFieldSpecified = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")>
    Partial Public Class DatiBeniServiziType

        Private descrizioneField As String

        Private importoField As Decimal

        Private datiIVAField As DatiIVAType

        Private naturaField As NaturaType

        Private naturaFieldSpecified As Boolean

        Private riferimentoNormativoField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString")>
        Public Property Descrizione() As String
            Get
                Return Me.descrizioneField
            End Get
            Set
                Me.descrizioneField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Importo() As Decimal
            Get
                Return Me.importoField
            End Get
            Set
                Me.importoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property DatiIVA() As DatiIVAType
            Get
                Return Me.datiIVAField
            End Get
            Set
                Me.datiIVAField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Natura() As NaturaType
            Get
                Return Me.naturaField
            End Get
            Set
                Me.naturaField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property NaturaSpecified() As Boolean
            Get
                Return Me.naturaFieldSpecified
            End Get
            Set
                Me.naturaFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString")>
        Public Property RiferimentoNormativo() As String
            Get
                Return Me.riferimentoNormativoField
            End Get
            Set
                Me.riferimentoNormativoField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")>
    Public Enum NaturaType

        '''<remarks/>
        N1

        '''<remarks/>
        N2

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("N2.1")>
        N21

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("N2.2")>
        N22

        '''<remarks/>
        N3

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("N3.1")>
        N31

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("N3.2")>
        N32

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("N3.3")>
        N33

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("N3.4")>
        N34

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("N3.5")>
        N35

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("N3.6")>
        N36

        '''<remarks/>
        N4

        '''<remarks/>
        N5
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")>
    Partial Public Class DatiFatturaRettificataType

        Private numeroFRField As String

        Private dataFRField As Date

        Private elementiRettificatiField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString")>
        Public Property NumeroFR() As String
            Get
                Return Me.numeroFRField
            End Get
            Set
                Me.numeroFRField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="date")>
        Public Property DataFR() As Date
            Get
                Return Me.dataFRField
            End Get
            Set
                Me.dataFRField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString")>
        Public Property ElementiRettificati() As String
            Get
                Return Me.elementiRettificatiField
            End Get
            Set
                Me.elementiRettificatiField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")>
    Partial Public Class DatiGeneraliDocumentoType

        Private tipoDocumentoField As TipoDocumentoType

        Private divisaField As String

        Private dataField As Date

        Private numeroField As String

        Private bolloVirtualeField As BolloVirtualeType

        Private bolloVirtualeFieldSpecified As Boolean

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property TipoDocumento() As TipoDocumentoType
            Get
                Return Me.tipoDocumentoField
            End Get
            Set
                Me.tipoDocumentoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Divisa() As String
            Get
                Return Me.divisaField
            End Get
            Set
                Me.divisaField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="date")>
        Public Property Data() As Date
            Get
                Return Me.dataField
            End Get
            Set
                Me.dataField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString")>
        Public Property Numero() As String
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property BolloVirtuale() As BolloVirtualeType
            Get
                Return Me.bolloVirtualeField
            End Get
            Set
                Me.bolloVirtualeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property BolloVirtualeSpecified() As Boolean
            Get
                Return Me.bolloVirtualeFieldSpecified
            End Get
            Set
                Me.bolloVirtualeFieldSpecified = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")>
    Public Enum TipoDocumentoType

        '''<remarks/>
        TD07

        '''<remarks/>
        TD08

        '''<remarks/>
        TD09
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")>
    Public Enum BolloVirtualeType

        '''<remarks/>
        SI
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")>
    Partial Public Class DatiGeneraliType

        Private datiGeneraliDocumentoField As DatiGeneraliDocumentoType

        Private datiFatturaRettificataField As DatiFatturaRettificataType

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property DatiGeneraliDocumento() As DatiGeneraliDocumentoType
            Get
                Return Me.datiGeneraliDocumentoField
            End Get
            Set
                Me.datiGeneraliDocumentoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property DatiFatturaRettificata() As DatiFatturaRettificataType
            Get
                Return Me.datiFatturaRettificataField
            End Get
            Set
                Me.datiFatturaRettificataField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")>
    Partial Public Class FatturaElettronicaBodyType

        Private datiGeneraliField As DatiGeneraliType

        Private datiBeniServiziField() As DatiBeniServiziType

        Private allegatiField() As AllegatiType

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property DatiGenerali() As DatiGeneraliType
            Get
                Return Me.datiGeneraliField
            End Get
            Set
                Me.datiGeneraliField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("DatiBeniServizi", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property DatiBeniServizi() As DatiBeniServiziType()
            Get
                Return Me.datiBeniServiziField
            End Get
            Set
                Me.datiBeniServiziField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Allegati", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Allegati() As AllegatiType()
            Get
                Return Me.allegatiField
            End Get
            Set
                Me.allegatiField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")>
    Partial Public Class AltriDatiIdentificativiType

        Private itemsField() As String

        Private itemsElementNameField() As ItemsChoiceType2

        Private sedeField As IndirizzoType

        Private stabileOrganizzazioneField As IndirizzoType

        Private rappresentanteFiscaleField As RappresentanteFiscaleType

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Cognome", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString"),
         System.Xml.Serialization.XmlElementAttribute("Denominazione", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString"),
         System.Xml.Serialization.XmlElementAttribute("Nome", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString"),
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")>
        Public Property Items() As String()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"),
         System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property ItemsElementName() As ItemsChoiceType2()
            Get
                Return Me.itemsElementNameField
            End Get
            Set
                Me.itemsElementNameField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Sede() As IndirizzoType
            Get
                Return Me.sedeField
            End Get
            Set
                Me.sedeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property StabileOrganizzazione() As IndirizzoType
            Get
                Return Me.stabileOrganizzazioneField
            End Get
            Set
                Me.stabileOrganizzazioneField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property RappresentanteFiscale() As RappresentanteFiscaleType
            Get
                Return Me.rappresentanteFiscaleField
            End Get
            Set
                Me.rappresentanteFiscaleField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0", IncludeInSchema:=False)>
    Public Enum ItemsChoiceType2

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute(":Cognome")>
        Cognome

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute(":Denominazione")>
        Denominazione

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute(":Nome")>
        Nome
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")>
    Partial Public Class IndirizzoType

        Private indirizzoField As String

        Private numeroCivicoField As String

        Private cAPField As String

        Private comuneField As String

        Private provinciaField As String

        Private nazioneField As String

        Public Sub New()
            MyBase.New
            Me.nazioneField = "IT"
        End Sub

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString")>
        Public Property Indirizzo() As String
            Get
                Return Me.indirizzoField
            End Get
            Set
                Me.indirizzoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString")>
        Public Property NumeroCivico() As String
            Get
                Return Me.numeroCivicoField
            End Get
            Set
                Me.numeroCivicoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property CAP() As String
            Get
                Return Me.cAPField
            End Get
            Set
                Me.cAPField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString")>
        Public Property Comune() As String
            Get
                Return Me.comuneField
            End Get
            Set
                Me.comuneField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Provincia() As String
            Get
                Return Me.provinciaField
            End Get
            Set
                Me.provinciaField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Nazione() As String
            Get
                Return Me.nazioneField
            End Get
            Set
                Me.nazioneField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")>
    Partial Public Class RappresentanteFiscaleType

        Private idFiscaleIVAField As IdFiscaleType

        Private itemsField() As String

        Private itemsElementNameField() As ItemsChoiceType1

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property IdFiscaleIVA() As IdFiscaleType
            Get
                Return Me.idFiscaleIVAField
            End Get
            Set
                Me.idFiscaleIVAField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Cognome", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString"),
         System.Xml.Serialization.XmlElementAttribute("Denominazione", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString"),
         System.Xml.Serialization.XmlElementAttribute("Nome", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString"),
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")>
        Public Property Items() As String()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"),
         System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property ItemsElementName() As ItemsChoiceType1()
            Get
                Return Me.itemsElementNameField
            End Get
            Set
                Me.itemsElementNameField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0", IncludeInSchema:=False)>
    Public Enum ItemsChoiceType1

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute(":Cognome")>
        Cognome

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute(":Denominazione")>
        Denominazione

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute(":Nome")>
        Nome
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")>
    Partial Public Class IdentificativiFiscaliType

        Private idFiscaleIVAField As IdFiscaleType

        Private codiceFiscaleField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property IdFiscaleIVA() As IdFiscaleType
            Get
                Return Me.idFiscaleIVAField
            End Get
            Set
                Me.idFiscaleIVAField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property CodiceFiscale() As String
            Get
                Return Me.codiceFiscaleField
            End Get
            Set
                Me.codiceFiscaleField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")>
    Partial Public Class CessionarioCommittenteType

        Private identificativiFiscaliField As IdentificativiFiscaliType

        Private altriDatiIdentificativiField As AltriDatiIdentificativiType

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property IdentificativiFiscali() As IdentificativiFiscaliType
            Get
                Return Me.identificativiFiscaliField
            End Get
            Set
                Me.identificativiFiscaliField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property AltriDatiIdentificativi() As AltriDatiIdentificativiType
            Get
                Return Me.altriDatiIdentificativiField
            End Get
            Set
                Me.altriDatiIdentificativiField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")>
    Partial Public Class IscrizioneREAType

        Private ufficioField As String

        Private numeroREAField As String

        Private capitaleSocialeField As Decimal

        Private capitaleSocialeFieldSpecified As Boolean

        Private socioUnicoField As SocioUnicoType

        Private socioUnicoFieldSpecified As Boolean

        Private statoLiquidazioneField As StatoLiquidazioneType

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Ufficio() As String
            Get
                Return Me.ufficioField
            End Get
            Set
                Me.ufficioField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString")>
        Public Property NumeroREA() As String
            Get
                Return Me.numeroREAField
            End Get
            Set
                Me.numeroREAField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property CapitaleSociale() As Decimal
            Get
                Return Me.capitaleSocialeField
            End Get
            Set
                Me.capitaleSocialeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property CapitaleSocialeSpecified() As Boolean
            Get
                Return Me.capitaleSocialeFieldSpecified
            End Get
            Set
                Me.capitaleSocialeFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property SocioUnico() As SocioUnicoType
            Get
                Return Me.socioUnicoField
            End Get
            Set
                Me.socioUnicoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property SocioUnicoSpecified() As Boolean
            Get
                Return Me.socioUnicoFieldSpecified
            End Get
            Set
                Me.socioUnicoFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property StatoLiquidazione() As StatoLiquidazioneType
            Get
                Return Me.statoLiquidazioneField
            End Get
            Set
                Me.statoLiquidazioneField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")>
    Public Enum SocioUnicoType

        '''<remarks/>
        SU

        '''<remarks/>
        SM
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")>
    Public Enum StatoLiquidazioneType

        '''<remarks/>
        LS

        '''<remarks/>
        LN
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")>
    Partial Public Class CedentePrestatoreType

        Private idFiscaleIVAField As IdFiscaleType

        Private codiceFiscaleField As String

        Private itemsField() As String

        Private itemsElementNameField() As ItemsChoiceType

        Private sedeField As IndirizzoType

        Private stabileOrganizzazioneField As IndirizzoType

        Private rappresentanteFiscaleField As RappresentanteFiscaleType

        Private iscrizioneREAField As IscrizioneREAType

        Private regimeFiscaleField As RegimeFiscaleType

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property IdFiscaleIVA() As IdFiscaleType
            Get
                Return Me.idFiscaleIVAField
            End Get
            Set
                Me.idFiscaleIVAField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property CodiceFiscale() As String
            Get
                Return Me.codiceFiscaleField
            End Get
            Set
                Me.codiceFiscaleField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Cognome", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString"),
         System.Xml.Serialization.XmlElementAttribute("Denominazione", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString"),
         System.Xml.Serialization.XmlElementAttribute("Nome", GetType(String), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="normalizedString"),
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")>
        Public Property Items() As String()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"),
         System.Xml.Serialization.XmlIgnoreAttribute()>
        Public Property ItemsElementName() As ItemsChoiceType()
            Get
                Return Me.itemsElementNameField
            End Get
            Set
                Me.itemsElementNameField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property Sede() As IndirizzoType
            Get
                Return Me.sedeField
            End Get
            Set
                Me.sedeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property StabileOrganizzazione() As IndirizzoType
            Get
                Return Me.stabileOrganizzazioneField
            End Get
            Set
                Me.stabileOrganizzazioneField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property RappresentanteFiscale() As RappresentanteFiscaleType
            Get
                Return Me.rappresentanteFiscaleField
            End Get
            Set
                Me.rappresentanteFiscaleField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property IscrizioneREA() As IscrizioneREAType
            Get
                Return Me.iscrizioneREAField
            End Get
            Set
                Me.iscrizioneREAField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>
        Public Property RegimeFiscale() As RegimeFiscaleType
            Get
                Return Me.regimeFiscaleField
            End Get
            Set
                Me.regimeFiscaleField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0", IncludeInSchema:=False)>
    Public Enum ItemsChoiceType

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute(":Cognome")>
        Cognome

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute(":Denominazione")>
        Denominazione

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute(":Nome")>
        Nome
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")>
    Public Enum RegimeFiscaleType

        '''<remarks/>
        RF01

        '''<remarks/>
        RF02

        '''<remarks/>
        RF04

        '''<remarks/>
        RF05

        '''<remarks/>
        RF06

        '''<remarks/>
        RF07

        '''<remarks/>
        RF08

        '''<remarks/>
        RF09

        '''<remarks/>
        RF10

        '''<remarks/>
        RF11

        '''<remarks/>
        RF12

        '''<remarks/>
        RF13

        '''<remarks/>
        RF14

        '''<remarks/>
        RF15

        '''<remarks/>
        RF16

        '''<remarks/>
        RF17

        '''<remarks/>
        RF19

        '''<remarks/>
        RF18
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")>
    Public Enum FormatoTrasmissioneType

        '''<remarks/>
        FSM10
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.0")>
    Public Enum SoggettoEmittenteType

        '''<remarks/>
        CC

        '''<remarks/>
        TZ
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),
     System.Xml.Serialization.XmlRootAttribute("Transforms", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)>
    Partial Public Class TransformsType

        Private transformField() As TransformType

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Transform")>
        Public Property Transform() As TransformType()
            Get
                Return Me.transformField
            End Get
            Set
                Me.transformField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),
     System.Xml.Serialization.XmlRootAttribute("Manifest", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)>
    Partial Public Class ManifestType

        Private referenceField() As ReferenceType

        Private idField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Reference")>
        Public Property Reference() As ReferenceType()
            Get
                Return Me.referenceField
            End Get
            Set
                Me.referenceField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),
     System.Xml.Serialization.XmlRootAttribute("SignatureProperties", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)>
    Partial Public Class SignaturePropertiesType

        Private signaturePropertyField() As SignaturePropertyType

        Private idField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("SignatureProperty")>
        Public Property SignatureProperty() As SignaturePropertyType()
            Get
                Return Me.signaturePropertyField
            End Get
            Set
                Me.signaturePropertyField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),
     System.Xml.Serialization.XmlRootAttribute("SignatureProperty", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)>
    Partial Public Class SignaturePropertyType

        Private itemsField() As System.Xml.XmlElement

        Private textField() As String

        Private targetField As String

        Private idField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>
        Public Property Items() As System.Xml.XmlElement()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>
        Public Property Target() As String
            Get
                Return Me.targetField
            End Get
            Set
                Me.targetField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = Value
            End Set
        End Property
    End Class
End Namespace
